"""
backend/seed_tr_remaining.py

Kullanici istegi (22 Eylul 2026): "Turkce'de kalan kelime sayisi zaten az
kalmisti, bana kalanlar icin yeni script olustur" -- ve devaminda kritik bir
duzeltme: "source_lang='tr', target_lang='' diger tum diller olmali, yani
db de tr olan kelimenin 11 dilde karsiligi olmali, suan calisan diger
scriptler de bu sekilde calismali".

ONCEKI (HATALI) YONTEM: Bir TR kavramin "tamamlandi" sayilip sayilmayacagi
SADECE source_lang='tr', target_lang='en' satirinin var olup olmadigina
bakilarak belirleniyordu. Bu YANLIS -- bir TR kelime 'en' karsiligina sahip
olsa bile, diger 10 hedef dilden (ar, de, es, fr, it, ja, ko, pt, ru, zh)
bazilari MyMemory kesintisi/rate-limit yuzunden hala eksik olabilir. Bu
durumda kavram yanlislikla "tamam" sayilip script'in REMAINING_CONCEPTS
listesine hic girmiyordu -- yani o eksik hedef diller HICBIR ZAMAN
tamamlanmayacakti.

DUZELTILMIS YONTEM (bu script): general_word_pool'da source_lang='tr' olan
her kelime icin, kac FARKLI target_lang degeri oldugu sayildi (count(distinct
target_lang)). ALL_LANGS 12 dilden olusuyor (ar, de, en, es, fr, it, ja, ko,
pt, ru, tr, zh); tr kendisi haric 11 hedef dil kaliyor -- yani "tamamlandi"
kriteri artik: bu TR kelime 11 target_lang'in HEPSINDE var mi?

Bir kavram su iki durumdan HERHANGI BIRINDEYSE bu script'in
REMAINING_CONCEPTS listesine dahil edildi:
  1) DB'de bu kavrama karsilik gelen bir TR kelime HIC bulunamadi (concept
     hic baslamamis), VEYA
  2) TR kelime bulundu AMA 11 hedef dilin hepsinde degil (eksik/yarim kalmis).

(22 Eylul 2026 itibariyle: 612 kavram hic baslamamis, 213 kavram yarim kalmis
 -- toplam 825 kavram. Onceki (hatali) yontem sadece 594 kavram buluyordu ve
 213'luk yarim-kalmis grubu tamamen atlıyordu.)

NOT (kavram eslestirme yontemi hakkinda, KESIN degil): general_word_pool'da
hangi TR kelimenin hangi Ingilizce kavramdan turedigini tutan ayri bir sutun
yok. Bu yuzden, source_lang='tr' AND target_lang='en' olan satirlarin
'meaning' alani (TR kelimenin Ingilizceye GERI cevirisi), kavram metniyle
(kucuk harfe cevrilip 'to '/'a '/'an ' onekleri silinerek) TAM ESLESIP
eslesmedigine bakilarak kavram tespit edildi. Bu YAKLASIK bir yontem -- ama
GUVENLI TARAFTA hata yapiyor: bir kavram yanlislikla "eksik" listesine
girebilir (o zaman sadece 1 fazladan anchor-cevirisi denemesi yapilir, zarar
yok), ama GERCEKTEN eksik bir kavram bu listeden ASLA disarida kalamaz.

Kalan mantigin tamami (gercek MyMemory cevirisi, gercek sozluk aramasi,
idempotent ekleme -- yani zaten var olan (source_lang, target_lang, word)
satirlari word_exists() ile atlanir, ag-hatasi retry, rate-limit devre
kesici) BIREBIR seed_lang_core.py'den import edilip kullaniliyor, hicbir sey
KOPYALANMADI/tekrar yazilmadi. Bu sayede, yarim-kalmis bir TR kelime icin
get_source_word() ayni (veya farkli) bir TR kelime uretse bile, seed_target()
zaten var olan hedef-dil satirlarini atlayip SADECE eksik olanlari ekler --
mukerrer veri veya deger degisikligi olmaz.

CALISTIRMA:
    cd backend
    venv\\Scripts\\activate      # Windows
    python seed_tr_remaining.py

Kesintiye ugrarsa (Ctrl+C, rate-limit devre kesici, ag hatasi) GUVENLE ayni
komutla tekrar calistirilip kaldigi yerden devam eder (idempotent -- zaten
eklenen (source_lang, target_lang, word) satirlari tekrar sorgulanmaz).
"""

import asyncio

from seed_lang_core import (
    ALL_LANGS,
    ANCHOR_FAILURE_CIRCUIT_BREAKER,
    REQUEST_DELAY_SECONDS,
    RateLimitSuspected,
    get_source_word,
    seed_target,
)

SOURCE_LANG = "tr"

# 22 Eylul 2026 itibariyle general_word_pool'da (source_lang='tr') henuz
# 11 hedef dilin HEPSINDE karsiligi olmayan kavramlar (612 hic baslamamis +
# 213 yarim kalmis = 825 toplam). Yontem icin yukaridaki docstring'e bakin.
# Veritabanindan sorgulanarak elde edildi (elle yazilmadi/uydurulmadi).
REMAINING_CONCEPTS: list[tuple[str, str]] = [
    ("abate", "advanced"),
    ("abdicate", "advanced"),
    ("abide", "advanced"),
    ("abrogate", "advanced"),
    ("abstain", "advanced"),
    ("abstruse", "advanced"),
    ("accumulate", "advanced"),
    ("acquiesce", "advanced"),
    ("acquired", "advanced"),
    ("adhere", "advanced"),
    ("adjudicate", "advanced"),
    ("aggregate", "advanced"),
    ("agitate", "advanced"),
    ("albeit", "advanced"),
    ("alienate", "advanced"),
    ("alleviate", "advanced"),
    ("allocate", "advanced"),
    ("allot", "advanced"),
    ("altruism", "advanced"),
    ("altruistic", "advanced"),
    ("amalgamate", "advanced"),
    ("amass", "advanced"),
    ("ambiguous", "advanced"),
    ("ambivalence", "advanced"),
    ("amplify", "advanced"),
    ("anarchic", "advanced"),
    ("anecdotal", "advanced"),
    ("annul", "advanced"),
    ("anomalous", "advanced"),
    ("anomaly", "advanced"),
    ("apathetic", "advanced"),
    ("apathy", "advanced"),
    ("appease", "advanced"),
    ("apportion", "advanced"),
    ("apprehend", "advanced"),
    ("approximate", "advanced"),
    ("arbitrate", "advanced"),
    ("arbitration", "advanced"),
    ("arcane", "advanced"),
    ("archetypal", "advanced"),
    ("ardent", "advanced"),
    ("articulate", "advanced"),
    ("ascertain", "advanced"),
    ("assuage", "advanced"),
    ("astute", "advanced"),
    ("atrophy", "advanced"),
    ("attenuate", "advanced"),
    ("audacious", "advanced"),
    ("audacity", "advanced"),
    ("augment", "advanced"),
    ("austerity", "advanced"),
    ("authoritarian", "advanced"),
    ("autocratic", "advanced"),
    ("autonomy", "advanced"),
    ("avert", "advanced"),
    ("axiomatic", "advanced"),
    ("belligerent", "advanced"),
    ("benign", "advanced"),
    ("bequeath", "advanced"),
    ("bestow", "advanced"),
    ("bifurcate", "advanced"),
    ("bureaucratic", "advanced"),
    ("burgeon", "advanced"),
    ("bypass", "advanced"),
    ("calibrate", "advanced"),
    ("capitulate", "advanced"),
    ("capricious", "advanced"),
    ("catalyst", "advanced"),
    ("categorical", "advanced"),
    ("categorize", "advanced"),
    ("cease", "advanced"),
    ("circumscribe", "advanced"),
    ("circumspect", "advanced"),
    ("circumvent", "advanced"),
    ("clandestine", "advanced"),
    ("codify", "advanced"),
    ("cogitate", "advanced"),
    ("coincide", "advanced"),
    ("collapse", "advanced"),
    ("collate", "advanced"),
    ("compensate", "advanced"),
    ("compile", "advanced"),
    ("complement", "advanced"),
    ("comply", "advanced"),
    ("comprehend", "advanced"),
    ("comprehensive", "advanced"),
    ("concede", "advanced"),
    ("conciliatory", "advanced"),
    ("condense", "advanced"),
    ("confer", "advanced"),
    ("confiscate", "advanced"),
    ("conform", "advanced"),
    ("congenital", "advanced"),
    ("congregate", "advanced"),
    ("conjectural", "advanced"),
    ("conjecture", "advanced"),
    ("connotation", "advanced"),
    ("consequently", "advanced"),
    ("consolidate", "advanced"),
    ("consternation", "advanced"),
    ("constitute", "advanced"),
    ("constitutional", "advanced"),
    ("constrain", "advanced"),
    ("construe", "advanced"),
    ("contemplate", "advanced"),
    ("contend", "advanced"),
    ("contentious", "advanced"),
    ("contradict", "advanced"),
    ("contradictory", "advanced"),
    ("controversial", "advanced"),
    ("convene", "advanced"),
    ("converge", "advanced"),
    ("correlate", "advanced"),
    ("correspond", "advanced"),
    ("corroborate", "advanced"),
    ("corrode", "advanced"),
    ("counteract", "advanced"),
    ("counterfeit", "advanced"),
    ("crumble", "advanced"),
    ("cryptic", "advanced"),
    ("curb", "advanced"),
    ("cursory", "advanced"),
    ("curtail", "advanced"),
    ("cynicism", "advanced"),
    ("decay", "advanced"),
    ("decipher", "advanced"),
    ("decode", "advanced"),
    ("deduce", "advanced"),
    ("defer", "advanced"),
    ("deficit", "advanced"),
    ("deleterious", "advanced"),
    ("deliberate", "advanced"),
    ("delineate", "advanced"),
    ("demarcate", "advanced"),
    ("denotation", "advanced"),
    ("desist", "advanced"),
    ("deter", "advanced"),
    ("deteriorate", "advanced"),
    ("deviate", "advanced"),
    ("dichotomy", "advanced"),
    ("didactic", "advanced"),
    ("differentiate", "advanced"),
    ("digress", "advanced"),
    ("diminish", "advanced"),
    ("diplomacy", "advanced"),
    ("disband", "advanced"),
    ("disburse", "advanced"),
    ("discern", "advanced"),
    ("discerning", "advanced"),
    ("discriminate", "advanced"),
    ("disentangle", "advanced"),
    ("disintegrate", "advanced"),
    ("dislodge", "advanced"),
    ("disperse", "advanced"),
    ("displace", "advanced"),
    ("dissemble", "advanced"),
    ("disseminate", "advanced"),
    ("dissolve", "advanced"),
    ("dissuade", "advanced"),
    ("distinguish", "advanced"),
    ("distort", "advanced"),
    ("distribute", "advanced"),
    ("diverge", "advanced"),
    ("diversify", "advanced"),
    ("divisive", "advanced"),
    ("doctrinaire", "advanced"),
    ("dogmatic", "advanced"),
    ("dwindle", "advanced"),
    ("ebb", "advanced"),
    ("egalitarian", "advanced"),
    ("elaborate", "advanced"),
    ("elementary", "advanced"),
    ("eloquent", "advanced"),
    ("elucidate", "advanced"),
    ("elude", "advanced"),
    ("embargo", "advanced"),
    ("embellish", "advanced"),
    ("emblematic", "advanced"),
    ("empathy", "advanced"),
    ("empirical", "advanced"),
    ("emulate", "advanced"),
    ("encode", "advanced"),
    ("encompass", "advanced"),
    ("encrypt", "advanced"),
    ("endow", "advanced"),
    ("enigmatic", "advanced"),
    ("epitomize", "advanced"),
    ("equivocal", "advanced"),
    ("equivocate", "advanced"),
    ("erode", "advanced"),
    ("erudite", "advanced"),
    ("escalate", "advanced"),
    ("eschew", "advanced"),
    ("esoteric", "advanced"),
    ("estrange", "advanced"),
    ("evade", "advanced"),
    ("exacerbate", "advanced"),
    ("exaggerate", "advanced"),
    ("exasperation", "advanced"),
    ("executive", "advanced"),
    ("exemplary", "advanced"),
    ("exemplify", "advanced"),
    ("exhaustive", "advanced"),
    ("expand", "advanced"),
    ("expound", "advanced"),
    ("expropriate", "advanced"),
    ("extrapolate", "advanced"),
    ("extricate", "advanced"),
    ("extrinsic", "advanced"),
    ("fabricate", "advanced"),
    ("facilitate", "advanced"),
    ("falsify", "advanced"),
    ("fervent", "advanced"),
    ("flourish", "advanced"),
    ("forestall", "advanced"),
    ("forfeit", "advanced"),
    ("forgo", "advanced"),
    ("fundamental", "advanced"),
    ("furthermore", "advanced"),
    ("galvanize", "advanced"),
    ("genetic", "advanced"),
    ("grant", "advanced"),
    ("gregarious", "advanced"),
    ("henceforth", "advanced"),
    ("hereditary", "advanced"),
    ("heterodox", "advanced"),
    ("hierarchical", "advanced"),
    ("hinder", "advanced"),
    ("hoard", "advanced"),
    ("homogenize", "advanced"),
    ("hypothesis", "advanced"),
    ("hypothetical", "advanced"),
    ("ideological", "advanced"),
    ("idiosyncratic", "advanced"),
    ("impede", "advanced"),
    ("impertinent", "advanced"),
    ("implication", "advanced"),
    ("inadvertently", "advanced"),
    ("incite", "advanced"),
    ("indemnify", "advanced"),
    ("indifferent", "advanced"),
    ("indignation", "advanced"),
    ("infer", "advanced"),
    ("inflation", "advanced"),
    ("inherent", "advanced"),
    ("inherently", "advanced"),
    ("inhibit", "advanced"),
    ("innate", "advanced"),
    ("innocuous", "advanced"),
    ("inscrutable", "advanced"),
    ("insidious", "advanced"),
    ("instigate", "advanced"),
    ("insulate", "advanced"),
    ("intangible", "advanced"),
    ("integrate", "advanced"),
    ("intensify", "advanced"),
    ("interpolate", "advanced"),
    ("interpret", "advanced"),
    ("intrinsic", "advanced"),
    ("intuit", "advanced"),
    ("invalidate", "advanced"),
    ("isolate", "advanced"),
    ("judicial", "advanced"),
    ("judicious", "advanced"),
    ("jurisdiction", "advanced"),
    ("jurisdictional", "advanced"),
    ("juxtapose", "advanced"),
    ("laconic", "advanced"),
    ("languid", "advanced"),
    ("languish", "advanced"),
    ("legislation", "advanced"),
    ("legislative", "advanced"),
    ("lethargic", "advanced"),
    ("libertarian", "advanced"),
    ("listless", "advanced"),
    ("litigation", "advanced"),
    ("loquacious", "advanced"),
    ("malicious", "advanced"),
    ("mediate", "advanced"),
    ("mediation", "advanced"),
    ("mercurial", "advanced"),
    ("merge", "advanced"),
    ("meritocratic", "advanced"),
    ("misconstrue", "advanced"),
    ("misinterpret", "advanced"),
    ("misrepresent", "advanced"),
    ("mitigate", "advanced"),
    ("mobilize", "advanced"),
    ("mollify", "advanced"),
    ("moreover", "advanced"),
    ("muster", "advanced"),
    ("negotiation", "advanced"),
    ("neutralize", "advanced"),
    ("nevertheless", "advanced"),
    ("nonetheless", "advanced"),
    ("notwithstanding", "advanced"),
    ("nuance", "advanced"),
    ("nullify", "advanced"),
    ("obfuscate", "advanced"),
    ("obsequious", "advanced"),
    ("obstinate", "advanced"),
    ("obstruct", "advanced"),
    ("orthodox", "advanced"),
    ("ostensibly", "advanced"),
    ("ostracize", "advanced"),
    ("overrule", "advanced"),
    ("overturn", "advanced"),
    ("pacify", "advanced"),
    ("paradigm", "advanced"),
    ("paradoxical", "advanced"),
    ("parallel", "advanced"),
    ("paraphrase", "advanced"),
    ("peculiar", "advanced"),
    ("pedantic", "advanced"),
    ("peremptory", "advanced"),
    ("perfunctory", "advanced"),
    ("pernicious", "advanced"),
    ("perpetuate", "advanced"),
    ("perspicacious", "advanced"),
    ("phenomenon", "advanced"),
    ("phlegmatic", "advanced"),
    ("placate", "advanced"),
    ("plagiarize", "advanced"),
    ("plausible", "advanced"),
    ("polarize", "advanced"),
    ("polarizing", "advanced"),
    ("postulate", "advanced"),
    ("pragmatic", "advanced"),
    ("pragmatism", "advanced"),
    ("precedent", "advanced"),
    ("preclude", "advanced"),
    ("presume", "advanced"),
    ("presumptuous", "advanced"),
    ("prevaricate", "advanced"),
    ("profound", "advanced"),
    ("proliferate", "advanced"),
    ("prolix", "advanced"),
    ("propagate", "advanced"),
    ("prosper", "advanced"),
    ("prototypical", "advanced"),
    ("provoke", "advanced"),
    ("prudent", "advanced"),
    ("quantify", "advanced"),
    ("quarantine", "advanced"),
    ("quintessential", "advanced"),
    ("rally", "advanced"),
    ("ramification", "advanced"),
    ("ration", "advanced"),
    ("rebut", "advanced"),
    ("recession", "advanced"),
    ("reconcile", "advanced"),
    ("redundant", "advanced"),
    ("refrain", "advanced"),
    ("refute", "advanced"),
    ("reimburse", "advanced"),
    ("relent", "advanced"),
    ("relinquish", "advanced"),
    ("remit", "advanced"),
    ("renounce", "advanced"),
    ("repeal", "advanced"),
    ("repercussion", "advanced"),
    ("replicate", "advanced"),
    ("rescind", "advanced"),
    ("resemble", "advanced"),
    ("resign", "advanced"),
    ("resilience", "advanced"),
    ("restrain", "advanced"),
    ("retract", "advanced"),
    ("revoke", "advanced"),
    ("robust", "advanced"),
    ("rudimentary", "advanced"),
    ("ruminate", "advanced"),
    ("sagacious", "advanced"),
    ("salubrious", "advanced"),
    ("sanction", "advanced"),
    ("schismatic", "advanced"),
    ("scholarly", "advanced"),
    ("scrutinize", "advanced"),
    ("segregate", "advanced"),
    ("sequester", "advanced"),
    ("shrewd", "advanced"),
    ("simulate", "advanced"),
    ("skepticism", "advanced"),
    ("soothe", "advanced"),
    ("sovereign", "advanced"),
    ("sovereignty", "advanced"),
    ("speculative", "advanced"),
    ("sponsor", "advanced"),
    ("stagnate", "advanced"),
    ("standardize", "advanced"),
    ("statutory", "advanced"),
    ("stockpile", "advanced"),
    ("stoic", "advanced"),
    ("stratify", "advanced"),
    ("subdivide", "advanced"),
    ("submit", "advanced"),
    ("subsequently", "advanced"),
    ("subside", "advanced"),
    ("subsidize", "advanced"),
    ("subsidy", "advanced"),
    ("substantiate", "advanced"),
    ("succinct", "advanced"),
    ("summarize", "advanced"),
    ("superficial", "advanced"),
    ("supersede", "advanced"),
    ("supplant", "advanced"),
    ("supplement", "advanced"),
    ("surmise", "advanced"),
    ("surplus", "advanced"),
    ("surrender", "advanced"),
    ("surreptitious", "advanced"),
    ("sycophantic", "advanced"),
    ("systematize", "advanced"),
    ("taciturn", "advanced"),
    ("tariff", "advanced"),
    ("tautological", "advanced"),
    ("temerity", "advanced"),
    ("tenacious", "advanced"),
    ("terminate", "advanced"),
    ("terse", "advanced"),
    ("theoretical", "advanced"),
    ("thereby", "advanced"),
    ("thrive", "advanced"),
    ("thwart", "advanced"),
    ("torpid", "advanced"),
    ("totalitarian", "advanced"),
    ("transcribe", "advanced"),
    ("translate", "advanced"),
    ("trepidation", "advanced"),
    ("unambiguous", "advanced"),
    ("undermine", "advanced"),
    ("unequivocal", "advanced"),
    ("unravel", "advanced"),
    ("untangle", "advanced"),
    ("utilitarian", "advanced"),
    ("vacillate", "advanced"),
    ("verbose", "advanced"),
    ("vexation", "advanced"),
    ("vigilant", "advanced"),
    ("vigorous", "advanced"),
    ("vindictive", "advanced"),
    ("volatile", "advanced"),
    ("wane", "advanced"),
    ("whereas", "advanced"),
    ("whereby", "advanced"),
    ("yield", "advanced"),
    ("zealous", "advanced"),
    ("adult", "beginner"),
    ("afraid", "beginner"),
    ("airplane", "beginner"),
    ("answer", "beginner"),
    ("apple", "beginner"),
    ("arm", "beginner"),
    ("arrive", "beginner"),
    ("ask", "beginner"),
    ("autumn", "beginner"),
    ("baby", "beginner"),
    ("back", "beginner"),
    ("bad", "beginner"),
    ("banana", "beginner"),
    ("bank", "beginner"),
    ("bathroom", "beginner"),
    ("begin", "beginner"),
    ("bicycle", "beginner"),
    ("birthday", "beginner"),
    ("book", "beginner"),
    ("borrow", "beginner"),
    ("boss", "beginner"),
    ("brave", "beginner"),
    ("bread", "beginner"),
    ("break", "beginner"),
    ("bright", "beginner"),
    ("brush", "beginner"),
    ("build", "beginner"),
    ("butter", "beginner"),
    ("car", "beginner"),
    ("careful", "beginner"),
    ("carrot", "beginner"),
    ("carry", "beginner"),
    ("change", "beginner"),
    ("chest", "beginner"),
    ("chicken", "beginner"),
    ("child", "beginner"),
    ("choose", "beginner"),
    ("clean", "beginner"),
    ("coffee", "beginner"),
    ("computer", "beginner"),
    ("continue", "beginner"),
    ("count", "beginner"),
    ("customer", "beginner"),
    ("different", "beginner"),
    ("difficult", "beginner"),
    ("doubt", "beginner"),
    ("drink", "beginner"),
    ("drive", "beginner"),
    ("early", "beginner"),
    ("earth", "beginner"),
    ("easy", "beginner"),
    ("egg", "beginner"),
    ("empty", "beginner"),
    ("evening", "beginner"),
    ("exercise", "beginner"),
    ("expensive", "beginner"),
    ("explore", "beginner"),
    ("face", "beginner"),
    ("factory", "beginner"),
    ("far", "beginner"),
    ("favorite", "beginner"),
    ("fill", "beginner"),
    ("find", "beginner"),
    ("finish", "beginner"),
    ("fly", "beginner"),
    ("forget", "beginner"),
    ("friend", "beginner"),
    ("full", "beginner"),
    ("grade", "beginner"),
    ("grandfather", "beginner"),
    ("grandmother", "beginner"),
    ("guide", "beginner"),
    ("hand", "beginner"),
    ("happy", "beginner"),
    ("hard", "beginner"),
    ("hat", "beginner"),
    ("head", "beginner"),
    ("holiday", "beginner"),
    ("horse", "beginner"),
    ("hungry", "beginner"),
    ("insect", "beginner"),
    ("invite", "beginner"),
    ("island", "beginner"),
    ("jump", "beginner"),
    ("key", "beginner"),
    ("lamp", "beginner"),
    ("later", "beginner"),
    ("laugh", "beginner"),
    ("lead", "beginner"),
    ("leg", "beginner"),
    ("library", "beginner"),
    ("look", "beginner"),
    ("meat", "beginner"),
    ("meet", "beginner"),
    ("midnight", "beginner"),
    ("milk", "beginner"),
    ("mix", "beginner"),
    ("money", "beginner"),
    ("monkey", "beginner"),
    ("moon", "beginner"),
    ("mountain", "beginner"),
    ("music", "beginner"),
    ("narrow", "beginner"),
    ("neck", "beginner"),
    ("neighbor", "beginner"),
    ("noon", "beginner"),
    ("normal", "beginner"),
    ("number", "beginner"),
    ("ocean", "beginner"),
    ("office", "beginner"),
    ("often", "beginner"),
    ("open", "beginner"),
    ("own", "beginner"),
    ("page", "beginner"),
    ("paint", "beginner"),
    ("park", "beginner"),
    ("pass", "beginner"),
    ("passport", "beginner"),
    ("phone", "beginner"),
    ("pig", "beginner"),
    ("pillow", "beginner"),
    ("pizza", "beginner"),
    ("plan", "beginner"),
    ("plate", "beginner"),
    ("play", "beginner"),
    ("polite", "beginner"),
    ("poor", "beginner"),
    ("popular", "beginner"),
    ("practice", "beginner"),
    ("pull", "beginner"),
    ("push", "beginner"),
    ("quiet", "beginner"),
    ("rabbit", "beginner"),
    ("red", "beginner"),
    ("relax", "beginner"),
    ("repeat", "beginner"),
    ("rest", "beginner"),
    ("return", "beginner"),
    ("ring", "beginner"),
    ("rude", "beginner"),
    ("run", "beginner"),
    ("sad", "beginner"),
    ("safe", "beginner"),
    ("salt", "beginner"),
    ("same", "beginner"),
    ("school", "beginner"),
    ("see", "beginner"),
    ("sell", "beginner"),
    ("sheep", "beginner"),
    ("ship", "beginner"),
    ("shop", "beginner"),
    ("sing", "beginner"),
    ("skin", "beginner"),
    ("skirt", "beginner"),
    ("small", "beginner"),
    ("snow", "beginner"),
    ("soft", "beginner"),
    ("sometimes", "beginner"),
    ("soup", "beginner"),
    ("spring", "beginner"),
    ("stomach", "beginner"),
    ("strange", "beginner"),
    ("stranger", "beginner"),
    ("street", "beginner"),
    ("strong", "beginner"),
    ("suitcase", "beginner"),
    ("summer", "beginner"),
    ("sun", "beginner"),
    ("talk", "beginner"),
    ("tall", "beginner"),
    ("teenager", "beginner"),
    ("test", "beginner"),
    ("thick", "beginner"),
    ("thin", "beginner"),
    ("throw", "beginner"),
    ("tiger", "beginner"),
    ("time", "beginner"),
    ("tired", "beginner"),
    ("tomorrow", "beginner"),
    ("tooth", "beginner"),
    ("touch", "beginner"),
    ("true", "beginner"),
    ("turn", "beginner"),
    ("visit", "beginner"),
    ("wall", "beginner"),
    ("want", "beginner"),
    ("wash", "beginner"),
    ("watch", "beginner"),
    ("weekend", "beginner"),
    ("wet", "beginner"),
    ("wide", "beginner"),
    ("window", "beginner"),
    ("woman", "beginner"),
    ("world", "beginner"),
    ("write", "beginner"),
    ("wrong", "beginner"),
    ("year", "beginner"),
    ("yellow", "beginner"),
    ("ability", "intermediate"),
    ("acceptance", "intermediate"),
    ("achieve", "intermediate"),
    ("ambition", "intermediate"),
    ("analysis", "intermediate"),
    ("appropriate", "intermediate"),
    ("approval", "intermediate"),
    ("argue", "intermediate"),
    ("argument", "intermediate"),
    ("asset", "intermediate"),
    ("assume", "intermediate"),
    ("authority", "intermediate"),
    ("available", "intermediate"),
    ("award", "intermediate"),
    ("behavior", "intermediate"),
    ("benefit", "intermediate"),
    ("broadcast", "intermediate"),
    ("budget", "intermediate"),
    ("campaign", "intermediate"),
    ("candidate", "intermediate"),
    ("career", "intermediate"),
    ("cause", "intermediate"),
    ("census", "intermediate"),
    ("channel", "intermediate"),
    ("characteristic", "intermediate"),
    ("circumstance", "intermediate"),
    ("claim", "intermediate"),
    ("commerce", "intermediate"),
    ("committee", "intermediate"),
    ("compassion", "intermediate"),
    ("competition", "intermediate"),
    ("compliment", "intermediate"),
    ("compromise", "intermediate"),
    ("concerned", "intermediate"),
    ("confidence", "intermediate"),
    ("context", "intermediate"),
    ("control", "intermediate"),
    ("conversation", "intermediate"),
    ("cooperation", "intermediate"),
    ("corporation", "intermediate"),
    ("courage", "intermediate"),
    ("critic", "intermediate"),
    ("current", "intermediate"),
    ("debate", "intermediate"),
    ("debt", "intermediate"),
    ("decision", "intermediate"),
    ("definition", "intermediate"),
    ("demonstration", "intermediate"),
    ("describe", "intermediate"),
    ("description", "intermediate"),
    ("determination", "intermediate"),
    ("determined", "intermediate"),
    ("develop", "intermediate"),
    ("development", "intermediate"),
    ("disagreement", "intermediate"),
    ("discovery", "intermediate"),
    ("discuss", "intermediate"),
    ("discussion", "intermediate"),
    ("duty", "intermediate"),
    ("economy", "intermediate"),
    ("edition", "intermediate"),
    ("editor", "intermediate"),
    ("effect", "intermediate"),
    ("element", "intermediate"),
    ("emotion", "intermediate"),
    ("enterprise", "intermediate"),
    ("equality", "intermediate"),
    ("essential", "intermediate"),
    ("estimate", "intermediate"),
    ("ethic", "intermediate"),
    ("event", "intermediate"),
    ("excuse", "intermediate"),
    ("exhausted", "intermediate"),
    ("explanation", "intermediate"),
    ("faith", "intermediate"),
    ("feature", "intermediate"),
    ("feeling", "intermediate"),
    ("festival", "intermediate"),
    ("general", "intermediate"),
    ("generation", "intermediate"),
    ("generosity", "intermediate"),
    ("government", "intermediate"),
    ("gradual", "intermediate"),
    ("gratitude", "intermediate"),
    ("growth", "intermediate"),
    ("habit", "intermediate"),
    ("headline", "intermediate"),
    ("heritage", "intermediate"),
    ("however", "intermediate"),
    ("immediate", "intermediate"),
    ("immigrant", "intermediate"),
    ("impression", "intermediate"),
    ("improve", "intermediate"),
    ("inclusion", "intermediate"),
    ("influence", "intermediate"),
    ("information", "intermediate"),
    ("ingredient", "intermediate"),
    ("inspiration", "intermediate"),
    ("institution", "intermediate"),
    ("instruction", "intermediate"),
    ("intellect", "intermediate"),
    ("involve", "intermediate"),
    ("journalist", "intermediate"),
    ("justice", "intermediate"),
    ("kindness", "intermediate"),
    ("knowledge", "intermediate"),
    ("lifestyle", "intermediate"),
    ("listener", "intermediate"),
    ("loan", "intermediate"),
    ("loss", "intermediate"),
    ("loyalty", "intermediate"),
    ("manager", "intermediate"),
    ("material", "intermediate"),
    ("measure", "intermediate"),
    ("minister", "intermediate"),
    ("obligation", "intermediate"),
    ("occasion", "intermediate"),
    ("official", "intermediate"),
    ("opportunity", "intermediate"),
    ("parliament", "intermediate"),
    ("participant", "intermediate"),
    ("particular", "intermediate"),
    ("partnership", "intermediate"),
    ("patience", "intermediate"),
    ("permanent", "intermediate"),
    ("personality", "intermediate"),
    ("presentation", "intermediate"),
    ("president", "intermediate"),
    ("prevent", "intermediate"),
    ("previous", "intermediate"),
    ("principle", "intermediate"),
    ("procedure", "intermediate"),
    ("produce", "intermediate"),
    ("profession", "intermediate"),
    ("profit", "intermediate"),
    ("provide", "intermediate"),
    ("province", "intermediate"),
    ("qualification", "intermediate"),
    ("quantity", "intermediate"),
    ("questionnaire", "intermediate"),
    ("rating", "intermediate"),
    ("reader", "intermediate"),
    ("reasoning", "intermediate"),
    ("recent", "intermediate"),
    ("reduce", "intermediate"),
    ("region", "intermediate"),
    ("regulation", "intermediate"),
    ("rejection", "intermediate"),
    ("relevant", "intermediate"),
    ("religion", "intermediate"),
    ("representative", "intermediate"),
    ("result", "intermediate"),
    ("review", "intermediate"),
    ("sample", "intermediate"),
    ("situation", "intermediate"),
    ("society", "intermediate"),
    ("solution", "intermediate"),
    ("soul", "intermediate"),
    ("source", "intermediate"),
    ("specific", "intermediate"),
    ("spirit", "intermediate"),
    ("statistic", "intermediate"),
    ("sufficient", "intermediate"),
    ("suggest", "intermediate"),
    ("suggestion", "intermediate"),
    ("summary", "intermediate"),
    ("sympathy", "intermediate"),
    ("talent", "intermediate"),
    ("technique", "intermediate"),
    ("territory", "intermediate"),
    ("tolerance", "intermediate"),
    ("trade", "intermediate"),
    ("training", "intermediate"),
    ("transaction", "intermediate"),
    ("unlikely", "intermediate"),
    ("value", "intermediate"),
    ("viewpoint", "intermediate"),
    ("virtue", "intermediate"),
    ("volunteer", "intermediate"),
    ("vote", "intermediate"),
]
assert len(REMAINING_CONCEPTS) == 825, f"Beklenen 825, bulunan {len(REMAINING_CONCEPTS)}"


async def seed_remaining() -> dict:
    target_langs = [l for l in ALL_LANGS if l != SOURCE_LANG]
    print(
        f"\n=== source_lang={SOURCE_LANG} (SADECE KALAN {len(REMAINING_CONCEPTS)} "
        f"kavram, 11 hedef dilin hepsinde tamamlanmamis olanlar) x "
        f"{len(target_langs)} hedef dil ===\n"
    )
    stats = {"eklendi": 0, "zaten_vardi": 0, "bulunamadi": 0, "capa_cevirisi_basarisiz": 0}
    consecutive_anchor_failures = 0

    for anchor_word, level in REMAINING_CONCEPTS:
        source_word = await get_source_word(SOURCE_LANG, anchor_word)
        await asyncio.sleep(REQUEST_DELAY_SECONDS)
        if not source_word:
            stats["capa_cevirisi_basarisiz"] += 1
            consecutive_anchor_failures += 1
            print(f"  [CAPA CEVIRISI YOK] {anchor_word}")
            if consecutive_anchor_failures >= ANCHOR_FAILURE_CIRCUIT_BREAKER:
                print(
                    f"\n  [DURDURULDU] {consecutive_anchor_failures} kavram art arda capa "
                    f"cevirisi bulamadi -- muhtemelen MyMemory API kota/rate-limit sorunu. "
                    f"Kalan kavramlar atlaniyor (hicbir sey uydurulmadi/yanlis yazilmadi -- "
                    f"sadece hic yazilmadi). Birkac saat ya da ertesi gun ayni komutla "
                    f"tekrar calistir, kaldigi yerden (zaten eklenenler atlanarak) guvenle "
                    f"devam eder.\n"
                )
                raise RateLimitSuspected(SOURCE_LANG)
            continue
        consecutive_anchor_failures = 0

        for target_lang in target_langs:
            outcome = await seed_target(SOURCE_LANG, source_word, level, target_lang)
            stats[outcome] += 1
            if outcome == "eklendi":
                print(f"  [EKLENDI] {source_word} ({SOURCE_LANG}->{target_lang}, {level})")
            await asyncio.sleep(REQUEST_DELAY_SECONDS)

    print(f"\n=== {SOURCE_LANG} (kalanlar) tamamlandi ===")
    print(stats)
    return stats


if __name__ == "__main__":
    try:
        asyncio.run(seed_remaining())
    except RateLimitSuspected:
        print(
            f"\n{SOURCE_LANG} (kalanlar) icin rate-limit suphesiyle erken durduruldu (yukaridaki "
            f"[DURDURULDU] mesajina bakin). Birkac saat ya da ertesi gun ayni komutla "
            f"tekrar calistir."
        )