"""
backend/seed_tr_remaining.py (v3 -- 24 Eylul 2026)

Bu dosya, tr havuzundaki veri kalitesi temizliginden (virgullu/coklu-anlam
kelimeler, buyuk harf/aksan sorunlari, kurtarilamaz coplukler -- toplam ~30
kayit) SONRA kalan GERCEK eksiklikleri kapatir. Onceki versiyonlardan farki:

  - source_word ARTIK BILINIYOR (DB'de zaten temiz halde duruyor), bu yuzden
    get_source_word() ile EN->TR capa cevirisi YENIDEN YAPILMIYOR. Bu, onceki
    surumdeki asil hatanin (her calistirmada MyMemory'den FARKLI bir ceviri
    donup ayni kavramin birden fazla kelime/harf varyantina bolunmesi --
    ornegin "bilgisayar"/"Bilgisayar", "para"/"Para") tekrarlanmasini
    engeller: artik SADECE eksik (kelime, hedef_dil) ciftleri icin
    seed_target() cagriliyor, source_word hic degismiyor.
  - Liste TUM 1322 kavram yerine, temizlik sonrasi SQL ile hesaplanan TAM
    469 eksik cift (250 farkli kelime) icin. word_exists() zaten var olani
    atlar, yani kesintiye ugrarsa guvenle tekrar calistirilabilir.

CALISTIRMA:
    cd backend
    venv\\Scripts\\activate      # Windows
    python seed_tr_remaining.py
"""

import asyncio

from seed_lang_core import (
    ANCHOR_FAILURE_CIRCUIT_BREAKER,
    REQUEST_DELAY_SECONDS,
    RateLimitSuspected,
    seed_target,
)

SOURCE_LANG = "tr"

# (tr_kelime, seviye, eksik_hedef_dil) -- 469 satir, temizlik sonrasi
# SQL ile hesaplandi (250 farkli kelime x degisen sayida eksik hedef).
REMAINING_PAIRS: list[tuple[str, str, str]] = [
    ("...nın/nin tam bir örneği timsali olmak; tam bir örnek oluşturmak", "advanced", "ko"),
    ("...nın/nin tam bir örneği timsali olmak; tam bir örnek oluşturmak", "advanced", "zh"),
    ("(farklı eşya/kişi) yanyana koymak/yerleştirmek; zıt şeyleri bir araya getirmek", "advanced", "ko"),
    ("(farklı eşya/kişi) yanyana koymak/yerleştirmek; zıt şeyleri bir araya getirmek", "advanced", "zh"),
    ("a/e karşı", "advanced", "ko"),
    ("a/e karşı", "advanced", "zh"),
    ("açar", "beginner", "de"),
    ("acil", "intermediate", "ko"),
    ("acil", "intermediate", "zh"),
    ("açıklama", "intermediate", "it"),
    ("açıklamak", "advanced", "ko"),
    ("açıklamak", "advanced", "zh"),
    ("açmak", "advanced", "ar"),
    ("açmak", "advanced", "it"),
    ("açmak", "advanced", "ja"),
    ("açmak", "advanced", "ko"),
    ("açmak", "advanced", "pt"),
    ("açmak", "advanced", "ru"),
    ("açmak", "advanced", "zh"),
    ("ad", "beginner", "ko"),
    ("ad", "beginner", "zh"),
    ("ada", "beginner", "de"),
    ("ada", "beginner", "es"),
    ("akla yatkın", "advanced", "ko"),
    ("akla yatkın", "advanced", "zh"),
    ("akşam", "beginner", "ko"),
    ("akşam", "beginner", "zh"),
    ("akşam yemeği", "beginner", "ko"),
    ("akşam yemeği", "beginner", "zh"),
    ("alt", "beginner", "ko"),
    ("alt", "beginner", "pt"),
    ("amalgamat", "advanced", "de"),
    ("ambargo", "advanced", "ko"),
    ("ambargo", "advanced", "zh"),
    ("Ambivalenz", "advanced", "de"),
    ("analiz etmek", "intermediate", "ko"),
    ("analiz etmek", "intermediate", "zh"),
    ("ancak", "intermediate", "ko"),
    ("ancak", "intermediate", "zh"),
    ("anlam/sonuç/mana çıkarmak", "advanced", "ko"),
    ("anlam/sonuç/mana çıkarmak", "advanced", "zh"),
    ("anormallik", "advanced", "ko"),
    ("anormallik", "advanced", "zh"),
    ("aracılık", "advanced", "ko"),
    ("aracılık", "advanced", "zh"),
    ("argüman", "intermediate", "ar"),
    ("art(ır)mak", "intermediate", "ko"),
    ("art(ır)mak", "intermediate", "zh"),
    ("artık", "advanced", "ar"),
    ("artık", "advanced", "ja"),
    ("artık", "advanced", "ko"),
    ("artık", "advanced", "pt"),
    ("artık", "advanced", "ru"),
    ("artık", "advanced", "zh"),
    ("aslında", "advanced", "ko"),
    ("aslında", "advanced", "zh"),
    ("ay; yılın ayları", "beginner", "ko"),
    ("ay; yılın ayları", "beginner", "zh"),
    ("ayırmak", "advanced", "ja"),
    ("ayrılık", "advanced", "ko"),
    ("ayrılık", "advanced", "zh"),
    ("ayrıntı içermeyen", "intermediate", "ko"),
    ("ayrıntı içermeyen", "intermediate", "zh"),
    ("azaltmak", "intermediate", "ko"),
    ("azaltmak", "intermediate", "zh"),
    ("azar azar", "intermediate", "ko"),
    ("azar azar", "intermediate", "zh"),
    ("bağlı kalmak", "advanced", "fr"),
    ("başarmak", "intermediate", "ko"),
    ("başarmak", "intermediate", "zh"),
    ("beklenmedik/yan sonuç", "advanced", "ko"),
    ("beklenmedik/yan sonuç", "advanced", "zh"),
    ("belli", "intermediate", "ko"),
    ("belli", "intermediate", "zh"),
    ("bildik", "intermediate", "ko"),
    ("bildik", "intermediate", "zh"),
    ("bilgi", "intermediate", "ru"),
    ("bir kaç", "intermediate", "ko"),
    ("bir kaç", "intermediate", "zh"),
    ("bir şeyin farkında olmak", "intermediate", "ko"),
    ("bir şeyin farkında olmak", "intermediate", "zh"),
    ("bir sorunu hakem aracılığı ile çözme", "advanced", "ko"),
    ("bir sorunu hakem aracılığı ile çözme", "advanced", "zh"),
    ("biriktirmek.", "advanced", "it"),
    ("bölge", "intermediate", "ru"),
    ("böylece", "advanced", "ko"),
    ("böylece", "advanced", "zh"),
    ("bul", "beginner", "es"),
    ("bütçe", "intermediate", "ru"),
    ("bütçe açığı", "advanced", "ko"),
    ("bütçe açığı", "advanced", "zh"),
    ("bütün", "intermediate", "ko"),
    ("bütün", "intermediate", "zh"),
    ("cadde", "beginner", "ko"),
    ("cadde", "beginner", "zh"),
    ("çağrışım", "advanced", "ko"),
    ("çağrışım", "advanced", "zh"),
    ("çalışmak", "beginner", "ko"),
    ("çalışmak", "beginner", "zh"),
    ("çalkalamak", "advanced", "fr"),
    ("çarşı", "beginner", "ko"),
    ("çarşı", "beginner", "zh"),
    ("çelişki", "advanced", "ko"),
    ("çelişki", "advanced", "zh"),
    ("çevre", "intermediate", "ko"),
    ("çevre", "intermediate", "zh"),
    ("çok anlamlı", "advanced", "ko"),
    ("çok anlamlı", "advanced", "zh"),
    ("çok büyük", "advanced", "ko"),
    ("çok büyük", "advanced", "zh"),
    ("çok genç çocuk", "beginner", "ko"),
    ("çok genç çocuk", "beginner", "zh"),
    ("çok yorgun", "intermediate", "ko"),
    ("çok yorgun", "intermediate", "zh"),
    ("daha sonra", "advanced", "ko"),
    ("daha sonra", "advanced", "zh"),
    ("dahası", "advanced", "ko"),
    ("dahası", "advanced", "zh"),
    ("dava", "advanced", "ko"),
    ("dava", "advanced", "zh"),
    ("dede", "beginner", "de"),
    ("değerini/önemini belirlemek", "intermediate", "ko"),
    ("değerini/önemini belirlemek", "intermediate", "zh"),
    ("Değerlendirme", "intermediate", "fr"),
    ("değerlendirmek", "intermediate", "ko"),
    ("değerlendirmek", "intermediate", "zh"),
    ("Derleme", "intermediate", "ar"),
    ("Diğerkâm", "advanced", "ar"),
    ("diğerkâmlık", "advanced", "ko"),
    ("din", "intermediate", "ar"),
    ("diplomasi", "advanced", "ko"),
    ("diplomasi", "advanced", "zh"),
    ("doğrulamak", "advanced", "ko"),
    ("doğrulamak", "advanced", "zh"),
    ("dükkân", "beginner", "ko"),
    ("dükkân", "beginner", "zh"),
    ("Duvar", "beginner", "fr"),
    ("duyarsızlık", "advanced", "ko"),
    ("duyarsızlık", "advanced", "zh"),
    ("duygu", "intermediate", "de"),
    ("düz anlam", "advanced", "ko"),
    ("düz anlam", "advanced", "zh"),
    ("düzen", "intermediate", "ko"),
    ("düzen", "intermediate", "zh"),
    ("egemenlik", "advanced", "ko"),
    ("egemenlik", "advanced", "zh"),
    ("ekonomi", "intermediate", "ko"),
    ("ekonomi", "intermediate", "zh"),
    ("ekonomide durgunluk/gerileme", "advanced", "ko"),
    ("ekonomide durgunluk/gerileme", "advanced", "zh"),
    ("empati", "advanced", "ko"),
    ("empati", "advanced", "zh"),
    ("endişeli", "intermediate", "ko"),
    ("endişeli", "intermediate", "zh"),
    ("enine boyuna düşünmek", "intermediate", "ko"),
    ("enine boyuna düşünmek", "intermediate", "zh"),
    ("erkek çocuk", "beginner", "ko"),
    ("erkek çocuk", "beginner", "zh"),
    ("erken", "beginner", "de"),
    ("et", "beginner", "de"),
    ("etik", "intermediate", "es"),
    ("etraflı", "advanced", "ko"),
    ("etraflı", "advanced", "zh"),
    ("farketmek", "advanced", "ko"),
    ("farketmek", "advanced", "zh"),
    ("farzetmek", "intermediate", "ko"),
    ("farzetmek", "intermediate", "zh"),
    ("Fazilet", "intermediate", "de"),
    ("fazlalık", "advanced", "ko"),
    ("fazlalık", "advanced", "zh"),
    ("fikir ve hislerini kelimelerle anlatabilen", "advanced", "ko"),
    ("fikir ve hislerini kelimelerle anlatabilen", "advanced", "zh"),
    ("gelişmek", "intermediate", "ko"),
    ("gelişmek", "intermediate", "zh"),
    ("genç çocuk", "beginner", "ko"),
    ("genç çocuk", "beginner", "zh"),
    ("gerekçe", "intermediate", "ru"),
    ("gereksiz", "advanced", "ko"),
    ("gereksiz", "advanced", "zh"),
    ("gereksiz artış", "advanced", "ko"),
    ("gereksiz artış", "advanced", "zh"),
    ("göçmen", "intermediate", "ar"),
    ("gök", "beginner", "ko"),
    ("gök", "beginner", "zh"),
    ("gönüllü", "intermediate", "ar"),
    ("gönüllü", "intermediate", "de"),
    ("gönüllü", "intermediate", "es"),
    ("gönüllü", "intermediate", "fr"),
    ("gönüllü", "intermediate", "it"),
    ("gönüllü", "intermediate", "ja"),
    ("gönüllü", "intermediate", "ko"),
    ("gönüllü", "intermediate", "pt"),
    ("gönüllü", "intermediate", "ru"),
    ("gönüllü", "intermediate", "zh"),
    ("görünüşe bakılırsa; görünüş olarak; sözde olarak; zahirî bir şekilde", "advanced", "ko"),
    ("görünüşe bakılırsa; görünüş olarak; sözde olarak; zahirî bir şekilde", "advanced", "zh"),
    ("gümrük vergisi", "advanced", "ko"),
    ("gümrük vergisi", "advanced", "zh"),
    ("güzel konuşan", "advanced", "ko"),
    ("güzel konuşan", "advanced", "zh"),
    ("hafifletmek; azaltmak; dindirmek", "advanced", "ko"),
    ("hafifletmek; azaltmak; dindirmek", "advanced", "zh"),
    ("hal/düş kırıklığına uğramış; sükûtu hayale uğramış", "intermediate", "ko"),
    ("hal/düş kırıklığına uğramış; sükûtu hayale uğramış", "intermediate", "zh"),
    ("halbuki", "advanced", "ko"),
    ("halbuki", "advanced", "zh"),
    ("harekete geçirmek", "intermediate", "ko"),
    ("harekete geçirmek", "intermediate", "zh"),
    ("hastane", "beginner", "ko"),
    ("hastane", "beginner", "zh"),
    ("hekim", "beginner", "ko"),
    ("hekim", "beginner", "zh"),
    ("her ne kadar", "advanced", "zh"),
    ("her yerde hazır ve nazır", "advanced", "ko"),
    ("her yerde hazır ve nazır", "advanced", "zh"),
    ("hesaba katmamak", "intermediate", "ko"),
    ("hesaba katmamak", "intermediate", "zh"),
    ("hesaplamak", "intermediate", "ko"),
    ("hesaplamak", "intermediate", "zh"),
    ("hoş olmayan", "beginner", "ko"),
    ("hoş olmayan", "beginner", "zh"),
    ("hükmetmek", "advanced", "es"),
    ("hükümet", "intermediate", "ko"),
    ("hükümet", "intermediate", "zh"),
    ("hüsrana uğramış", "intermediate", "ko"),
    ("hüsrana uğramış", "intermediate", "zh"),
    ("İçerme", "intermediate", "es"),
    ("içermek", "intermediate", "ko"),
    ("içermek", "intermediate", "zh"),
    ("içmek", "beginner", "ko"),
    ("içmek", "beginner", "zh"),
    ("iddia etmek", "intermediate", "ko"),
    ("iddia etmek", "intermediate", "zh"),
    ("ideolojik", "advanced", "ko"),
    ("ideolojik", "advanced", "zh"),
    ("ile ilgili", "intermediate", "ko"),
    ("ile ilgili", "intermediate", "zh"),
    ("İlham", "intermediate", "de"),
    ("ilkbahar", "beginner", "ko"),
    ("ilkbahar", "beginner", "zh"),
    ("ince ayrıntı", "advanced", "ko"),
    ("ince ayrıntı", "advanced", "zh"),
    ("iyice incelemek", "advanced", "ko"),
    ("iyice incelemek", "advanced", "zh"),
    ("iyileş(tir)mek", "intermediate", "ko"),
    ("iyileş(tir)mek", "intermediate", "zh"),
    ("izah etmek", "advanced", "ko"),
    ("izah etmek", "advanced", "zh"),
    ("kabul", "intermediate", "ar"),
    ("kalıcı", "intermediate", "ko"),
    ("kalıcı", "intermediate", "zh"),
    ("kampanya", "intermediate", "ru"),
    ("kanal", "intermediate", "de"),
    ("kanıt", "intermediate", "ko"),
    ("kanıt", "intermediate", "zh"),
    ("kaplan", "beginner", "de"),
    ("kapsamak", "advanced", "ko"),
    ("kapsamak", "advanced", "zh"),
    ("kar", "beginner", "ko"),
    ("kar", "beginner", "zh"),
    ("kara", "beginner", "ko"),
    ("kara", "beginner", "zh"),
    ("karar", "intermediate", "ko"),
    ("karar", "intermediate", "zh"),
    ("kararlı", "intermediate", "ko"),
    ("kararlı", "intermediate", "zh"),
    ("kararsız", "intermediate", "ko"),
    ("kararsız", "intermediate", "zh"),
    ("kararsızlık", "advanced", "ko"),
    ("kararsızlık", "advanced", "zh"),
    ("karşılaştırma", "intermediate", "ko"),
    ("karşılaştırma", "intermediate", "zh"),
    ("katalizör", "advanced", "ko"),
    ("katalizör", "advanced", "zh"),
    ("kazara", "advanced", "ko"),
    ("kazara", "advanced", "zh"),
    ("kendi türünün yegane örneği; tipik numune; model", "advanced", "ko"),
    ("kendi türünün yegane örneği; tipik numune; model", "advanced", "zh"),
    ("kesin", "intermediate", "ko"),
    ("kesin", "intermediate", "zh"),
    ("ki bununla", "advanced", "ko"),
    ("ki bununla", "advanced", "zh"),
    ("kişi", "intermediate", "ko"),
    ("kişi", "intermediate", "zh"),
    ("kişisel", "intermediate", "ko"),
    ("kişisel", "intermediate", "zh"),
    ("kitap", "beginner", "ko"),
    ("kitap", "beginner", "zh"),
    ("kırmızı", "beginner", "ko"),
    ("kırmızı", "beginner", "zh"),
    ("Kısım", "beginner", "ru"),
    ("kız", "beginner", "ko"),
    ("kız", "beginner", "zh"),
    ("kolay farkedilmeyen/anlaşılmayan; aşikâr olmayan", "advanced", "ko"),
    ("kolay farkedilmeyen/anlaşılmayan; aşikâr olmayan", "advanced", "zh"),
    ("kontrol etmek", "intermediate", "ko"),
    ("kontrol etmek", "intermediate", "zh"),
    ("koşmak", "beginner", "ko"),
    ("koşmak", "beginner", "zh"),
    ("kötüleştirmek; olumsuz etkisini artırmak", "advanced", "ko"),
    ("kötüleştirmek; olumsuz etkisini artırmak", "advanced", "zh"),
    ("kötümserlik", "advanced", "ko"),
    ("kötümserlik", "advanced", "zh"),
    ("koyun", "beginner", "de"),
    ("kuramsal", "advanced", "ko"),
    ("kuramsal", "advanced", "zh"),
    ("kütüphane", "beginner", "ar"),
    ("masa", "beginner", "ko"),
    ("masa", "beginner", "zh"),
    ("materyal", "intermediate", "ar"),
    ("mevcut olan", "intermediate", "ko"),
    ("mevcut olan", "intermediate", "zh"),
    ("miktarı", "beginner", "ru"),
    ("modeli", "intermediate", "it"),
    ("muhtelif", "intermediate", "ko"),
    ("muhtelif", "intermediate", "zh"),
    ("muhtemel", "intermediate", "ko"),
    ("muhtemel", "intermediate", "zh"),
    ("muhtemel etki/sonuç", "advanced", "ko"),
    ("muhtemel etki/sonuç", "advanced", "zh"),
    ("mukayese etmek", "intermediate", "ko"),
    ("mukayese etmek", "intermediate", "zh"),
    ("mümkün", "intermediate", "ko"),
    ("mümkün", "intermediate", "zh"),
    ("mümkün kılmak", "advanced", "ko"),
    ("mümkün kılmak", "advanced", "zh"),
    ("müşteri", "beginner", "ar"),
    ("müzakere", "advanced", "ko"),
    ("müzakere", "advanced", "zh"),
    ("müzik", "beginner", "ko"),
    ("müzik", "beginner", "zh"),
    ("Nezaket", "intermediate", "de"),
    ("numara", "beginner", "ko"),
    ("numara", "beginner", "zh"),
    ("ödül", "intermediate", "de"),
    ("ödül", "intermediate", "fr"),
    ("ödül", "intermediate", "it"),
    ("ödül", "intermediate", "pt"),
    ("ödül", "intermediate", "zh"),
    ("okumak", "beginner", "ko"),
    ("okumak", "beginner", "zh"),
    ("olası olmayan", "intermediate", "ko"),
    ("olası olmayan", "intermediate", "zh"),
    ("oluşturmak", "advanced", "ko"),
    ("oluşturmak", "advanced", "zh"),
    ("önerme", "advanced", "ko"),
    ("önerme", "advanced", "zh"),
    ("önermek", "intermediate", "ko"),
    ("önermek", "intermediate", "zh"),
    ("önlemek", "intermediate", "ko"),
    ("önlemek", "intermediate", "zh"),
    ("onun için", "intermediate", "ko"),
    ("onun için", "intermediate", "zh"),
    ("örnek vermek", "advanced", "ko"),
    ("örnek vermek", "advanced", "zh"),
    ("otomobil", "beginner", "ko"),
    ("otomobil", "beginner", "zh"),
    ("oy", "intermediate", "de"),
    ("oy", "intermediate", "fr"),
    ("özen göstermeyen", "advanced", "ko"),
    ("özen göstermeyen", "advanced", "zh"),
    ("özerklik", "advanced", "ko"),
    ("özerklik", "advanced", "zh"),
    ("özet", "intermediate", "de"),
    ("özgecilik", "advanced", "ko"),
    ("özgecilik", "advanced", "zh"),
    ("paradoks", "advanced", "ko"),
    ("paradoks", "advanced", "zh"),
    ("park", "beginner", "ko"),
    ("park", "beginner", "zh"),
    ("Parlamento", "intermediate", "es"),
    ("Parlamento", "intermediate", "it"),
    ("patron", "beginner", "fr"),
    ("pencere", "beginner", "ko"),
    ("pencere", "beginner", "zh"),
    ("planlamak", "intermediate", "ko"),
    ("planlamak", "intermediate", "zh"),
    ("popüler", "beginner", "fr"),
    ("pratik", "advanced", "ko"),
    ("pratik", "advanced", "zh"),
    ("renk", "beginner", "ko"),
    ("renk", "beginner", "zh"),
    ("sadelik", "advanced", "ko"),
    ("sadelik", "advanced", "zh"),
    ("saptamak", "advanced", "ko"),
    ("saptamak", "advanced", "zh"),
    ("şaşırmış", "intermediate", "ko"),
    ("şaşırmış", "intermediate", "zh"),
    ("sat", "beginner", "de"),
    ("sat", "beginner", "fr"),
    ("sat", "beginner", "it"),
    ("sat", "beginner", "ja"),
    ("sat", "beginner", "ru"),
    ("sayfa", "beginner", "ar"),
    ("sebep", "intermediate", "ko"),
    ("sebep", "intermediate", "zh"),
    ("sempati", "intermediate", "de"),
    ("sempati", "intermediate", "es"),
    ("sempati", "intermediate", "it"),
    ("sempati", "intermediate", "ru"),
    ("seyretmek", "beginner", "ko"),
    ("seyretmek", "beginner", "zh"),
    ("sokak", "beginner", "de"),
    ("sonbahar", "beginner", "ko"),
    ("sonbahar", "beginner", "zh"),
    ("sonuç çıkarmak", "advanced", "ko"),
    ("sonuç çıkarmak", "advanced", "zh"),
    ("sonuç itibariyle", "advanced", "ko"),
    ("sonuç itibariyle", "advanced", "zh"),
    ("soyut", "advanced", "ko"),
    ("soyut", "advanced", "zh"),
    ("şu andan itibaren", "advanced", "ko"),
    ("şu andan itibaren", "advanced", "zh"),
    ("şüphecilik", "advanced", "ko"),
    ("şüphecilik", "advanced", "zh"),
    ("sürüm", "intermediate", "de"),
    ("tahmin etmek", "advanced", "ko"),
    ("tahmin etmek", "advanced", "zh"),
    ("tasvir etmek", "intermediate", "ko"),
    ("tasvir etmek", "intermediate", "zh"),
    ("tatmin olmuş", "intermediate", "ko"),
    ("tatmin olmuş", "intermediate", "zh"),
    ("tavşan", "beginner", "de"),
    ("teknik direktör", "intermediate", "fr"),
    ("telefon", "beginner", "ko"),
    ("telefon", "beginner", "zh"),
    ("titiz", "advanced", "ko"),
    ("titiz", "advanced", "zh"),
    ("toplam", "advanced", "ja"),
    ("tuhaf", "beginner", "de"),
    ("ürkütmek", "advanced", "ko"),
    ("ürkütmek", "advanced", "zh"),
    ("üstelik", "advanced", "ko"),
    ("üstelik", "advanced", "zh"),
    ("uygulama ve bilimsel deneye dayalı; deneysel", "advanced", "ko"),
    ("uygulama ve bilimsel deneye dayalı; deneysel", "advanced", "zh"),
    ("uygulamacılık", "advanced", "ko"),
    ("uygulamacılık", "advanced", "zh"),
    ("uyumak", "beginner", "ko"),
    ("uyumak", "beginner", "zh"),
    ("uzlaştırmak", "advanced", "ko"),
    ("uzlaştırmak", "advanced", "zh"),
    ("uzmanlık alanı", "intermediate", "fr"),
    ("Yabancılaşma", "advanced", "ar"),
    ("yalanlamak", "advanced", "ko"),
    ("yalanlamak", "advanced", "zh"),
    ("yankı", "advanced", "ko"),
    ("yankı", "advanced", "zh"),
    ("yapmak", "intermediate", "ko"),
    ("yapmak", "intermediate", "zh"),
    ("yaptırım", "advanced", "ko"),
    ("yaptırım", "advanced", "zh"),
    ("yardım", "advanced", "ko"),
    ("yardım", "advanced", "zh"),
    ("yasal yetki/selahiyet; yetki alanı", "advanced", "ko"),
    ("yasal yetki/selahiyet; yetki alanı", "advanced", "zh"),
    ("yasalar", "advanced", "ko"),
    ("yasalar", "advanced", "zh"),
    ("yeni", "intermediate", "ko"),
    ("yeni", "intermediate", "zh"),
    ("yine de", "advanced", "ko"),
    ("yine de", "advanced", "zh"),
    ("yıl", "beginner", "ko"),
    ("yıl", "beginner", "zh"),
    ("yıldız", "beginner", "ko"),
    ("yıldız", "beginner", "zh"),
    ("yürürlükten kaldırmak", "advanced", "ru"),
    ("zaman", "beginner", "ko"),
    ("zaman", "beginner", "zh"),
]

assert len(REMAINING_PAIRS) == 469, (
    f"Beklenmeyen satir sayisi: {len(REMAINING_PAIRS)}"
)


async def seed_remaining() -> dict:
    stats = {"eklendi": 0, "zaten_vardi": 0, "bulunamadi": 0}
    consecutive_not_found = 0

    for source_word, level, target_lang in REMAINING_PAIRS:
        outcome = await seed_target(SOURCE_LANG, source_word, level, target_lang)
        stats[outcome] += 1
        if outcome == "eklendi":
            print(f"  [EKLENDI] {source_word} ({SOURCE_LANG}->{target_lang}, {level})")
            consecutive_not_found = 0
        elif outcome == "bulunamadi":
            consecutive_not_found += 1
            if consecutive_not_found >= ANCHOR_FAILURE_CIRCUIT_BREAKER:
                raise RateLimitSuspected(SOURCE_LANG)
        else:
            consecutive_not_found = 0
        await asyncio.sleep(REQUEST_DELAY_SECONDS)

    return stats


if __name__ == "__main__":
    try:
        final_stats = asyncio.run(seed_remaining())
        print(f"\n=== {SOURCE_LANG} (kalanlar) tamamlandi ===")
        print(final_stats)
    except RateLimitSuspected:
        print(
            f"\n{SOURCE_LANG} icin rate-limit suphesiyle erken durduruldu. "
            f"Birkac saat ya da ertesi gun ayni komutla tekrar calistir, "
            f"kaldigi yerden (zaten eklenenler atlanarak) guvenle devam eder."
        )
