-- Migration: Sınav Hazırlık Alanı — YÖKDİL, IELTS, TOEFL soru bankaları (ilk seed,
-- her biri için 10 orijinal soru). §1.1 MVP'de sadece YDS vardı (024_exam_prep_
-- yds_seed.sql); bu migration ile question_count>0 olduğu için istemcide artık
-- "Yakında" değil, oynanabilir olarak görünecekler (bkz. exams.py::list_exam_types
-- — available = question_count > 0, ekstra kod değişikliği gerekmiyor).
--
-- İçerik kaynağı (023_exam_prep.sql'deki kararla aynı): telif riski nedeniyle
-- GERÇEK geçmiş sınav soruları KULLANILMIYOR — sınav formatına uygun orijinal
-- sorular. Sınav türüne göre kayıtlı vurgu:
--  - YÖKDİL: akademik/bilimsel kayıt (hypothesis, empirical, mitigate, vb.)
--  - IELTS:  genel akademik okuma kelime hazinesi (sustainable, versatile, vb.)
--  - TOEFL:  akademik ders/okuma kelime hazinesi (ubiquitous, discern, vb.)

INSERT INTO public.exam_questions (exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level)
VALUES
('yokdil',
 'Recent studies have shown a ------- increase in global temperatures over the past decade, prompting renewed concern among climate scientists.',
 '[{"id":"a","text":"substantial"},{"id":"b","text":"negligible"},{"id":"c","text":"temporary"},{"id":"d","text":"uncertain"}]',
 'a',
 '"İklim bilimcileri arasında yenilenen endişe" büyük/önemli bir artışı işaret eder; "substantial" (önemli ölçüde) doğru cevaptır.',
 '[{"word":"substantial","meaning":"önemli ölçüde, hatırı sayılır","example":"There has been a substantial improvement in air quality since the new regulations."}]',
 'medium'),

('yokdil',
 'Before conducting the experiment, the researchers formulated a clear ------- that could be tested through controlled observation.',
 '[{"id":"a","text":"hypothesis"},{"id":"b","text":"conclusion"},{"id":"c","text":"coincidence"},{"id":"d","text":"habit"}]',
 'a',
 'Deney yapılmadan önce, kontrollü gözlemle test edilebilecek bir şey bilimsel bir hipotezdir; "conclusion" (sonuç) deneyden SONRA gelir, "coincidence" ve "habit" bağlama uymaz.',
 '[{"word":"hypothesis","meaning":"hipotez, varsayım","example":"The hypothesis was later confirmed by a series of experiments."}]',
 'medium'),

('yokdil',
 'Unlike theoretical models, ------- research relies on direct observation and experimentation to reach conclusions.',
 '[{"id":"a","text":"empirical"},{"id":"b","text":"theoretical"},{"id":"c","text":"hypothetical"},{"id":"d","text":"abstract"}]',
 'a',
 'Doğrudan gözlem ve deneye dayanma görgül/deneysel (empirical) araştırmayı tanımlar; diğer seçenekler cümledeki karşıtlıkla veya anlamca uymaz.',
 '[{"word":"empirical","meaning":"görgül, deneye dayalı","example":"The theory was supported by strong empirical evidence."}]',
 'hard'),

('yokdil',
 'The sudden decline in bee populations is a ------- that has puzzled scientists for over a decade.',
 '[{"id":"a","text":"phenomenon"},{"id":"b","text":"opinion"},{"id":"c","text":"rumor"},{"id":"d","text":"exception"}]',
 'a',
 'Bilimsel açıdan gözlemlenen, açıklanması zor bir olay "phenomenon" (olgu) olarak adlandırılır.',
 '[{"word":"phenomenon","meaning":"olgu, fenomen","example":"Global warming is a phenomenon that affects the entire planet."}]',
 'easy'),

('yokdil',
 'Several studies have found that higher levels of education tend to ------- with better long-term health outcomes.',
 '[{"id":"a","text":"correlate"},{"id":"b","text":"contradict"},{"id":"c","text":"interfere"},{"id":"d","text":"compete"}]',
 'a',
 '"Correlate with" (ile ilişkili olmak) istatistiksel bir bağlantıyı ifade eder; diğer seçenekler bağlama uymaz.',
 '[{"word":"correlate","meaning":"ilişkilendirmek, bağlantılı olmak","example":"Income level often correlates with access to healthcare."}]',
 'medium'),

('yokdil',
 'The new policies were designed to ------- the negative effects of industrial pollution on nearby communities.',
 '[{"id":"a","text":"mitigate"},{"id":"b","text":"worsen"},{"id":"c","text":"ignore"},{"id":"d","text":"accelerate"}]',
 'a',
 'Olumsuz etkileri hafifletmek/azaltmak anlamındaki "mitigate" doğru cevaptır; diğerleri anlamca ters veya uyumsuzdur.',
 '[{"word":"mitigate","meaning":"hafifletmek, azaltmak","example":"Planting trees can help mitigate the effects of climate change."}]',
 'medium'),

('yokdil',
 'The committee published a ------- report covering every aspect of the university''s research output over the past five years.',
 '[{"id":"a","text":"comprehensive"},{"id":"b","text":"partial"},{"id":"c","text":"superficial"},{"id":"d","text":"brief"}]',
 'a',
 '"Her yönünü kapsayan" ifadesi kapsamlı (comprehensive) bir raporu tanımlar.',
 '[{"word":"comprehensive","meaning":"kapsamlı, geniş çaplı","example":"She wrote a comprehensive review of the existing literature."}]',
 'medium'),

('yokdil',
 'Given the current budget constraints, the proposed expansion project is simply not ------- at this time.',
 '[{"id":"a","text":"feasible"},{"id":"b","text":"mandatory"},{"id":"c","text":"popular"},{"id":"d","text":"profitable"}]',
 'a',
 'Bütçe kısıtlamaları nedeniyle projenin uygulanabilir olmaması ima ediliyor; "feasible" (uygulanabilir) olumsuzlanmış haliyle doğru cevaptır.',
 '[{"word":"feasible","meaning":"uygulanabilir, yapılabilir","example":"It is not economically feasible to build the plant in this location."}]',
 'hard'),

('yokdil',
 'The medication proved effective, although some patients reported ------- side effects such as nausea and dizziness.',
 '[{"id":"a","text":"adverse"},{"id":"b","text":"beneficial"},{"id":"c","text":"negligible"},{"id":"d","text":"desirable"}]',
 'a',
 'Bulantı ve baş dönmesi olumsuz/istenmeyen (adverse) yan etkilerdir.',
 '[{"word":"adverse","meaning":"olumsuz, ters, zararlı","example":"The drug can cause adverse reactions in a small percentage of patients."}]',
 'medium'),

('yokdil',
 'To solve the problem effectively, the researchers first needed to identify its ------- cause rather than simply treating the symptoms.',
 '[{"id":"a","text":"underlying"},{"id":"b","text":"obvious"},{"id":"c","text":"irrelevant"},{"id":"d","text":"temporary"}]',
 'a',
 '"Semptomları tedavi etmek yerine" ifadesiyle kurulan zıtlık, altta yatan/temel (underlying) nedeni bulma anlamını verir.',
 '[{"word":"underlying","meaning":"altta yatan, temel","example":"Stress is often the underlying cause of many health problems."}]',
 'medium'),

('ielts',
 'Access to clean water is ------- for maintaining public health, especially in densely populated urban areas.',
 '[{"id":"a","text":"crucial"},{"id":"b","text":"optional"},{"id":"c","text":"irrelevant"},{"id":"d","text":"occasional"}]',
 'a',
 'Halk sağlığının korunması için "vazgeçilmez/çok önemli" (crucial) olması bağlamla uyumludur.',
 '[{"word":"crucial","meaning":"çok önemli, hayati","example":"Early diagnosis is crucial for successful treatment."}]',
 'easy'),

('ielts',
 'The new software update is expected to significantly ------- the performance and speed of the application.',
 '[{"id":"a","text":"enhance"},{"id":"b","text":"reduce"},{"id":"c","text":"delay"},{"id":"d","text":"complicate"}]',
 'a',
 'Bir güncellemenin performansı "iyileştirmesi/artırması" (enhance) beklenir; diğer seçenekler olumlu beklentiyle çelişir.',
 '[{"word":"enhance","meaning":"geliştirmek, iyileştirmek","example":"Regular exercise can enhance both physical and mental well-being."}]',
 'easy'),

('ielts',
 'The city''s population is remarkably -------, with residents representing more than eighty different nationalities.',
 '[{"id":"a","text":"diverse"},{"id":"b","text":"uniform"},{"id":"c","text":"declining"},{"id":"d","text":"isolated"}]',
 'a',
 '"Seksenden fazla farklı milliyet" çeşitliliği (diverse) gösterir.',
 '[{"word":"diverse","meaning":"çeşitli, farklı","example":"The company values a diverse and inclusive workplace."}]',
 'medium'),

('ielts',
 'Environmental experts are urging governments to invest in ------- energy sources that will not deplete natural resources.',
 '[{"id":"a","text":"sustainable"},{"id":"b","text":"temporary"},{"id":"c","text":"expensive"},{"id":"d","text":"traditional"}]',
 'a',
 'Doğal kaynakları tüketmeyen enerji kaynakları "sürdürülebilir" (sustainable) olarak adlandırılır.',
 '[{"word":"sustainable","meaning":"sürdürülebilir","example":"The company shifted to more sustainable manufacturing practices."}]',
 'medium'),

('ielts',
 'Without proper maintenance, the old bridge continued to ------- until it was finally closed to traffic.',
 '[{"id":"a","text":"deteriorate"},{"id":"b","text":"improve"},{"id":"c","text":"expand"},{"id":"d","text":"stabilize"}]',
 'a',
 'Bakımsızlık sonucu köprünün "kötüleşmesi/bozulması" (deteriorate) beklenir, bu yüzden trafiğe kapatılmıştır.',
 '[{"word":"deteriorate","meaning":"kötüleşmek, bozulmak","example":"His health began to deteriorate rapidly after the accident."}]',
 'medium'),

('ielts',
 'Many customers ------- higher prices as a sign of better quality, even when this is not necessarily true.',
 '[{"id":"a","text":"perceive"},{"id":"b","text":"ignore"},{"id":"c","text":"reject"},{"id":"d","text":"calculate"}]',
 'a',
 'Yüksek fiyatları kalite göstergesi olarak "algılamak" (perceive) bağlama uygundur.',
 '[{"word":"perceive","meaning":"algılamak, öyle görmek","example":"She was perceived as a strong and confident leader."}]',
 'medium'),

('ielts',
 'Building the new railway line required a ------- amount of both time and financial investment.',
 '[{"id":"a","text":"considerable"},{"id":"b","text":"negligible"},{"id":"c","text":"fixed"},{"id":"d","text":"minimal"}]',
 'a',
 'Büyük bir demiryolu inşaatının "hatırı sayılır/önemli miktarda" (considerable) zaman ve yatırım gerektirmesi beklenir.',
 '[{"word":"considerable","meaning":"hatırı sayılır, önemli miktarda","example":"The project required considerable effort from the entire team."}]',
 'easy'),

('ielts',
 'Olive oil is a remarkably ------- ingredient, used in cooking, skincare, and even traditional medicine.',
 '[{"id":"a","text":"versatile"},{"id":"b","text":"rare"},{"id":"c","text":"expensive"},{"id":"d","text":"artificial"}]',
 'a',
 'Birçok farklı alanda kullanılabilmesi çok yönlü (versatile) olmasını gösterir.',
 '[{"word":"versatile","meaning":"çok yönlü, çok amaçlı","example":"She is a versatile actress who can play both comedic and dramatic roles."}]',
 'medium'),

('ielts',
 'English remains the ------- language of international business, despite the rise of other global languages.',
 '[{"id":"a","text":"predominant"},{"id":"b","text":"forbidden"},{"id":"c","text":"obsolete"},{"id":"d","text":"minor"}]',
 'a',
 '"Uluslararası iş dünyasında hâkim/baskın" dil olması "predominant" ile ifade edilir.',
 '[{"word":"predominant","meaning":"hâkim, baskın, en yaygın","example":"Rice is the predominant crop grown in this region."}]',
 'medium'),

('ielts',
 'Schools play an important role in helping to ------- creativity and independent thinking among young students.',
 '[{"id":"a","text":"foster"},{"id":"b","text":"suppress"},{"id":"c","text":"ignore"},{"id":"d","text":"postpone"}]',
 'a',
 'Okulların öğrencilerde yaratıcılığı "geliştirmesi/beslemesi" (foster) beklenen olumlu bir rol olduğu için doğru cevaptır.',
 '[{"word":"foster","meaning":"geliştirmek, beslemek, teşvik etmek","example":"The program aims to foster a love of reading in children."}]',
 'medium'),

('toefl',
 'In the field of aviation, safety is considered ------- , taking precedence over every other operational concern.',
 '[{"id":"a","text":"paramount"},{"id":"b","text":"irrelevant"},{"id":"c","text":"negotiable"},{"id":"d","text":"secondary"}]',
 'a',
 '"Her şeyin önünde gelmesi" en üstün öneme (paramount) sahip olduğunu gösterir.',
 '[{"word":"paramount","meaning":"en üstün, en önemli","example":"Customer safety is of paramount importance to the company."}]',
 'hard'),

('toefl',
 'Smartphones have become so ------- in modern society that it is difficult to imagine daily life without them.',
 '[{"id":"a","text":"ubiquitous"},{"id":"b","text":"rare"},{"id":"c","text":"forbidden"},{"id":"d","text":"outdated"}]',
 'a',
 '"Her yerde bulunan/yaygın" (ubiquitous) olması, günlük hayatta onsuz yaşamayı hayal etmenin zor olmasıyla örtüşür.',
 '[{"word":"ubiquitous","meaning":"her yerde bulunan, çok yaygın","example":"Plastic packaging has become ubiquitous in modern retail."}]',
 'hard'),

('toefl',
 'It can be difficult for beginners to ------- subtle differences between similar chemical compounds without specialized training.',
 '[{"id":"a","text":"discern"},{"id":"b","text":"create"},{"id":"c","text":"ignore"},{"id":"d","text":"exaggerate"}]',
 'a',
 'İnce farkları "ayırt etmek/fark etmek" (discern) anlamı, "özel eğitim olmadan zor olması" ile uyumludur.',
 '[{"word":"discern","meaning":"ayırt etmek, fark etmek","example":"It was hard to discern any real difference between the two proposals."}]',
 'hard'),

('toefl',
 'The professor asked a series of open-ended questions designed to ------- deeper discussion among the students.',
 '[{"id":"a","text":"elicit"},{"id":"b","text":"prevent"},{"id":"c","text":"discourage"},{"id":"d","text":"postpone"}]',
 'a',
 'Sorular öğrencilerden tartışma "çekmek/elde etmek" (elicit) amacıyla sorulur; diğer seçenekler amaçla çelişir.',
 '[{"word":"elicit","meaning":"ortaya çıkarmak, elde etmek","example":"The survey was designed to elicit honest feedback from employees."}]',
 'medium'),

('toefl',
 'Although the scientist''s daily lab routine may seem ------- to outsiders, it often leads to significant discoveries over time.',
 '[{"id":"a","text":"mundane"},{"id":"b","text":"extraordinary"},{"id":"c","text":"dangerous"},{"id":"d","text":"rewarding"}]',
 'a',
 '"Dışarıdan bakanlara sıradan görünse de" ifadesi, günlük ve sıradan (mundane) bir rutini tanımlar; zıtlık cümledeki "önemli keşiflere yol açması" ile kurulur.',
 '[{"word":"mundane","meaning":"sıradan, gündelik","example":"Most of the job involves fairly mundane administrative tasks."}]',
 'medium'),

('toefl',
 'The new evidence was strong enough to ------- the long-held theory that had dominated the field for decades.',
 '[{"id":"a","text":"refute"},{"id":"b","text":"support"},{"id":"c","text":"ignore"},{"id":"d","text":"summarize"}]',
 'a',
 'Yeni kanıtın eski teoriyi "çürütmesi" (refute) bağlamla uyumludur.',
 '[{"word":"refute","meaning":"çürütmek, yanlışlığını kanıtlamak","example":"Scientists were able to refute the earlier claims with new data."}]',
 'hard'),

('toefl',
 'Investors wanted to see ------- results before committing any further funding to the project.',
 '[{"id":"a","text":"tangible"},{"id":"b","text":"imaginary"},{"id":"c","text":"theoretical"},{"id":"d","text":"verbal"}]',
 'a',
 'Yatırımcıların soyut değil "somut" (tangible) sonuçlar görmek istemesi doğal bir beklentidir.',
 '[{"word":"tangible","meaning":"somut, elle tutulur","example":"The project has yet to produce any tangible benefits."}]',
 'medium'),

('toefl',
 'The company''s financial situation became increasingly ------- after losing its two biggest clients.',
 '[{"id":"a","text":"precarious"},{"id":"b","text":"stable"},{"id":"c","text":"profitable"},{"id":"d","text":"predictable"}]',
 'a',
 'En büyük iki müşterisini kaybetmesi şirketin durumunu "kırılgan/tehlikeli" (precarious) hale getirir.',
 '[{"word":"precarious","meaning":"kırılgan, tehlikeli, istikrarsız","example":"Many freelancers face a precarious income from month to month."}]',
 'hard'),

('toefl',
 'Obesity has become increasingly ------- in many developed countries over the past thirty years.',
 '[{"id":"a","text":"prevalent"},{"id":"b","text":"rare"},{"id":"c","text":"forbidden"},{"id":"d","text":"declining"}]',
 'a',
 '"Giderek artan" bir sorunun "yaygın" (prevalent) hale gelmesi bağlamla uyumludur.',
 '[{"word":"prevalent","meaning":"yaygın, hâkim","example":"This disease is particularly prevalent among older adults."}]',
 'medium'),

('toefl',
 'The young researcher was able to ------- her complex findings in a way that was easy for a general audience to understand.',
 '[{"id":"a","text":"articulate"},{"id":"b","text":"conceal"},{"id":"c","text":"exaggerate"},{"id":"d","text":"abandon"}]',
 'a',
 'Karmaşık bulguları anlaşılır şekilde "ifade etmek/dile getirmek" (articulate) bağlamla uyumludur.',
 '[{"word":"articulate","meaning":"açıkça ifade etmek, dile getirmek","example":"He struggled to articulate his feelings about the situation."}]',
 'medium');
