-- 030_grammar_reference_expansion.sql
--
-- Gramer Rehberi genisletmesi + sinav soru havuzu buyutmesi (kullanicinin
-- "sinav soru sayisi az, bunu artir" talebine ve daha once anlasilan Gramer
-- PDF plani -- Cambridge "English Grammar in Use" 5. baski, Raymond
-- Murphy -- karsiligi).
--
-- ICERIK KAYNAGI VE TELIF NOTU: Bu migration'daki grammar_topics kayitlarinin
-- SADECE unite/konu basliklari (orn. "Going to ve Will Farki", "Third
-- Conditional") kitaptaki standart dilbilgisi terminolojisinden esinlenerek
-- adlandirilmistir -- bunlar telife konu olmayan genel gramer kavramlaridir.
-- Kural aciklamalari (rule_content_md), ornek cumleler (example_sentences),
-- sik hatalar (common_mistakes) ve tum exam_questions sorulari %100 ozgun
-- olarak yeniden yazilmistir. Kitaptan hicbir cumle, ornek veya alistirma
-- birebir kopyalanmamistir.
--
-- Icerik: 5 yeni grammar_categories (future, ing-to-infinitive,
-- pronouns-determiners, adjectives-adverbs, prepositions), 24 yeni
-- grammar_topics (bir kismi yeni kategorilerde, bir kismi mevcut 9 kategoriye
-- ek olarak), 48 yeni exam_questions -- bunlar mevcut 45 sorunun aksine
-- KELIME/sozcuk degil, DILBILGISI YAPISI (tenses, conditionals, passive,
-- relative clauses, prepositions vb.) test eder ve topic_tag'leri yukaridaki
-- yeni grammar_topics.slug degerleriyle birebir eslesir (029'daki notta
-- belirtilen bosluk boylece kapatilmistir).
--
-- Not: Bu, Murphy kitabinin 145 unitelik tam icerigi degil, ilk 24 unitelik
-- bir genisleme dalgasidir; kalan konular backlog'da.
--
-- Bu SQL, Supabase MCP execute_sql/apply_migration araciyla proje
-- mrxeuxscyztpiuagsumh uzerinde 3 parcada (categories, topics, questions)
-- zaten uygulanmistir; bu dosya repo gecmisi icin ayniyla tekrar eder.

-- new grammar_categories
INSERT INTO grammar_categories (id, slug, name_tr, name_en, sort_order) VALUES ('61d02907-0253-40a4-b4d1-0c74272921d9', 'future', 'Gelecek Zaman', 'Future', 10);
INSERT INTO grammar_categories (id, slug, name_tr, name_en, sort_order) VALUES ('a2d94eeb-7392-44dc-ac26-25515d092ade', 'ing-to-infinitive', 'Fiil + -ing / to', 'Verb + -ing / to', 11);
INSERT INTO grammar_categories (id, slug, name_tr, name_en, sort_order) VALUES ('8177e0ff-0465-4326-883f-7e6cd16d7c80', 'pronouns-determiners', 'Zamirler ve Belirleyiciler', 'Pronouns and Determiners', 12);
INSERT INTO grammar_categories (id, slug, name_tr, name_en, sort_order) VALUES ('04cea72d-2c5f-46f2-a0e3-778e18cd34ad', 'adjectives-adverbs', 'Sıfat ve Zarflar', 'Adjectives and Adverbs', 13);
INSERT INTO grammar_categories (id, slug, name_tr, name_en, sort_order) VALUES ('257372e3-7f2f-4ec7-8e96-c0079591e3ca', 'prepositions', 'Edatlar', 'Prepositions', 14);

-- new grammar_topics
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('f502e0f0-3e2d-4d26-ac4b-f2ad1b5a0d0a', 'future-going-to-will', '61d02907-0253-40a4-b4d1-0c74272921d9', 'en', 'Going to ve Will Farkı', 'Önceden planlanmış niyetler için going to, o an alınan kararlar ve tahminler için will kullanılır.', 'b1', ARRAY['yds','yokdil','toefl'], '- **be going to** önceden karar verilmiş bir plan veya niyeti anlatır: konuşmadan ÖNCE karar verilmiştir.
- **will** ise konuşma anında alınan ani kararlar, sözler (promise) ve gelecekle ilgili tahminler için kullanılır.
- Elde somut bir kanıt varsa (bulutlar, hazırlık vb.) going to tercih edilir: ''Look at those clouds -- it''s going to rain.''
- Kişisel görüş bildiren tahminlerde (I think, I''m sure, probably) genellikle will kullanılır.', '[{"en": "I''ve already bought the tickets -- we''re going to see a concert on Friday.", "tr": "Biletleri zaten aldım -- cuma günü bir konsere gideceğiz."}, {"en": "I''m thirsty. I think I''ll get some water.", "tr": "Susadım. Sanırım biraz su alacağım."}, {"en": "Look at the sky -- it''s going to rain soon.", "tr": "Gökyüzüne bak -- az sonra yağmur yağacak."}]'::jsonb, '[{"wrong": "I will go to the cinema tonight, I bought the ticket yesterday.", "correct": "I am going to the cinema tonight, I bought the ticket yesterday.", "note": "Önceden yapılmış bir plan söz konusu olduğunda will değil going to kullanılır."}, {"wrong": "Wait, the phone is ringing, I am going to answer it.", "correct": "Wait, the phone is ringing, I''ll answer it.", "note": "O anda alınan ani kararlarda going to değil will tercih edilir."}]'::jsonb, 'published', 'manual', 1);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('c020443a-24a8-4644-aea8-7aa845c99ad1', 'future-present-continuous', '61d02907-0253-40a4-b4d1-0c74272921d9', 'en', 'Gelecek İçin Şimdiki Zaman', 'Belirli bir zamana ayarlanmış, düzenlenmiş gelecek planları present continuous ile anlatılır.', 'b1', ARRAY['yds','ielts'], '- Present continuous, takvime/programa yerleşmiş, kişilerle önceden ayarlanmış planlar için kullanılır: ''I''m meeting Ali at 6 o''clock.''
- Genellikle belirli bir zaman ifadesiyle (tonight, tomorrow, next week) birlikte kullanılır.
- be going to ile anlam olarak çok yakındır, ama present continuous özellikle BAŞKA biriyle yapılan düzenlemeleri vurgular.
- Kararı sadece kendi başına almak (henüz düzenleme yapılmamış niyet) için going to daha uygundur.', '[{"en": "We''re having dinner with my parents on Sunday.", "tr": "Pazar günü ailemle yemek yiyoruz."}, {"en": "What are you doing this weekend?", "tr": "Bu hafta sonu ne yapıyorsun?"}, {"en": "She isn''t coming to the meeting tomorrow -- she''s on leave.", "tr": "Yarınki toplantıya gelmiyor -- izinli."}]'::jsonb, '[{"wrong": "I go to the dentist tomorrow at 3pm.", "correct": "I''m going to the dentist tomorrow at 3pm.", "note": "Present simple, düzenlenmiş kişisel bir randevu için kullanılmaz; present continuous gerekir."}]'::jsonb, 'published', 'manual', 2);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('1ba03076-e577-4a61-a835-3a7f16e5f8b5', 'future-continuous-perfect', '61d02907-0253-40a4-b4d1-0c74272921d9', 'en', 'Future Continuous ve Future Perfect', 'Future continuous gelecekte belirli bir anda sürmekte olan bir eylemi, future perfect ise belirli bir zamandan önce tamamlanmış olacak bir eylemi anlatır.', 'b2', ARRAY['yds','yokdil','toefl'], '- **Future continuous (will be doing)**: gelecekte belirtilen bir anda eylem devam ediyor olacak. ''This time tomorrow, I''ll be flying to London.''
- **Future perfect (will have done)**: gelecekte belirtilen bir zamandan önce eylem tamamlanmış olacak. ''By 2030, she will have graduated.''
- Future perfect genellikle by + zaman ifadesiyle (by then, by next year) kullanılır.
- YDS/YÖKDİL''de bu iki yapı sıklıkla ''by the time'' bağlacıyla birlikte test edilir.', '[{"en": "By this time next week, we will have finished the project.", "tr": "Gelecek hafta bu saatlerde projeyi bitirmiş olacağız."}, {"en": "Don''t call at 9 -- I''ll be having dinner then.", "tr": "Saat 9''da arama -- o sırada yemek yiyor olacağım."}, {"en": "By the time you arrive, the shop will have closed.", "tr": "Sen vardığında dükkan kapanmış olacak."}]'::jsonb, '[{"wrong": "By 2030, she will graduate from university.", "correct": "By 2030, she will have graduated from university.", "note": "''By + gelecek zaman'' ifadesiyle kullanılan tamamlanmış eylemler için will değil, will have done (future perfect) gerekir."}]'::jsonb, 'published', 'manual', 3);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('b6eb0ab9-2d69-451a-b00f-7c87b44d034a', 'gerund-vs-infinitive', 'a2d94eeb-7392-44dc-ac26-25515d092ade', 'en', 'Fiil + -ing mi, to + Fiil mi?', 'Bazı fiillerden sonra -ing (gerund), bazılarından sonra to + fiil (infinitive) gelir; bazı fiillerde ise anlam değişir.', 'b1', ARRAY['yds','yokdil','toefl','ielts'], '- enjoy, avoid, suggest, finish, mind, consider, admit gibi fiillerden sonra -ing gelir: ''I enjoy reading.''
- want, decide, plan, hope, promise, agree, refuse gibi fiillerden sonra to + fiil gelir: ''I decided to leave.''
- remember, forget, stop, try, regret gibi fiillerde -ing ve to farklı anlamlar taşır: ''I stopped smoking'' ile ''I stopped to smoke'' çok farklıdır.
- Bu liste ezber gerektirir -- YDS/YÖKDİL''de en sık karışan yapılardan biridir.', '[{"en": "She suggested going to the beach.", "tr": "Sahile gitmeyi önerdi."}, {"en": "He refused to answer the question.", "tr": "Soruyu cevaplamayı reddetti."}, {"en": "I remember locking the door.", "tr": "Kapıyı kilitlediğimi hatırlıyorum."}, {"en": "Please remember to lock the door.", "tr": "Kapıyı kilitlemeyi unutma."}]'::jsonb, '[{"wrong": "I enjoy to swim in the sea.", "correct": "I enjoy swimming in the sea.", "note": "enjoy fiilinden sonra to değil, -ing (gerund) gelir."}, {"wrong": "They decided going to the concert.", "correct": "They decided to go to the concert.", "note": "decide fiilinden sonra -ing değil, to + fiil (infinitive) gelir."}]'::jsonb, 'published', 'manual', 1);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('265700fb-0422-4608-aa77-c5d37423fcd1', 'verb-preposition-ing', 'a2d94eeb-7392-44dc-ac26-25515d092ade', 'en', 'Edat + -ing Kullanımı', 'Bir edattan sonra fiil her zaman -ing formunda kullanılır, asla to + fiil gelmez.', 'b2', ARRAY['yds','yokdil'], '- Bir edattan hemen sonra fiil geliyorsa bu fiil MUTLAKA -ing alır: ''interested in learning'', ''good at cooking'', ''afraid of flying''.
- ''to'' bazen bir edat olarak da kullanılabilir (look forward to, be used to, object to) -- bu durumlarda da to''dan sonra -ing gelir, infinitive DEĞİL.
- Bu kural, look forward to gibi kalıpları to + fiil ile karıştıran öğrenciler için YDS''de klasik bir tuzaktır.', '[{"en": "I''m looking forward to seeing you again.", "tr": "Seni tekrar görmeyi dört gözle bekliyorum."}, {"en": "She''s not used to working night shifts.", "tr": "Gece vardiyasında çalışmaya alışkın değil."}, {"en": "He apologized for being late.", "tr": "Geç kaldığı için özür diledi."}]'::jsonb, '[{"wrong": "I look forward to hear from you.", "correct": "I look forward to hearing from you.", "note": "Buradaki ''to'' bir edattır (infinitive işareti değil), bu yüzden sonrasında -ing gelmelidir."}]'::jsonb, 'published', 'manual', 2);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('2fffb535-fa49-4c8e-bbbf-0ca524e8533e', 'used-to-be-used-to', 'a2d94eeb-7392-44dc-ac26-25515d092ade', 'en', 'used to / be used to / get used to Farkı', 'used to + fiil geçmişteki alışkanlıkları, be/get used to + -ing ise bir duruma alışkın olmayı/alışmayı anlatır.', 'b1', ARRAY['yds','yokdil'], '- **used to + fiil**: geçmişte düzenli yapılan ama artık yapılmayan bir alışkanlık/durum. ''I used to smoke.''
- **be used to + -ing/isim**: bir şeye ALIŞKIN olmak. ''I am used to the noise.''
- **get used to + -ing/isim**: bir şeye ALIŞMAK, alışma SÜRECİ. ''It took me months to get used to the climate.''
- used to sadece geçmiş zamanda vardır (present formu yoktur); be/get used to ise her zamanda çekimlenebilir.', '[{"en": "I used to live in Ankara, but now I live in Izmir.", "tr": "Eskiden Ankara''da yaşardım, ama şimdi İzmir''de yaşıyorum."}, {"en": "She is used to working long hours.", "tr": "Uzun saatler çalışmaya alışkın."}, {"en": "It took me a while to get used to driving on the left.", "tr": "Soldan sürmeye alışmam biraz zaman aldı."}]'::jsonb, '[{"wrong": "I am used to wake up early when I was a soldier.", "correct": "I used to wake up early when I was a soldier.", "note": "Geçmişte bırakılmış bir alışkanlık anlatılıyorsa ''be used to'' değil, sadece ''used to'' kullanılır."}, {"wrong": "She used to living in a big city.", "correct": "She is used to living in a big city.", "note": "''alışkın olmak'' anlamı için ''be used to'' gerekir, çıplak ''used to'' bu anlamı vermez."}]'::jsonb, 'published', 'manual', 3);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('bc461409-1510-4ad5-9b0d-ce9c78a24b2d', 'quantifiers-much-many-few-little', '8177e0ff-0465-4326-883f-7e6cd16d7c80', 'en', 'much/many/little/few/a lot of Kullanımı', 'Sayılamayan isimlerle much/little, sayılabilen çoğul isimlerle many/few kullanılır; a lot of ikisiyle de kullanılabilir.', 'a2', ARRAY['yds','ielts','toefl'], '- **many** ve **few** sayılabilen çoğul isimlerle kullanılır: many books, few friends.
- **much** ve **little** sayılamayan isimlerle kullanılır: much time, little information.
- **a lot of / lots of** her iki isim türüyle de rahatça kullanılabilir, özellikle olumlu cümlelerde tercih edilir.
- **a few / a little** ''birazcık ama yeterli'' anlamı taşır; **few / little** (a''sız) ise ''neredeyse hiç yok, yetersiz'' anlamı taşır -- bu ayrım YDS''de sık sorulur.', '[{"en": "We don''t have much time left.", "tr": "Fazla zamanımız kalmadı."}, {"en": "She has a few close friends.", "tr": "Birkaç yakın arkadaşı var."}, {"en": "He has few close friends.", "tr": "Neredeyse hiç yakın arkadaşı yok."}]'::jsonb, '[{"wrong": "There isn''t many information about this topic.", "correct": "There isn''t much information about this topic.", "note": "''information'' sayılamayan bir isimdir, bu yüzden many değil much ile kullanılır."}, {"wrong": "I have a little friends in this city.", "correct": "I have a few friends in this city.", "note": "''friends'' sayılabilen çoğul bir isim olduğu için a little değil a few ile kullanılır."}]'::jsonb, 'published', 'manual', 1);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('8afe963f-09e2-4f8f-a4cc-4563f656b91f', 'all-both-neither-either', '8177e0ff-0465-4326-883f-7e6cd16d7c80', 'en', 'all / both / neither / either Kullanımı', 'both iki şeyin ikisini de, either ikisinden birini, neither ikisinden hiçbirini, all ise ikiden fazla şeyin tamamını ifade eder.', 'b1', ARRAY['yds','yokdil'], '- **both** iki kişi/şey için ''ikisi de'' anlamındadır: ''Both of my parents are teachers.''
- **either** iki seçenekten birini belirtir: ''You can take either road.''
- **neither** iki şeyin ikisinin de değil, hiçbirinin olmadığını anlatır ve kendi içinde olumsuzluk taşır -- ''not'' ile birlikte kullanılmaz: ''Neither of them is right.''
- İkiden fazla şey söz konusuysa either/neither/both değil, all/none/any kullanılır.', '[{"en": "Both of the candidates gave strong answers.", "tr": "Adayların ikisi de güçlü cevaplar verdi."}, {"en": "Neither of the two plans worked.", "tr": "İki planın da hiçbiri işe yaramadı."}, {"en": "All of the students passed the exam.", "tr": "Öğrencilerin hepsi sınavı geçti."}]'::jsonb, '[{"wrong": "Neither of them are not coming to the party.", "correct": "Neither of them is coming to the party.", "note": "neither zaten olumsuz anlam taşır, cümleye ayrıca ''not'' eklenmez."}, {"wrong": "Both of them is late again.", "correct": "Both of them are late again.", "note": "''both of them'' çoğul özne olduğu için fiil de çoğul (are) olmalıdır."}]'::jsonb, 'published', 'manual', 2);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('94fb9825-43e5-4d53-9f0e-99fcdacf65de', 'reflexive-pronouns', '8177e0ff-0465-4326-883f-7e6cd16d7c80', 'en', 'Dönüşlü Zamirler (myself/yourself vb.)', 'Eylemi yapan ile eylemden etkilenen aynı kişi olduğunda dönüşlü zamirler kullanılır.', 'a2', ARRAY['yds'], '- Özne ile nesne aynı kişiyse dönüşlü zamir kullanılır: ''She hurt herself.''
- ''by + dönüşlü zamir'' kalıbı ''tek başına, kimsenin yardımı olmadan'' anlamına gelir: ''He did it by himself.''
- Bazı fiiller Türkçede dönüşlü gibi düşünülse de İngilizcede dönüşlü zamir ALMAZ: wash, dress, shave, feel, relax, concentrate.
- ''each other'' iki kişi arasındaki KARŞILIKLI eylemi anlatır (dönüşlü zamirle karıştırılmamalıdır): ''They looked at each other.''', '[{"en": "I taught myself how to play the guitar.", "tr": "Gitar çalmayı kendi kendime öğrendim."}, {"en": "Make yourself at home.", "tr": "Kendi evindeymiş gibi rahat ol."}, {"en": "They''ve known each other since childhood.", "tr": "Çocukluktan beri birbirlerini tanıyorlar."}]'::jsonb, '[{"wrong": "Every morning he shaves himself before work.", "correct": "Every morning he shaves before work.", "note": "shave gibi fiiller İngilizcede genellikle dönüşlü zamir almadan kullanılır."}, {"wrong": "We know us for ten years.", "correct": "We have known each other for ten years.", "note": "Karşılıklı bir eylem anlatılırken dönüşlü zamir değil ''each other'' kullanılır."}]'::jsonb, 'published', 'manual', 3);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('63b66db9-e5ee-407b-8bbc-39f14484036e', 'comparatives-superlatives', '04cea72d-2c5f-46f2-a0e3-778e18cd34ad', 'en', 'Karşılaştırma ve Üstünlük Sıfatları', 'Kısa sıfatlara -er/-est, uzun sıfatlara more/most eklenir; bazı sıfatlar düzensizdir.', 'a2', ARRAY['yds','ielts','toefl'], '- Tek heceli sıfatlar: -er / -est eklenir (cheap -> cheaper -> the cheapest).
- İki heceli ve -y ile bitenler: -ier / -iest (happy -> happier -> the happiest).
- İki heceden uzun sıfatlar: more / the most eklenir (expensive -> more expensive -> the most expensive).
- Düzensiz sıfatlar ezberlenmelidir: good->better->the best, bad->worse->the worst, far->further->the furthest.
- ''as...as'' eşitlik karşılaştırması için kullanılır: ''This bag is as heavy as that one.''', '[{"en": "This year''s exam was much more difficult than last year''s.", "tr": "Bu yılki sınav geçen yılkinden çok daha zordu."}, {"en": "He is the tallest student in the class.", "tr": "Sınıftaki en uzun öğrenci o."}, {"en": "My phone isn''t as fast as yours.", "tr": "Telefonum seninki kadar hızlı değil."}]'::jsonb, '[{"wrong": "This question is more easier than the previous one.", "correct": "This question is easier than the previous one.", "note": "Bir sıfat zaten -er almışsa başına ayrıca ''more'' getirilmez."}, {"wrong": "She is the most best singer I know.", "correct": "She is the best singer I know.", "note": "''best'' zaten düzensiz üstünlük halidir, başına ayrıca ''most'' getirilmez."}]'::jsonb, 'published', 'manual', 1);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('11df5f26-2630-474b-959d-a92e86620196', 'adjective-order-formation', '04cea72d-2c5f-46f2-a0e3-778e18cd34ad', 'en', '-ing/-ed Sıfatları ve Sıfat Sırası', '-ing sıfatları bir şeyin özelliğini, -ed sıfatları o şeyden etkilenen kişinin duygusunu anlatır; birden fazla sıfat kullanılırken belli bir sıra izlenir.', 'b1', ARRAY['yds','yokdil'], '- **-ing sıfatları** (boring, interesting, exciting) bir şeyin NASIL olduğunu anlatır: ''The film was boring.''
- **-ed sıfatları** (bored, interested, excited) bir kişinin o şeyden nasıl ETKİLENDİĞİNİ anlatır: ''I was bored during the film.''
- Birden fazla sıfat sıralanırken genel eğilim: görüş -> boyut -> yaş -> şekil -> renk -> köken -> malzeme + isim.
- Bu sıralama katı bir kural değil eğilimdir, ama YDS/YÖKDİL''de en sık test edilen kombinasyon: görüş + boyut/yaş + köken/malzeme.', '[{"en": "I found the lecture quite confusing.", "tr": "Dersi oldukça kafa karıştırıcı buldum."}, {"en": "I was confused by the instructions.", "tr": "Talimatlar kafamı karıştırdı."}, {"en": "She bought a beautiful old wooden table.", "tr": "Güzel, eski, ahşap bir masa aldı."}]'::jsonb, '[{"wrong": "I am so boring in this meeting.", "correct": "I am so bored in this meeting.", "note": "Kişinin kendisinin sıkıldığını anlatmak için -ing değil -ed sıfatı kullanılmalıdır."}, {"wrong": "She has a wooden beautiful old table.", "correct": "She has a beautiful old wooden table.", "note": "Sıfat sırasında görüş (beautiful) diğer sıfatlardan önce, malzeme (wooden) ise isme en yakın konumda gelir."}]'::jsonb, 'published', 'manual', 2);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('904af216-05e9-4a85-9175-8285f40477bb', 'adverbs-of-degree', '04cea72d-2c5f-46f2-a0e3-778e18cd34ad', 'en', 'so / such / enough / too Kullanımı', 'so sıfat/zarftan önce, such isim öbeğinden önce gelir; enough yeterliliği, too aşırılığı anlatır.', 'b1', ARRAY['yds','yokdil','toefl'], '- **so** + sıfat/zarf: ''The exam was so difficult.''
- **such** + (a/an) + sıfat + isim: ''It was such a difficult exam.''
- **enough** sıfattan SONRA, isimden ÖNCE gelir: ''old enough'' ama ''enough time''.
- **too** aşırılık bildirir ve genellikle istenmeyen bir sonuca yol açar: ''too tired to walk''.
- so...that / such...that kalıbı sonuç cümleciği kurar: ''It was so cold that we stayed home.''', '[{"en": "It was such a long journey that everyone fell asleep.", "tr": "O kadar uzun bir yolculuktu ki herkes uyuyakaldı."}, {"en": "She isn''t old enough to drive.", "tr": "Araba kullanamayacak kadar genç."}, {"en": "This coffee is too hot to drink.", "tr": "Bu kahve içilemeyecek kadar sıcak."}]'::jsonb, '[{"wrong": "I am not enough tall to reach the shelf.", "correct": "I am not tall enough to reach the shelf.", "note": "''enough'' sıfattan sonra gelir; sıfattan önce kullanılmaz."}, {"wrong": "It was so a difficult decision.", "correct": "It was such a difficult decision.", "note": "Bir isim öbeğinden önce so değil such kullanılır."}]'::jsonb, 'published', 'manual', 3);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('77c4cf50-fe20-41fb-bc54-d4d92717c596', 'prepositions-time', '257372e3-7f2f-4ec7-8e96-c0079591e3ca', 'en', 'Zaman Edatları: at / on / in', 'Saatler ve noktasal anlarla at, günler ve tarihlerle on, aylar/yıllar/mevsimlerle in kullanılır.', 'a2', ARRAY['yds','ielts','toefl'], '- **at**: saatler (at 6 o''clock), belirli anlar (at night, at the weekend, at Christmas).
- **on**: günler (on Monday), tarihler (on 5th May), özel günler (on my birthday).
- **in**: aylar (in June), yıllar (in 2020), mevsimler (in summer), uzun dönemler (in the morning -- ama ''at night'' istisnadır).
- ''next/last/every/this'' kelimelerinden önce hiçbir edat KULLANILMAZ: ''next week''.', '[{"en": "The meeting starts at 9 o''clock on Monday.", "tr": "Toplantı pazartesi saat 9''da başlıyor."}, {"en": "She was born in 1998, in the spring.", "tr": "1998''de, ilkbaharda doğdu."}, {"en": "I''ll see you next week.", "tr": "Seni gelecek hafta görürüm."}]'::jsonb, '[{"wrong": "I will call you in next week.", "correct": "I will call you next week.", "note": "''next/last/every/this'' ile başlayan zaman ifadelerinden önce edat kullanılmaz."}]'::jsonb, 'published', 'manual', 1);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('4553fa69-d858-4208-a5aa-9bc3853137a3', 'prepositions-place', '257372e3-7f2f-4ec7-8e96-c0079591e3ca', 'en', 'Yer Edatları: at / on / in', 'Bir nokta için at, bir yüzey için on, bir hacim/alan içinde olmak için in kullanılır.', 'a2', ARRAY['yds','ielts'], '- **at**: bir NOKTA olarak düşünülen yer: ''at the bus stop'', ''at the door'', ''at the corner''.
- **on**: bir YÜZEY üzerinde: ''on the table'', ''on the wall'', ''on the second floor''.
- **in**: bir HACİM/ALAN içinde: ''in the box'', ''in the room'', ''in London'', ''in the garden''.
- Şehir/ülke gibi büyük alanlarda in, belirli bir bina/kurumda çalışıyor olmayı ifade ederken at kullanılabilir.', '[{"en": "Wait for me at the entrance.", "tr": "Beni girişte bekle."}, {"en": "There''s a picture on the wall.", "tr": "Duvarda bir tablo var."}, {"en": "They live in a small village in the mountains.", "tr": "Dağlarda küçük bir köyde yaşıyorlar."}]'::jsonb, '[{"wrong": "I saw him standing in the bus stop.", "correct": "I saw him standing at the bus stop.", "note": "Durak gibi noktasal bir yer için in değil at kullanılır."}, {"wrong": "There is a spider at the ceiling.", "correct": "There is a spider on the ceiling.", "note": "Tavan bir yüzey olduğu için at değil on kullanılır."}]'::jsonb, 'published', 'manual', 2);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('68ba5ecb-be06-4d3f-a52a-c7c40432509a', 'dependent-prepositions', '257372e3-7f2f-4ec7-8e96-c0079591e3ca', 'en', 'Sıfat/Fiil + Edat Kalıpları', 'Bazı sıfat ve fiiller belirli edatlarla sabit kalıplar oluşturur; bu kalıplar Türkçedeki edat kullanımıyla birebir örtüşmez ve ezberlenmelidir.', 'b2', ARRAY['yds','yokdil'], '- Sık kullanılan sıfat + edat kalıpları: interested IN, good AT, afraid OF, married TO, similar TO, famous FOR, responsible FOR.
- Sık kullanılan fiil + edat kalıpları: depend ON, believe IN, apologize FOR, consist OF, deal WITH, insist ON, succeed IN.
- Bu kalıplarda edat seçimi genellikle Türkçedeki karşılığından farklıdır -- YDS/YÖKDİL''de en sık hata yapılan alanlardan biridir.', '[{"en": "This job depends on your experience.", "tr": "Bu iş deneyimine bağlı."}, {"en": "The committee is responsible for the final decision.", "tr": "Komite nihai karardan sorumludur."}, {"en": "She succeeded in convincing the board.", "tr": "Yönetim kurulunu ikna etmeyi başardı."}]'::jsonb, '[{"wrong": "He is married with a doctor.", "correct": "He is married to a doctor.", "note": "''married'' sıfatı with değil to edatıyla kullanılır."}, {"wrong": "I''m not interested about politics.", "correct": "I''m not interested in politics.", "note": "''interested'' sıfatı about değil in edatıyla kullanılır."}]'::jsonb, 'published', 'manual', 3);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('7fdab097-fe79-4f28-b7e3-2f1644ae869a', 'conditionals-third', '3bab55a9-719e-4872-881f-bdac0d123eb0', 'en', 'Third Conditional (Geçmişe Yönelik Hayali Durumlar)', 'Geçmişte gerçekleşmemiş bir durumun, gerçekleşmiş OLSAYDI nasıl bir sonuç doğuracağını anlatmak için third conditional kullanılır.', 'b2', ARRAY['yds','yokdil','toefl'], '- Yapı: If + past perfect, ... would have + past participle. ''If I had studied harder, I would have passed the exam.''
- Bu yapı GERÇEKLEŞMEMİŞ bir geçmiş durumu anlatır.
- Pişmanlık (regret) anlatmak için de sıklıkla kullanılır: ''If I had known, I wouldn''t have said that.''
- would yerine could/might de kullanılabilir, anlam değişir.', '[{"en": "If she had left earlier, she wouldn''t have missed the flight.", "tr": "Daha erken çıksaydı, uçağı kaçırmazdı."}, {"en": "We would have won the match if we had played better.", "tr": "Daha iyi oynasaydık maçı kazanırdık."}, {"en": "If I had known about the meeting, I could have attended.", "tr": "Toplantıdan haberim olsaydı katılabilirdim."}]'::jsonb, '[{"wrong": "If I studied harder, I would have passed the exam.", "correct": "If I had studied harder, I would have passed the exam.", "note": "Geçmişe yönelik hayali durumda if cümleciğinde past simple değil past perfect kullanılmalıdır."}, {"wrong": "If she had left earlier, she wouldn''t miss the flight.", "correct": "If she had left earlier, she wouldn''t have missed the flight.", "note": "Sonuç cümleciğinde would değil would HAVE + past participle kullanılmalıdır."}]'::jsonb, 'published', 'manual', 3);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('18209e8d-1e91-4599-9ec3-514f4b007f49', 'wish-if-only', '3bab55a9-719e-4872-881f-bdac0d123eb0', 'en', 'wish / if only Kullanımı', 'wish ve if only, şimdiki bir durumdan memnuniyetsizlik veya geçmiş için pişmanlık anlatmak için kullanılır; zaman bir kademe geriye kayar.', 'b2', ARRAY['yds','yokdil'], '- Şimdiki durumdan memnuniyetsizlik: wish + past simple. ''I wish I had more free time.''
- Geçmiş için pişmanlık: wish + past perfect. ''I wish I had studied medicine.''
- Birinden bir şeyin değişmesini istemek/şikayet: wish + would. ''I wish you would stop interrupting me.''
- if only, wish ile aynı yapıları kullanır ama anlamı daha güçlü/duygusaldır.', '[{"en": "I wish I lived closer to my family.", "tr": "Keşke aileme daha yakın yaşasaydım."}, {"en": "If only I had taken his advice.", "tr": "Keşke onun tavsiyesini dinleseydim."}, {"en": "I wish it would stop raining.", "tr": "Keşke yağmur dursa."}]'::jsonb, '[{"wrong": "I wish I have more money.", "correct": "I wish I had more money.", "note": "Şu anki bir durumdan memnuniyetsizlik anlatılırken present simple değil past simple kullanılır."}, {"wrong": "I wish I studied harder last year.", "correct": "I wish I had studied harder last year.", "note": "Geçmişe yönelik pişmanlıkta past simple değil past perfect kullanılır."}]'::jsonb, 'published', 'manual', 4);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('42e6aba0-c0b0-4aaa-86bd-83678606befc', 'passive-modals-perfect', '66e1f28f-0a1e-40ab-8dd8-752a4b3292c7', 'en', 'Modal ve Perfect Yapılarda Edilgen Çatı', 'Modal fiillerden ve perfect zamanlardan sonra edilgen çatı be + past participle kalıbıyla kurulur.', 'b2', ARRAY['yds','yokdil'], '- Modal + edilgen: modal + BE + past participle. ''The report must be finished by Friday.''
- Present perfect edilgen: has/have + BEEN + past participle. ''The documents have been signed.''
- Past perfect edilgen: had + BEEN + past participle.
- Modal perfect edilgen (geçmişe yönelik): modal + HAVE BEEN + past participle. ''The letter should have been sent yesterday.''', '[{"en": "This form must be completed in black ink.", "tr": "Bu form siyah kalemle doldurulmalıdır."}, {"en": "The results have already been announced.", "tr": "Sonuçlar zaten açıklandı."}, {"en": "The problem could have been avoided.", "tr": "Sorun önlenebilirdi."}]'::jsonb, '[{"wrong": "The report must finished by Friday.", "correct": "The report must be finished by Friday.", "note": "Modal fiilden sonra edilgen çatı kurulurken ''be'' fiili unutulmamalıdır."}, {"wrong": "The documents have signed by the manager.", "correct": "The documents have been signed by the manager.", "note": "Present perfect edilgende have/has''ten sonra ''been'' gelmelidir."}]'::jsonb, 'published', 'manual', 4);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('0d351f5a-d607-49e6-8bc6-f982fc809cda', 'causative-have-something-done', '66e1f28f-0a1e-40ab-8dd8-752a4b3292c7', 'en', 'have/get something done (Ettirgen Yapı)', 'Bir işi kendimiz değil de başka birine yaptırdığımızı anlatmak için have/get + nesne + past participle kalıbı kullanılır.', 'b2', ARRAY['yds','yokdil'], '- Yapı: have/get + nesne + past participle. ''I had my car repaired.''
- get, have''e göre biraz daha gündelik/konuşma diline yakındır: ''I need to get my hair cut.''
- Bu yapı, başımıza gelen istenmeyen bir olayı anlatmak için de kullanılabilir: ''She had her phone stolen.''
- have/get something done, edilgen çatıdan farklıdır -- vurgu işin BAŞKASI tarafından yapıldığı gerçeğidir.', '[{"en": "We had the kitchen painted last month.", "tr": "Geçen ay mutfağı boyattık."}, {"en": "I''m going to get my eyes tested next week.", "tr": "Gelecek hafta gözlerimi kontrol ettireceğim."}, {"en": "He had his wallet stolen on the train.", "tr": "Trende cüzdanı çalındı."}]'::jsonb, '[{"wrong": "I had my car repair yesterday.", "correct": "I had my car repaired yesterday.", "note": "Ettirgen yapıda fiil past participle (3. hal) formunda olmalıdır, yalın hal değil."}, {"wrong": "She cut her hair by the hairdresser.", "correct": "She had her hair cut by the hairdresser.", "note": "İş başkası tarafından yapıldığında ''have something done'' yapısı kullanılmalıdır."}]'::jsonb, 'published', 'manual', 5);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('78d0edd2-c8a8-4601-89a3-b3943294b711', 'modals-ability', '7497b230-ca4b-4a39-a719-f9fd60ca670a', 'en', 'can / could / be able to (Yetenek)', 'Genel yetenek için can/could, belirli bir durumda başarıyla yapabilmek için özellikle geçmişte was/were able to tercih edilir.', 'a2', ARRAY['yds','ielts','toefl'], '- **can**: şimdiki zamanda genel yetenek. ''She can speak three languages.''
- **could**: geçmişte genel yetenek. ''I could swim when I was five.''
- Geçmişte BELİRLİ, TEK SEFERLİK bir başarıyı anlatırken could DEĞİL, was/were able to (ya da managed to) kullanılır.
- can/could''un gelecek ve perfect formu olmadığı için bu boşluklar be able to ile doldurulur.', '[{"en": "He couldn''t understand the instructions at first.", "tr": "İlk başta talimatları anlayamadı."}, {"en": "After months of practice, she was able to pass the driving test.", "tr": "Aylarca pratik yaptıktan sonra ehliyet sınavını geçmeyi başardı."}, {"en": "In a few years, computers will be able to translate speech instantly.", "tr": "Birkaç yıl içinde bilgisayarlar konuşmayı anında çevirebilecek."}]'::jsonb, '[{"wrong": "Despite the heavy traffic, I could arrive on time.", "correct": "Despite the heavy traffic, I was able to arrive on time.", "note": "Geçmişte belirli, tek seferlik bir başarı anlatılırken could değil was/were able to kullanılmalıdır."}, {"wrong": "I hope I will can finish this by tomorrow.", "correct": "I hope I will be able to finish this by tomorrow.", "note": "can''in gelecek zaman hali olmadığı için will can değil will be able to kullanılmalıdır."}]'::jsonb, 'published', 'manual', 5);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('7c7e09b9-5a2c-424c-b298-ba207e593b14', 'relative-clauses-whose-where', '84cdbc75-d933-40ff-8ef7-cde838f80c0a', 'en', 'whose / where ile İlgi Cümlecikleri', 'whose iyelik/aitlik ilişkisini, where ise bir yer bilgisini bir sonraki cümleciğe bağlamak için kullanılır.', 'b1', ARRAY['yds','yokdil'], '- **whose** bir kişiye/şeye ait olan bir şeyi belirtir (his/her/its yerine geçer): ''That''s the man whose car was stolen.''
- **where** bir yer belirten isimden sonra kullanılır ve ''in/at which'' anlamına gelir: ''This is the school where I studied.''
- when de benzer şekilde zaman belirten isimlerden sonra kullanılır.
- whose canlı/cansız ayrımı yapmaz -- hem insanlar hem nesneler için kullanılabilir.', '[{"en": "She''s the author whose book won the award.", "tr": "Ödülü kazanan kitabın yazarı o."}, {"en": "This is the cafe where we first met.", "tr": "İlk tanıştığımız kafe burası."}, {"en": "I''ll never forget the day when I got my diploma.", "tr": "Diplomamı aldığım günü asla unutmayacağım."}]'::jsonb, '[{"wrong": "That''s the man who''s car was stolen.", "correct": "That''s the man whose car was stolen.", "note": "who''s (who is''in kısaltması) ile whose (iyelik zamiri) karıştırılmamalıdır."}, {"wrong": "This is the school which I studied.", "correct": "This is the school where I studied.", "note": "Bir yeri belirten isimden sonra which değil where kullanılmalıdır."}]'::jsonb, 'published', 'manual', 3);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('d65f28ef-869c-4ad1-b102-b4477f0faa4a', 'countable-uncountable-nouns', '0e09cf97-b155-45eb-a27f-bdc536f317bd', 'en', 'Sayılabilen ve Sayılamayan İsimler', 'Sayılabilen isimler tekil/çoğul olabilir ve a/an alabilir; sayılamayan isimler her zaman tekil kabul edilir ve a/an almaz.', 'a2', ARRAY['yds','ielts','toefl'], '- Sayılabilen isimler (book, idea, chair) hem tekil hem çoğul olabilir.
- Sayılamayan isimler (information, advice, furniture, news, luggage) SADECE tekil kabul edilir, çoğul yapılmaz, önlerine a/an gelmez.
- Sayılamayan bir ismi saymak için bir ölçü birimi kullanılır: ''a piece of advice'', ''a piece of furniture''.
- Bazı isimler Türkçede sayılabilir gibi hissettirse de İngilizcede sayılamaz: information, advice, news, furniture, luggage/baggage, homework, equipment.', '[{"en": "Can you give me some advice?", "tr": "Bana biraz tavsiye verebilir misin?"}, {"en": "We bought a new piece of furniture for the living room.", "tr": "Oturma odası için yeni bir mobilya parçası aldık."}, {"en": "I have a lot of homework to do tonight.", "tr": "Bu akşam yapacak çok ödevim var."}]'::jsonb, '[{"wrong": "She gave me a useful advice.", "correct": "She gave me some useful advice.", "note": "''advice'' sayılamayan bir isim olduğu için başına a/an gelmez."}, {"wrong": "I have many furnitures in my new flat.", "correct": "I have a lot of furniture in my new flat.", "note": "''furniture'' sayılamayan bir isim olduğu için çoğul yapılmaz."}]'::jsonb, 'published', 'manual', 3);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('c1aa8f97-d2e8-4aa4-8277-d9be52986353', 'concession-connectors', '8e943cc9-69d2-4bef-ac3c-9434bd679e5e', 'en', 'although / despite / in spite of Farkı', 'although bir cümleciği bağlar, despite ve in spite of ise bir isim ya da -ing yapısını bağlar.', 'b1', ARRAY['yds','yokdil','toefl'], '- **although / though / even though** + ÖZNE + FİİL: ''Although it was raining, we went out.''
- **despite / in spite of** + İSİM veya -ing: ''Despite the rain, we went out.''
- despite/in spite of''tan sonra ASLA düz bir cümlecik (özne+fiil) gelmez -- en sık yapılan hatadır.
- ''despite the fact that'' kalıbı, despite''tan sonra tam bir cümlecik bağlamak için kullanılabilir.', '[{"en": "Although he was tired, he finished the report.", "tr": "Yorgun olmasına rağmen raporu bitirdi."}, {"en": "Despite the heavy traffic, we arrived on time.", "tr": "Yoğun trafiğe rağmen zamanında vardık."}, {"en": "In spite of having little experience, she got the job.", "tr": "Az deneyimi olmasına rağmen işi aldı."}]'::jsonb, '[{"wrong": "Despite it was raining, we went out.", "correct": "Despite the rain, we went out.", "note": "despite''tan sonra özne+fiil içeren bir cümlecik değil, isim ya da -ing yapısı gelmelidir."}, {"wrong": "Although the heavy traffic, we arrived on time.", "correct": "Although there was heavy traffic, we arrived on time.", "note": "although''tan sonra sadece isim değil, özne+fiil içeren tam bir cümlecik gelmelidir."}]'::jsonb, 'published', 'manual', 2);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('a90dee73-d2f3-4f42-9fe8-49188ed05f02', 'purpose-reason-connectors', '8e943cc9-69d2-4bef-ac3c-9434bd679e5e', 'en', 'so that / in order to / because of Farkı', 'so that ve in order to bir amacı, because of ise bir nedeni bağlamak için kullanılır; because of''tan sonra isim, because''ten sonra cümlecik gelir.', 'b1', ARRAY['yds','yokdil'], '- **in order to / to** + fiil: bir amacı anlatır. ''She left early in order to catch the train.''
- **so that** + özne + can/could/will/would: bir amacı, genellikle bir sonucu vurgulayarak anlatır.
- **because** + özne + fiil: bir nedeni anlatır.
- **because of / due to** + İSİM: bir nedeni anlatır ama sonrasında cümlecik değil isim gelir.', '[{"en": "He studies every night so that he can pass the exam.", "tr": "Sınavı geçebilmek için her gece ders çalışıyor."}, {"en": "The flight was delayed because of bad weather.", "tr": "Uçuş kötü hava koşulları nedeniyle ertelendi."}, {"en": "The flight was delayed because the weather was bad.", "tr": "Uçuş, hava kötü olduğu için ertelendi."}]'::jsonb, '[{"wrong": "The match was cancelled because of it was raining.", "correct": "The match was cancelled because it was raining.", "note": "because of''tan sonra bir cümlecik değil isim/isim öbeği gelmelidir."}, {"wrong": "She saves money for that she can travel more.", "correct": "She saves money so that she can travel more.", "note": "Bir amacı bağlamak için ''for that'' değil ''so that'' kullanılır."}]'::jsonb, 'published', 'manual', 3);

-- new exam_questions (grammar-structure based, not vocab)
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('41abb437-5439-4265-aadb-0685f3553c1b', 'yds', 'A: I don''t feel like cooking tonight. B: Don''t worry, I ------- us something from the new place down the street.', '[{"id": "a", "text": "will order"}, {"id": "b", "text": "am going to order"}, {"id": "c", "text": "order"}, {"id": "d", "text": "am ordering"}]'::jsonb, 'a', 'Konuşma anında alınan ani bir karar söz konusu olduğu için will kullanılır; ''am going to order'' önceden planlanmış bir niyeti ima eder ki bu bağlamla çelişir.', '[{"word": "will (ani karar)", "example": "I''ll answer the phone.", "meaning": "konuşma anında alınan ani karar"}]'::jsonb, 'medium', true, 'en', 'future-going-to-will', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('af91c4f2-8900-42a3-a6d5-fd522cd0e21d', 'toefl', 'Look at those dark clouds over the hills -- it ------- very soon.', '[{"id": "a", "text": "rains"}, {"id": "b", "text": "will rain"}, {"id": "c", "text": "is going to rain"}, {"id": "d", "text": "has rained"}]'::jsonb, 'c', 'Elimizde somut bir kanıt (koyu bulutlar) olduğu için tahmin will değil, going to ile yapılır.', '[{"word": "going to (kanıta dayalı tahmin)", "example": "Look out! You''re going to drop that.", "meaning": "elde kanıt olan tahmin"}]'::jsonb, 'easy', true, 'en', 'future-going-to-will', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('6b798d28-2f66-4523-8e6f-5b5a6c7704ef', 'yds', 'I can''t join you for lunch tomorrow -- I ------- my dentist at noon; it''s been on my calendar for weeks.', '[{"id": "a", "text": "see"}, {"id": "b", "text": "am seeing"}, {"id": "c", "text": "will see"}, {"id": "d", "text": "have seen"}]'::jsonb, 'b', 'Önceden ayarlanmış, takvime yerleşmiş kişisel bir randevu anlatıldığı için present continuous kullanılır.', '[{"word": "present continuous (planlı gelecek)", "example": "We''re flying to Paris next Monday.", "meaning": "önceden düzenlenmiş gelecek plan"}]'::jsonb, 'medium', true, 'en', 'future-present-continuous', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('ca411734-97fb-4ab3-af1f-f7fad3355b2c', 'ielts', 'A: ------- you ------- anything special this weekend? B: Not yet, we haven''t decided.', '[{"id": "a", "text": "Are / doing"}, {"id": "b", "text": "Do / do"}, {"id": "c", "text": "Will / do"}, {"id": "d", "text": "Have / done"}]'::jsonb, 'a', 'Gelecekteki bir plan hakkında soru sorarken present continuous kullanılır.', '[{"word": "present continuous soru kalıbı", "example": "What are you doing tonight?", "meaning": "planlanmış gelecek hakkında soru"}]'::jsonb, 'easy', true, 'en', 'future-present-continuous', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('d3f0d4bf-55d5-4ddb-9cea-88bb998f059b', 'yds', 'By the time the guests arrive, I ------- the whole house, so please don''t worry about helping.', '[{"id": "a", "text": "will have cleaned"}, {"id": "b", "text": "will clean"}, {"id": "c", "text": "am cleaning"}, {"id": "d", "text": "clean"}]'::jsonb, 'a', '''By the time'' + gelecekteki bir zamandan önce tamamlanmış olacak bir eylem anlatıldığı için future perfect (will have cleaned) kullanılır.', '[{"word": "future perfect", "example": "By 2030, she will have graduated.", "meaning": "gelecekte belirli bir zamandan önce tamamlanmış olacak eylem"}]'::jsonb, 'hard', true, 'en', 'future-continuous-perfect', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('0db18fd0-5a6d-481c-b92e-355801d7f378', 'yokdil', 'Don''t try to call me between 8 and 9 tomorrow morning -- I ------- on the highway at that time.', '[{"id": "a", "text": "will drive"}, {"id": "b", "text": "will be driving"}, {"id": "c", "text": "drive"}, {"id": "d", "text": "have driven"}]'::jsonb, 'b', 'Gelecekte belirtilen bir anda sürmekte olacak bir eylem anlatıldığı için future continuous (will be driving) kullanılır.', '[{"word": "future continuous", "example": "This time tomorrow, I''ll be flying to London.", "meaning": "gelecekte belirli bir anda süren eylem"}]'::jsonb, 'hard', true, 'en', 'future-continuous-perfect', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('65653b98-fafd-4548-9204-514edf049d33', 'yds', 'The committee finally agreed ------- the new policy after months of debate.', '[{"id": "a", "text": "implementing"}, {"id": "b", "text": "to implement"}, {"id": "c", "text": "implement"}, {"id": "d", "text": "implemented"}]'::jsonb, 'b', '''agree'' fiilinden sonra -ing değil, to + fiil (infinitive) gelir.', '[{"word": "agree + to", "example": "They agreed to help us.", "meaning": "fiilden sonra infinitive alan yapı"}]'::jsonb, 'medium', true, 'en', 'gerund-vs-infinitive', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('f0b34a15-fb35-4826-958f-807d2dd874b5', 'ielts', 'She avoided ------- eye contact with the interviewer, which made her seem nervous.', '[{"id": "a", "text": "to make"}, {"id": "b", "text": "make"}, {"id": "c", "text": "making"}, {"id": "d", "text": "made"}]'::jsonb, 'c', '''avoid'' fiilinden sonra her zaman -ing (gerund) gelir, to + fiil gelmez.', '[{"word": "avoid + -ing", "example": "He avoided answering the question.", "meaning": "fiilden sonra gerund alan yapı"}]'::jsonb, 'medium', true, 'en', 'gerund-vs-infinitive', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('fe825891-29a7-4506-a402-9b7d6a12732b', 'yds', 'The manager apologized for ------- the deadline without informing the team in advance.', '[{"id": "a", "text": "change"}, {"id": "b", "text": "changed"}, {"id": "c", "text": "to change"}, {"id": "d", "text": "changing"}]'::jsonb, 'd', 'Bir edattan (for) hemen sonra fiil her zaman -ing formunda kullanılır.', '[{"word": "edat + -ing", "example": "She apologized for being late.", "meaning": "edattan sonra gerund kullanımı"}]'::jsonb, 'hard', true, 'en', 'verb-preposition-ing', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('d9c2df96-0acc-4b60-9ee9-f6484745e949', 'yokdil', 'I''m really looking forward to ------- you at the conference next month.', '[{"id": "a", "text": "see"}, {"id": "b", "text": "seeing"}, {"id": "c", "text": "seen"}, {"id": "d", "text": "have seen"}]'::jsonb, 'b', 'Buradaki ''to'' bir edattır (look forward TO), bu yüzden sonrasında infinitive değil -ing gelir.', '[{"word": "look forward to + -ing", "example": "I look forward to hearing from you.", "meaning": "edat olarak kullanılan to''dan sonra gerund"}]'::jsonb, 'hard', true, 'en', 'verb-preposition-ing', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('12b01fd7-beaf-4978-b0c4-6f0ef9e75330', 'yds', 'When I was a child, I ------- to the park every Sunday with my grandfather, but we don''t do that anymore.', '[{"id": "a", "text": "used to go"}, {"id": "b", "text": "am used to going"}, {"id": "c", "text": "was used to go"}, {"id": "d", "text": "use to going"}]'::jsonb, 'a', 'Geçmişte düzenli yapılan ama artık yapılmayan bir alışkanlık anlatıldığı için ''used to + fiil'' kullanılır.', '[{"word": "used to", "example": "I used to smoke.", "meaning": "bırakılmış geçmiş alışkanlık"}]'::jsonb, 'medium', true, 'en', 'used-to-be-used-to', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('26206fd9-0ced-4941-bc3c-fecc74d889b6', 'yokdil', 'It took her a few months, but she eventually ------- the noise from the construction site next door.', '[{"id": "a", "text": "used to get"}, {"id": "b", "text": "got used to"}, {"id": "c", "text": "was used to"}, {"id": "d", "text": "used to"}]'::jsonb, 'b', 'Bir şeye alışma sürecini anlatmak için ''get used to + isim/-ing'' kullanılır.', '[{"word": "get used to", "example": "It took me months to get used to the climate.", "meaning": "bir şeye alışma süreci"}]'::jsonb, 'hard', true, 'en', 'used-to-be-used-to', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('658e12a3-75bb-4638-96b6-1ee50729f4ed', 'ielts', 'There isn''t ------- traffic on this road at this time of day, so we should arrive early.', '[{"id": "a", "text": "many"}, {"id": "b", "text": "much"}, {"id": "c", "text": "few"}, {"id": "d", "text": "a few"}]'::jsonb, 'b', '''traffic'' sayılamayan bir isim olduğu için many değil much ile kullanılır.', '[{"word": "much (sayılamayan)", "example": "We don''t have much time.", "meaning": "sayılamayan isimle kullanılan miktar sözcüğü"}]'::jsonb, 'easy', true, 'en', 'quantifiers-much-many-few-little', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('db620cab-f87d-4102-ac7f-879ce8130b45', 'yds', 'Unfortunately, ------- people showed up to the lecture, so it was cancelled.', '[{"id": "a", "text": "little"}, {"id": "b", "text": "much"}, {"id": "c", "text": "few"}, {"id": "d", "text": "a little"}]'::jsonb, 'c', '''people'' sayılabilen çoğul bir isimdir ve ''neredeyse hiç yok'' anlamı verildiği için a''sız few kullanılır.', '[{"word": "few (yetersiz)", "example": "He has few close friends.", "meaning": "neredeyse hiç yok anlamı"}]'::jsonb, 'medium', true, 'en', 'quantifiers-much-many-few-little', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('b834a97e-58c6-4eb9-9e0e-bb1f516a986a', 'yds', 'You can park on ------- side of the street; there are no restrictions today.', '[{"id": "a", "text": "either"}, {"id": "b", "text": "neither"}, {"id": "c", "text": "both"}, {"id": "d", "text": "all"}]'::jsonb, 'a', 'İki seçenekten (iki taraftan) herhangi birinin serbest olduğu anlatıldığı için ''either'' kullanılır.', '[{"word": "either (ikisinden biri)", "example": "You can take either road.", "meaning": "iki seçenekten herhangi biri"}]'::jsonb, 'medium', true, 'en', 'all-both-neither-either', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('efe31f88-c8b1-47b8-b8cb-5a0bbbc77e3d', 'yokdil', '------- of the two candidates was able to answer the final question correctly.', '[{"id": "a", "text": "Both"}, {"id": "b", "text": "All"}, {"id": "c", "text": "Neither"}, {"id": "d", "text": "Either"}]'::jsonb, 'c', 'İki kişiden hiçbirinin başaramadığı anlatıldığı için, kendi içinde olumsuzluk taşıyan neither kullanılır.', '[{"word": "neither (ikisinden hiçbiri)", "example": "Neither of them is right.", "meaning": "iki şeyin ikisinin de değil"}]'::jsonb, 'hard', true, 'en', 'all-both-neither-either', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('875e0999-8414-4fc5-a9b1-1f245d5fa510', 'yds', 'He was so proud that he had built the shed entirely by -------.', '[{"id": "a", "text": "him"}, {"id": "b", "text": "himself"}, {"id": "c", "text": "his"}, {"id": "d", "text": "he"}]'::jsonb, 'b', '''by + dönüşlü zamir'' kalıbı ''kimsenin yardımı olmadan'' anlamına gelir.', '[{"word": "by himself", "example": "He did it by himself.", "meaning": "kimsenin yardımı olmadan"}]'::jsonb, 'easy', true, 'en', 'reflexive-pronouns', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('f3dac238-e506-4232-8664-6d80da4a49cc', 'yds', 'Every morning he ------- before leaving for work, just like he has for the past ten years.', '[{"id": "a", "text": "shaves himself"}, {"id": "b", "text": "shaves"}, {"id": "c", "text": "shaves him"}, {"id": "d", "text": "is shaved"}]'::jsonb, 'b', '''shave'' gibi fiiller İngilizcede genellikle dönüşlü zamir almadan kullanılır.', '[{"word": "shave (dönüşlü zamirsiz)", "example": "He shaves every morning.", "meaning": "dönüşlü zamir almayan fiil"}]'::jsonb, 'medium', true, 'en', 'reflexive-pronouns', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('1a7252fe-d9e5-4660-a307-c3ae8b8bf908', 'ielts', 'This year''s exam was ------- than last year''s, according to most of the students.', '[{"id": "a", "text": "more difficult"}, {"id": "b", "text": "difficult"}, {"id": "c", "text": "most difficult"}, {"id": "d", "text": "the most difficult"}]'::jsonb, 'a', 'İki heceden uzun sıfatlarda karşılaştırma more ile yapılır.', '[{"word": "more + sıfat", "example": "This bag is more expensive than that one.", "meaning": "uzun sıfatlarda karşılaştırma"}]'::jsonb, 'easy', true, 'en', 'comparatives-superlatives', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('8a3b884e-809b-4e19-9e55-b150fbc2faa1', 'toefl', 'Of all the singers in the competition, she was clearly -------.', '[{"id": "a", "text": "the better"}, {"id": "b", "text": "better"}, {"id": "c", "text": "the best"}, {"id": "d", "text": "the goodest"}]'::jsonb, 'c', '''good'' sıfatının düzensiz üstünlük hali ''the best''tir.', '[{"word": "good -> the best", "example": "She is the best singer I know.", "meaning": "düzensiz üstünlük hali"}]'::jsonb, 'medium', true, 'en', 'comparatives-superlatives', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('014e05ab-be57-4f78-ac29-ce1e39491ce2', 'yds', 'I found the safety instructions extremely -------, so I had to read them twice.', '[{"id": "a", "text": "confused"}, {"id": "b", "text": "confusing"}, {"id": "c", "text": "confuse"}, {"id": "d", "text": "confusion"}]'::jsonb, 'b', 'Talimatların kendisinin nasıl olduğu anlatıldığı için -ed değil -ing sıfatı kullanılır.', '[{"word": "-ing sıfatı", "example": "The film was boring.", "meaning": "bir şeyin özelliğini anlatan sıfat"}]'::jsonb, 'medium', true, 'en', 'adjective-order-formation', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('a7d02d47-c257-4aac-841c-7637aae316c2', 'yokdil', 'She showed us photos of a ------- house she had visited in Portugal.', '[{"id": "a", "text": "wooden beautiful old"}, {"id": "b", "text": "old wooden beautiful"}, {"id": "c", "text": "beautiful old wooden"}, {"id": "d", "text": "beautiful wooden old"}]'::jsonb, 'c', 'Sıfat sıralamasında görüş (beautiful) önce, yaş (old) sonra, malzeme (wooden) isme en yakın konumda gelir.', '[{"word": "sıfat sırası", "example": "a beautiful old wooden table", "meaning": "görüş-yaş-malzeme sıralaması"}]'::jsonb, 'hard', true, 'en', 'adjective-order-formation', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('fa08c931-da10-43bd-97dc-839195943db2', 'yds', 'It was ------- cold that we decided to cancel the trip.', '[{"id": "a", "text": "such"}, {"id": "b", "text": "so"}, {"id": "c", "text": "too"}, {"id": "d", "text": "very"}]'::jsonb, 'b', 'so...that kalıbı bir sıfattan önce kullanılır; such ise isim öbeğinden önce gelir.', '[{"word": "so...that", "example": "It was so cold that we stayed home.", "meaning": "sıfattan önce gelen sonuç bağlacı"}]'::jsonb, 'medium', true, 'en', 'adverbs-of-degree', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('c3a49fb7-8928-4139-b9a7-10c4a471d978', 'toefl', 'We didn''t have ------- time to visit every museum on our list.', '[{"id": "a", "text": "such"}, {"id": "b", "text": "so"}, {"id": "c", "text": "enough"}, {"id": "d", "text": "too"}]'::jsonb, 'c', '''enough'' isimden önce gelerek yeterlilik ifade eder.', '[{"word": "enough + isim", "example": "I don''t have enough time.", "meaning": "isimden önce gelen yeterlilik sözcüğü"}]'::jsonb, 'medium', true, 'en', 'adverbs-of-degree', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('4e6b8a53-87f9-487a-9559-aba00bc50725', 'ielts', 'The store closes ------- 9 p.m. every day except Sunday.', '[{"id": "a", "text": "in"}, {"id": "b", "text": "on"}, {"id": "c", "text": "at"}, {"id": "d", "text": "by"}]'::jsonb, 'c', 'Saatlerle ''at'' edatı kullanılır.', '[{"word": "at + saat", "example": "The meeting starts at 9 o''clock.", "meaning": "saatlerle kullanılan edat"}]'::jsonb, 'easy', true, 'en', 'prepositions-time', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('3fb8d1a6-30bd-4e1f-abb9-2ed23da7551c', 'yds', 'She started her new job ------- the spring of 2021.', '[{"id": "a", "text": "at"}, {"id": "b", "text": "on"}, {"id": "c", "text": "in"}, {"id": "d", "text": "since"}]'::jsonb, 'c', 'Mevsimlerle ''in'' edatı kullanılır.', '[{"word": "in + mevsim", "example": "She was born in the spring.", "meaning": "mevsimlerle kullanılan edat"}]'::jsonb, 'easy', true, 'en', 'prepositions-time', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('50417b9b-872b-4831-9961-6fbc8c2415e1', 'ielts', 'I''ll meet you ------- the entrance to the museum at ten.', '[{"id": "a", "text": "in"}, {"id": "b", "text": "on"}, {"id": "c", "text": "at"}, {"id": "d", "text": "by"}]'::jsonb, 'c', 'Noktasal bir yer (giriş) anlatıldığı için ''at'' kullanılır.', '[{"word": "at + nokta", "example": "Wait for me at the entrance.", "meaning": "noktasal yer bildiren edat"}]'::jsonb, 'easy', true, 'en', 'prepositions-place', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('f9447a8d-c781-44e5-96ba-c8f10205c5d3', 'yds', 'There was a large stain ------- the carpet that nobody could explain.', '[{"id": "a", "text": "at"}, {"id": "b", "text": "in"}, {"id": "c", "text": "on"}, {"id": "d", "text": "to"}]'::jsonb, 'c', 'Halı bir yüzey olduğu için ''on'' kullanılır.', '[{"word": "on + yüzey", "example": "There''s a picture on the wall.", "meaning": "yüzey bildiren edat"}]'::jsonb, 'medium', true, 'en', 'prepositions-place', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('0bd615ea-8dcb-47b4-ad25-f9504b4f114e', 'yokdil', 'The success of the project largely depends ------- how well the team communicates.', '[{"id": "a", "text": "of"}, {"id": "b", "text": "on"}, {"id": "c", "text": "with"}, {"id": "d", "text": "for"}]'::jsonb, 'b', '''depend'' fiili ''on'' edatıyla sabit bir kalıp oluşturur.', '[{"word": "depend on", "example": "This job depends on your experience.", "meaning": "fiil + edat kalıbı"}]'::jsonb, 'hard', true, 'en', 'dependent-prepositions', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('d07a3083-cd2c-49e7-b7c5-223faaa2afbc', 'yds', 'She has always been interested ------- ancient history, ever since she was a child.', '[{"id": "a", "text": "of"}, {"id": "b", "text": "about"}, {"id": "c", "text": "in"}, {"id": "d", "text": "for"}]'::jsonb, 'c', '''interested'' sıfatı ''in'' edatıyla kullanılır.', '[{"word": "interested in", "example": "I''m not interested in politics.", "meaning": "sıfat + edat kalıbı"}]'::jsonb, 'hard', true, 'en', 'dependent-prepositions', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('a8e39926-1a3c-44a5-bc68-2654f33c4463', 'yds', 'If we ------- earlier, we wouldn''t have missed the opening ceremony.', '[{"id": "a", "text": "left"}, {"id": "b", "text": "had left"}, {"id": "c", "text": "would leave"}, {"id": "d", "text": "leave"}]'::jsonb, 'b', 'Geçmişe yönelik hayali bir durum anlatıldığı için if cümleciğinde past perfect kullanılır.', '[{"word": "third conditional", "example": "If I had studied harder, I would have passed.", "meaning": "geçmişe yönelik hayali durum"}]'::jsonb, 'hard', true, 'en', 'conditionals-third', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('ddfcca50-65a3-43da-853e-12def4c67ade', 'yokdil', 'She would have accepted the offer if the salary ------- higher.', '[{"id": "a", "text": "was"}, {"id": "b", "text": "is"}, {"id": "c", "text": "had been"}, {"id": "d", "text": "would be"}]'::jsonb, 'c', 'Third conditional yapısında if cümleciğinde past perfect kullanılır.', '[{"word": "third conditional", "example": "If it had been sunny, we would have gone out.", "meaning": "geçmişe yönelik hayali durum"}]'::jsonb, 'hard', true, 'en', 'conditionals-third', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('66917147-e9fa-4386-a4a7-cd7c498f3f0a', 'yds', 'I wish I ------- more time to prepare for the interview, but it''s too late now.', '[{"id": "a", "text": "have"}, {"id": "b", "text": "had"}, {"id": "c", "text": "will have"}, {"id": "d", "text": "having"}]'::jsonb, 'b', 'Şimdiki bir durumdan memnuniyetsizlik anlatılırken wish + past simple kullanılır.', '[{"word": "wish + past simple", "example": "I wish I lived closer to my family.", "meaning": "şimdiki duruma memnuniyetsizlik"}]'::jsonb, 'medium', true, 'en', 'wish-if-only', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('ec2cee7a-cefa-4f3b-9593-3327d73d53cc', 'yokdil', 'If only I ------- his advice before investing all my savings.', '[{"id": "a", "text": "took"}, {"id": "b", "text": "take"}, {"id": "c", "text": "had taken"}, {"id": "d", "text": "would take"}]'::jsonb, 'c', 'Geçmişe yönelik bir pişmanlık anlatıldığı için if only + past perfect kullanılır.', '[{"word": "if only + past perfect", "example": "If only I had taken his advice.", "meaning": "geçmişe yönelik pişmanlık"}]'::jsonb, 'hard', true, 'en', 'wish-if-only', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('2ee652a0-0f5c-495e-b2c6-cf503bd28cea', 'yds', 'All application forms ------- by the end of business on Friday.', '[{"id": "a", "text": "must submit"}, {"id": "b", "text": "must be submitted"}, {"id": "c", "text": "must submitted"}, {"id": "d", "text": "must be submit"}]'::jsonb, 'b', 'Modal fiilden sonra edilgen çatı ''modal + be + past participle'' şeklinde kurulur.', '[{"word": "modal + edilgen", "example": "This form must be completed in black ink.", "meaning": "modal fiilden sonra edilgen çatı"}]'::jsonb, 'hard', true, 'en', 'passive-modals-perfect', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('3c7ffa4b-0832-4dd5-86ab-0490718d7ef3', 'yokdil', 'The accident ------- if the driver had been paying more attention.', '[{"id": "a", "text": "could avoid"}, {"id": "b", "text": "could have avoided"}, {"id": "c", "text": "could have been avoided"}, {"id": "d", "text": "could be avoided"}]'::jsonb, 'c', 'Geçmişe yönelik edilgen bir olasılık anlatıldığı için ''modal + have been + past participle'' kullanılır.', '[{"word": "modal perfect edilgen", "example": "The problem could have been avoided.", "meaning": "geçmişe yönelik edilgen olasılık"}]'::jsonb, 'hard', true, 'en', 'passive-modals-perfect', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('e5b91618-c0d2-489e-ad01-317ada00930e', 'yds', 'We ------- the roof repaired last month after the storm damaged it.', '[{"id": "a", "text": "had"}, {"id": "b", "text": "made"}, {"id": "c", "text": "did"}, {"id": "d", "text": "got done"}]'::jsonb, 'a', 'Bir işi başkasına yaptırdığımızı anlatmak için ''have + nesne + past participle'' kalıbı kullanılır.', '[{"word": "have something done", "example": "I had my car repaired.", "meaning": "ettirgen yapı"}]'::jsonb, 'medium', true, 'en', 'causative-have-something-done', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('bf0edc85-9b7d-4310-ab7f-137f6ad2776a', 'yokdil', 'Unfortunately, she had her laptop ------- while she was on the train.', '[{"id": "a", "text": "steal"}, {"id": "b", "text": "stole"}, {"id": "c", "text": "stolen"}, {"id": "d", "text": "stealing"}]'::jsonb, 'c', 'Başımıza gelen istenmeyen bir olay anlatıldığında ''have something done'' kalıbında past participle kullanılır.', '[{"word": "have something done (istenmeyen olay)", "example": "She had her phone stolen.", "meaning": "istenmeyen olay ettirgeni"}]'::jsonb, 'hard', true, 'en', 'causative-have-something-done', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('b53d8591-a297-46f1-9951-b139fe704168', 'ielts', 'Despite having no formal training, he ------- fix the engine himself.', '[{"id": "a", "text": "could"}, {"id": "b", "text": "was able to"}, {"id": "c", "text": "can"}, {"id": "d", "text": "would"}]'::jsonb, 'b', 'Geçmişte belirli, tek seferlik bir başarı anlatıldığı için could değil was able to kullanılır.', '[{"word": "was able to", "example": "She was able to pass the driving test.", "meaning": "geçmişte tek seferlik başarı"}]'::jsonb, 'easy', true, 'en', 'modals-ability', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('4fcc00db-42d2-4413-945b-2706a27d2095', 'toefl', 'I hope that one day robots ------- perform complex surgery without any human help.', '[{"id": "a", "text": "can"}, {"id": "b", "text": "could"}, {"id": "c", "text": "will be able to"}, {"id": "d", "text": "will can"}]'::jsonb, 'c', 'can''in gelecek zaman formu olmadığı için ''will be able to'' kullanılır.', '[{"word": "will be able to", "example": "Computers will be able to translate speech instantly.", "meaning": "gelecek zamanda yetenek"}]'::jsonb, 'medium', true, 'en', 'modals-ability', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('a78e40b5-bff8-4e07-847b-df48cda955fd', 'yds', 'That''s the company ------- founder started the business in his garage.', '[{"id": "a", "text": "who"}, {"id": "b", "text": "which"}, {"id": "c", "text": "whose"}, {"id": "d", "text": "where"}]'::jsonb, 'c', 'Bir şirkete ait olan bir şey (kurucusu) anlatıldığı için iyelik bildiren ''whose'' kullanılır.', '[{"word": "whose", "example": "That''s the man whose car was stolen.", "meaning": "iyelik bildiren ilgi zamiri"}]'::jsonb, 'medium', true, 'en', 'relative-clauses-whose-where', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('d86075fd-8c8b-4d45-bf12-ccd463a43394', 'yokdil', 'This is the hospital ------- I was born, over thirty years ago.', '[{"id": "a", "text": "which"}, {"id": "b", "text": "whose"}, {"id": "c", "text": "who"}, {"id": "d", "text": "where"}]'::jsonb, 'd', 'Bir yer belirten isimden sonra ''where'' kullanılır.', '[{"word": "where", "example": "This is the school where I studied.", "meaning": "yer bildiren ilgi zamiri"}]'::jsonb, 'medium', true, 'en', 'relative-clauses-whose-where', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('7a4df127-f750-425f-96a1-315911b201d9', 'ielts', 'Could you give me some ------- about how to fill in this form correctly?', '[{"id": "a", "text": "advices"}, {"id": "b", "text": "an advice"}, {"id": "c", "text": "advice"}, {"id": "d", "text": "advice''s"}]'::jsonb, 'c', '''advice'' sayılamayan bir isimdir; çoğul yapılmaz ve başına a/an gelmez.', '[{"word": "advice (sayılamayan)", "example": "She gave me some useful advice.", "meaning": "sayılamayan isim"}]'::jsonb, 'easy', true, 'en', 'countable-uncountable-nouns', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('6b1989de-f408-401b-8f1f-f5404b1ce8c6', 'toefl', 'We need to buy a new piece of ------- for the office, maybe a bookshelf.', '[{"id": "a", "text": "furnitures"}, {"id": "b", "text": "furniture"}, {"id": "c", "text": "a furniture"}, {"id": "d", "text": "furniture''s"}]'::jsonb, 'b', '''furniture'' sayılamayan bir isim olduğu için çoğul yapılmaz ve tekil kullanılır.', '[{"word": "furniture (sayılamayan)", "example": "a piece of furniture", "meaning": "sayılamayan isim"}]'::jsonb, 'medium', true, 'en', 'countable-uncountable-nouns', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('300493a3-687e-49ba-838f-45c3d486baff', 'yds', '------- the heavy rain, thousands of fans stayed until the very end of the concert.', '[{"id": "a", "text": "Although"}, {"id": "b", "text": "Despite"}, {"id": "c", "text": "Because"}, {"id": "d", "text": "Since"}]'::jsonb, 'b', 'Sonrasında isim öbeği geldiği için (the heavy rain) despite kullanılır; although''tan sonra özne+fiil içeren bir cümlecik gelmelidir.', '[{"word": "despite + isim", "example": "Despite the heavy traffic, we arrived on time.", "meaning": "isimden önce gelen zıtlık bağlacı"}]'::jsonb, 'medium', true, 'en', 'concession-connectors', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('f5a1b824-2450-4013-b6f6-5085eaeaf17a', 'toefl', '------- he had very little experience, he was offered the position immediately.', '[{"id": "a", "text": "Despite"}, {"id": "b", "text": "In spite of"}, {"id": "c", "text": "Although"}, {"id": "d", "text": "Because of"}]'::jsonb, 'c', 'Sonrasında özne+fiil içeren tam bir cümlecik (he had very little experience) geldiği için although kullanılır.', '[{"word": "although + cümlecik", "example": "Although he was tired, he finished the report.", "meaning": "cümlecikten önce gelen zıtlık bağlacı"}]'::jsonb, 'hard', true, 'en', 'concession-connectors', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('594dc306-47c8-4bd1-9b30-0e21921d1f9f', 'yds', 'The flight was delayed for several hours ------- a technical problem with the aircraft.', '[{"id": "a", "text": "because"}, {"id": "b", "text": "because of"}, {"id": "c", "text": "so that"}, {"id": "d", "text": "although"}]'::jsonb, 'b', 'Sonrasında bir isim öbeği (a technical problem) geldiği için because of kullanılır.', '[{"word": "because of + isim", "example": "The flight was delayed because of bad weather.", "meaning": "isimden önce gelen neden bağlacı"}]'::jsonb, 'medium', true, 'en', 'purpose-reason-connectors', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('9605eb20-c718-4820-afa7-58f5a1336aa5', 'yokdil', 'She left the office early ------- she could pick her daughter up from school.', '[{"id": "a", "text": "because of"}, {"id": "b", "text": "so that"}, {"id": "c", "text": "in order"}, {"id": "d", "text": "despite"}]'::jsonb, 'b', 'Bir amacı, özne+fiil içeren bir cümlecikle bağlamak için ''so that'' kullanılır.', '[{"word": "so that", "example": "He studies every night so that he can pass the exam.", "meaning": "amaç bildiren bağlaç"}]'::jsonb, 'medium', true, 'en', 'purpose-reason-connectors', 'system', 'approved');
