-- 031_grammar_reference_wave2.sql
--
-- Gramer Rehberi 2. dalga genisleme -- Cambridge "English Grammar in Use"
-- (Murphy, 5. baski) icerigine paralel, kitaptaki en zayif 3 bolum:
-- Present Perfect and Past (bolum 2), Questions and Auxiliary Verbs (bolum 8,
-- yeni kategori), Prepositions (bolum 15).
--
-- ICERIK KAYNAGI VE TELIF NOTU: Bu migration'daki grammar_topics kayitlarinin
-- SADECE unite/konu basliklari kitaptaki standart dilbilgisi terminolojisinden
-- esinlenerek adlandirilmistir -- bunlar telife konu olmayan genel gramer
-- kavramlaridir. Kural aciklamalari (rule_content_md), ornek cumleler
-- (example_sentences), sik hatalar (common_mistakes) ve tum exam_questions
-- sorulari %100 ozgun olarak yazilmistir. Kitaptan hicbir cumle, ornek veya
-- alistirma birebir kopyalanmamistir.
--
-- Icerik: 1 yeni grammar_categories (questions-auxiliaries), 15 yeni
-- grammar_topics (tenses kategorisine +7, yeni questions-auxiliaries
-- kategorisine +3, prepositions kategorisine +5), 30 yeni exam_questions
-- (her yeni konu icin 2 soru, topic_tag = grammar_topics.slug ile birebir
-- eslesir).
--
-- Bu SQL, Supabase MCP apply_migration araciyla proje mrxeuxscyztpiuagsumh
-- uzerinde 3 parcada (categories, topics, questions) zaten uygulanmistir; bu
-- dosya repo gecmisi icin ayniyla tekrar eder.

-- new grammar_categories
INSERT INTO grammar_categories (id, slug, name_tr, name_en, sort_order) VALUES ('3fe6dd0f-8a4f-4ab8-a4d9-c8f53d87793e', 'questions-auxiliaries', 'Sorular ve Yardımcı Fiiller', 'Questions and Auxiliary Verbs', 15);

-- new grammar_topics
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('d3c1dd53-cd9b-4b35-bf86-beea5466b7ea', 'present-perfect-continuous', (SELECT id FROM grammar_categories WHERE slug = 'tenses'), 'en', 'Present Perfect Continuous Kullanımı', 'Bir eylemin geçmişte başlayıp hâlâ sürdüğünü veya yakın zamanda bitmiş olsa da etkisi hâlâ hissedildiğini vurgulamak için have/has been + fiil-ing kullanılır.', 'b1', ARRAY['yds','toefl','ielts'], '- have/has been + fiil-ing yapısı, geçmişte başlayıp şu ana kadar SÜREN bir eylemi anlatır ve genellikle eylemin SÜRESİNE vurgu yapar.
- for/since ile birlikte sıkça kullanılır: "I''ve been waiting for two hours."
- Eylem az önce bitmiş olsa bile, şu anki sonucunu/etkisini açıklamak için de kullanılabilir: "Why are you so tired? -- I''ve been running."
- Durum fiilleri (know, believe, love, want gibi) normalde continuous formda kullanılmaz; bu fiillerle present perfect simple tercih edilir.', '[{"en": "I''ve been studying English for three years.", "tr": "Üç yıldır İngilizce çalışıyorum."}, {"en": "It''s been raining since this morning.", "tr": "Sabahtan beri yağmur yağıyor."}, {"en": "Her eyes are red -- she''s been crying.", "tr": "Gözleri kızarmış -- ağlıyormuş."}]'::jsonb, '[{"wrong": "I have been knowing him for years.", "correct": "I have known him for years.", "note": "know bir durum fiilidir, continuous formda kullanılmaz; present perfect simple gerekir."}, {"wrong": "She is study English since 2019.", "correct": "She has been studying English since 2019.", "note": "since ile süregelen bir eylem anlatılırken present perfect continuous gerekir, present continuous değil."}]'::jsonb, 'published', 'manual', 3);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('be270b76-6d9f-473a-8f0d-4c74f69cb538', 'present-perfect-simple-vs-continuous', (SELECT id FROM grammar_categories WHERE slug = 'tenses'), 'en', 'Present Perfect Simple ve Continuous Farkı', 'Present perfect simple sonucu/tamamlanmayı, present perfect continuous ise eylemin süresini ve devamlılığını vurgular.', 'b2', ARRAY['yds','yokdil','ielts'], '- Present perfect SIMPLE, bir eylemin SONUCUNA veya kaç kez/ne kadar yapıldığına odaklanır: "I''ve read three books this month."
- Present perfect CONTINUOUS, eylemin kendisinin ne kadar SÜRDÜĞÜNE odaklanır, sonuçtan çok sürece vurgu yapar: "I''ve been reading for three hours."
- Kalıcı/sürekli değişim bildiren fiillerde (improve, grow, increase) genellikle simple form tercih edilir: "The company has grown a lot."
- Sayılabilir bir miktar/sonuç belirtiliyorsa (how many, how much) simple form kullanılır; sadece süre belirtiliyorsa (how long) continuous form daha doğaldır.', '[{"en": "I''ve written five emails this morning.", "tr": "Bu sabah beş e-posta yazdım."}, {"en": "I''ve been writing emails all morning.", "tr": "Bütün sabah e-posta yazıyorum (yazmakla meşgulüm)."}, {"en": "He has repaired ten cars this week.", "tr": "Bu hafta on araba tamir etti."}]'::jsonb, '[{"wrong": "I have been reading three books this month.", "correct": "I have read three books this month.", "note": "Belirli bir sayı/sonuç vurgulanıyorsa (three books) continuous değil simple form kullanılır."}, {"wrong": "She has improving her English a lot.", "correct": "She has improved her English a lot.", "note": "improve gibi kalıcı bir gelişimi bildiren fiillerle genellikle simple form tercih edilir."}]'::jsonb, 'published', 'manual', 4);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('6b968593-d885-48dd-ba39-116189dc4066', 'for-since-how-long', (SELECT id FROM grammar_categories WHERE slug = 'tenses'), 'en', 'for / since / how long Kullanımı', 'for bir sürenin uzunluğunu, since bir başlangıç noktasını belirtir; how long ile süre sorulur.', 'a2', ARRAY['yds','yokdil'], '- **for** bir eylemin ne KADAR SÜREDİR devam ettiğini belirtir: for two years, for a long time, for ages.
- **since** eylemin BAŞLADIĞI noktayı belirtir: since 2015, since Monday, since I was a child.
- **How long** sorusu genellikle present perfect (simple veya continuous) ile birlikte kullanılır: "How long have you lived here?"
- since''den sonra bir zaman noktası veya bir cümle (özne+fiil) gelebilir; for''dan sonra ise her zaman bir süre ifadesi gelir.', '[{"en": "How long have you known each other?", "tr": "Birbirinizi ne zamandır tanıyorsunuz?"}, {"en": "We have lived in this house for eight years.", "tr": "Bu evde sekiz yıldır yaşıyoruz."}, {"en": "I haven''t seen her since last summer.", "tr": "Geçen yazdan beri onu görmedim."}]'::jsonb, '[{"wrong": "I have worked here since five years.", "correct": "I have worked here for five years.", "note": "Bir süre uzunluğu belirtiliyorsa (five years) since değil for kullanılır."}, {"wrong": "She has lived in London for 2010.", "correct": "She has lived in London since 2010.", "note": "Belirli bir başlangıç noktası (2010 yılı) belirtiliyorsa for değil since kullanılır."}]'::jsonb, 'published', 'manual', 5);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('75cc1733-eba5-493b-96db-2b96d7554bb4', 'already-yet-still', (SELECT id FROM grammar_categories WHERE slug = 'tenses'), 'en', 'already / yet / still Kullanımı', 'already olumlu cümlelerde beklenenden önce gerçekleşeni, yet olumsuz/soru cümlelerinde henüz gerçekleşmeyeni, still devam eden bir durumu anlatır.', 'a2', ARRAY['yds','toefl'], '- **already** genellikle olumlu cümlelerde, bir şeyin beklenenden erken veya çoktan gerçekleştiğini vurgulamak için kullanılır: "I''ve already finished my homework."
- **yet** genellikle olumsuz ve soru cümlelerinin SONUNDA kullanılır, bir şeyin henüz gerçekleşmediğini/gerçekleşip gerçekleşmediğini sorar: "Haven''t you finished yet?"
- **still** bir durumun beklenenden UZUN sürdüğünü, hâlâ devam ettiğini vurgular ve genellikle özne ile ana fiil arasına yerleşir: "She still hasn''t replied."
- already cümle içinde fiilden hemen önce, yet ise genellikle cümle sonunda yer alır.', '[{"en": "We''ve already booked the hotel.", "tr": "Oteli çoktan ayırttık."}, {"en": "Have you finished the report yet?", "tr": "Raporu henüz bitirdin mi?"}, {"en": "He still hasn''t called me back.", "tr": "Hâlâ beni geri aramadı."}]'::jsonb, '[{"wrong": "I already have finished my homework.", "correct": "I have already finished my homework.", "note": "already normalde yardımcı fiil (have) ile ana fiil ARASINA yerleşir."}, {"wrong": "Did you finish the project already, or are you still working on it?", "correct": "Have you finished the project yet, or are you still working on it?", "note": "Bir şeyin henüz olup olmadığını soran nötr sorularda already değil yet tercih edilir."}]'::jsonb, 'published', 'manual', 6);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('53199afc-c245-4a78-8b70-03484fde56bf', 'gone-vs-been', (SELECT id FROM grammar_categories WHERE slug = 'tenses'), 'en', 'been to / gone to Farkı', 'have been to bir yere gidip GERİ DÖNMÜŞ olmayı, have gone to ise hâlâ o yerde olmayı veya yolda olmayı anlatır.', 'b1', ARRAY['yds','yokdil'], '- **have/has been to** bir yere daha önce gidip geri DÖNMÜŞ olmayı anlatır: "I''ve been to Paris twice." (Paris''e gittim ve geri döndüm.)
- **have/has gone to** kişinin hâlâ o yerde olduğunu veya oraya doğru yolda olduğunu anlatır, konuşan kişi genellikle o yerde DEĞİLDİR: "She''s gone to the bank."
- Deneyim anlatırken (kaç kere gidildiği) been to tercih edilir.
- gone to ile kurulan cümlede özne şu anda konuşmanın yapıldığı yerde YOKTUR; been to''da ise özne artık geri dönmüştür.', '[{"en": "I have been to Japan three times.", "tr": "Japonya''ya üç kere gittim (ve döndüm)."}, {"en": "Where''s Ali? -- He''s gone to the gym.", "tr": "Ali nerede? -- Spor salonuna gitti (hâlâ orada)."}, {"en": "Have you ever been to an opera?", "tr": "Hiç operaya gittin mi?"}]'::jsonb, '[{"wrong": "He has been to the shop, he''ll be back soon.", "correct": "He has gone to the shop, he''ll be back soon.", "note": "Kişi hâlâ dışarıda/dönmediyse been to değil gone to kullanılmalıdır."}, {"wrong": "I have gone to Rome twice in my life.", "correct": "I have been to Rome twice in my life.", "note": "Bir yere daha önce gidip dönmüş olmaktan (deneyim) bahsedilirken been to kullanılır."}]'::jsonb, 'published', 'manual', 7);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('df91848f-054e-49f9-aeea-755d3b163051', 'past-perfect', (SELECT id FROM grammar_categories WHERE slug = 'tenses'), 'en', 'Past Perfect Kullanımı', 'Geçmişte iki olaydan daha ÖNCE gerçekleşeni belirtmek için had + past participle kullanılır.', 'b1', ARRAY['yds','toefl'], '- Past perfect (had + V3), geçmişteki iki olaydan hangisinin DAHA ÖNCE gerçekleştiğini netleştirmek için kullanılır.
- Genellikle before, after, by the time, when gibi bağlaçlarla birlikte past simple ile aynı cümlede kullanılır: "When I arrived, the train had already left."
- Sadece geçmişte tek bir olay anlatılıyorsa (kıyaslanacak ikinci bir olay yoksa) past perfect değil past simple yeterlidir.
- Reported speech''te, direkt cümledeki present perfect veya past simple genellikle past perfect''e döner.', '[{"en": "By the time we got to the cinema, the film had already started.", "tr": "Sinemaya vardığımızda film çoktan başlamıştı."}, {"en": "She had never seen snow before she moved to Canada.", "tr": "Kanada''ya taşınmadan önce hiç kar görmemişti."}, {"en": "I realized I had left my keys at home.", "tr": "Anahtarlarımı evde bıraktığımı fark ettim."}]'::jsonb, '[{"wrong": "When I arrived at the station, the train left.", "correct": "When I arrived at the station, the train had left.", "note": "Trenin kalkışı, varıştan DAHA ÖNCE gerçekleştiği için past perfect kullanılmalıdır."}, {"wrong": "I had finished the exam yesterday.", "correct": "I finished the exam yesterday.", "note": "Kıyaslanacak ikinci bir geçmiş olay yoksa, tek başına geçmiş bir olay için past simple yeterlidir."}]'::jsonb, 'published', 'manual', 8);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('fb029223-f0f4-435b-895d-647f7f267dd7', 'past-perfect-continuous', (SELECT id FROM grammar_categories WHERE slug = 'tenses'), 'en', 'Past Perfect Continuous Kullanımı', 'Geçmişte belirli bir andan önce ne kadar süredir devam etmekte olan bir eylemi anlatmak için had been + fiil-ing kullanılır.', 'b2', ARRAY['yokdil','ielts'], '- had been + -ing yapısı, geçmişteki bir olaydan ÖNCE belirli bir süredir DEVAM ETMEKTE olan bir eylemi anlatır.
- Genellikle for/since ile birlikte kullanılır ve geçmişteki bir olayın NEDENİNİ açıklar: "He was tired because he had been working all day."
- Past perfect simple sonuca, past perfect continuous ise sürece ve süreye odaklanır -- tıpkı present perfect simple/continuous ayrımı gibi.
- Durum fiilleriyle (know, want, believe) past perfect continuous değil past perfect simple kullanılır.', '[{"en": "She was exhausted because she had been studying all night.", "tr": "Bütün gece çalışmış olduğu için bitkindi."}, {"en": "They had been waiting for an hour when the bus finally arrived.", "tr": "Otobüs sonunda geldiğinde bir saattir bekliyorlardı."}, {"en": "The road was wet because it had been raining.", "tr": "Yağmur yağmış olduğu için yol ıslaktı."}]'::jsonb, '[{"wrong": "He was tired because he had work all day.", "correct": "He was tired because he had been working all day.", "note": "had''den sonra been + fiil-ing gelmelidir, çıplak fiil değil."}, {"wrong": "I had been knowing her for years before we became friends.", "correct": "I had known her for years before we became friends.", "note": "know bir durum fiilidir, past perfect continuous değil past perfect simple ile kullanılır."}]'::jsonb, 'published', 'manual', 9);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('479abb51-d506-4239-9637-64a7db3f64d1', 'question-word-order', '3fe6dd0f-8a4f-4ab8-a4d9-c8f53d87793e', 'en', 'Soru Cümlelerinde Kelime Sırası', 'İngilizcede soru cümleleri genellikle yardımcı fiil/modal + özne + ana fiil sırasıyla kurulur; soru kelimesi varsa en başa gelir.', 'a2', ARRAY['yds','toefl'], '- Evet/hayır sorularında sıralama: (Soru kelimesi) + yardımcı fiil/modal + özne + ana fiil: "Do you like coffee?", "Can she drive?"
- be fiili ana fiil olarak kullanıldığında yardımcı fiile gerek yoktur, be doğrudan öznenin önüne geçer: "Is he a teacher?"
- present simple/past simple''da ana fiil bir aksiyon fiili ise do/does/did yardımcı fiili gerekir: "Does she work here?"
- Soru kelimesi (who, what) cümlenin ÖZNESİ ise yardımcı fiil kullanılmaz, düz cümle sırası korunur: "Who broke the window?"', '[{"en": "Where does your brother live?", "tr": "Kardeşin nerede yaşıyor?"}, {"en": "Why are you so quiet today?", "tr": "Bugün neden bu kadar sessizsin?"}, {"en": "Who wrote this letter?", "tr": "Bu mektubu kim yazdı?"}]'::jsonb, '[{"wrong": "Where you are going?", "correct": "Where are you going?", "note": "Soru cümlesinde yardımcı fiil (are) özneden ÖNCE gelmelidir."}, {"wrong": "What means this word?", "correct": "What does this word mean?", "note": "Ana fiil ''mean'' bir aksiyon fiili olduğu için soru kurulurken does yardımcı fiili gerekir."}]'::jsonb, 'published', 'manual', 1);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('c9621392-6041-40dc-8de4-fbdfa37f3747', 'question-tags', '3fe6dd0f-8a4f-4ab8-a4d9-c8f53d87793e', 'en', 'Soru Ekleri (Question Tags)', 'Cümlenin sonuna eklenen kısa sorularda, ana cümle olumluysa etiket olumsuz, ana cümle olumsuzsa etiket olumlu kurulur.', 'b1', ARRAY['yokdil','yds'], '- Ana cümle OLUMLU ise, cümle sonundaki soru eki OLUMSUZ olur: "You live here, don''t you?"
- Ana cümle OLUMSUZ ise, soru eki OLUMLU olur: "She isn''t coming, is she?"
- Soru eki, ana cümledeki yardımcı fiil/modal ile aynı zamanı ve aynı özneyi (zamir olarak) kullanır: "They have finished, haven''t they?"
- Ana cümlede yardımcı fiil yoksa (present/past simple, aksiyon fiili), do/does/did kullanılır: "He likes tea, doesn''t he?"
- "I am" cümlesinin olumsuz soru eki istisnaidir: "I am right, aren''t I?"', '[{"en": "This is your bag, isn''t it?", "tr": "Bu senin çantan, değil mi?"}, {"en": "You haven''t met him before, have you?", "tr": "Onunla daha önce tanışmadın, değil mi?"}, {"en": "Let''s have a break, shall we?", "tr": "Biraz ara verelim, olur mu?"}]'::jsonb, '[{"wrong": "You are tired, are you?", "correct": "You are tired, aren''t you?", "note": "Ana cümle olumlu olduğu için soru eki olumsuz olmalıdır (aren''t you)."}, {"wrong": "She doesn''t like coffee, does she like?", "correct": "She doesn''t like coffee, does she?", "note": "Soru ekinde ana fiil (like) tekrar edilmez, sadece yardımcı fiil + özne kullanılır."}]'::jsonb, 'published', 'manual', 2);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('4325c892-c51e-4689-9d28-baeea34a6798', 'so-neither-agreement', '3fe6dd0f-8a4f-4ab8-a4d9-c8f53d87793e', 'en', 'so / neither ile Katılma İfadeleri', 'Bir cümledeki durumla aynı fikirde/durumda olunduğunu kısaca belirtmek için olumlu cümlelerde so, olumsuz cümlelerde neither/nor kullanılır.', 'b1', ARRAY['ielts','yds'], '- Olumlu bir cümleye aynı durumun geçerli olduğunu eklemek için: **so + yardımcı fiil + özne**: "I love pizza." -- "So do I."
- Olumsuz bir cümleye aynı durumun geçerli olduğunu eklemek için: **neither/nor + yardımcı fiil + özne**: "I don''t like spinach." -- "Neither do I."
- Kullanılan yardımcı fiil, önceki cümledeki yardımcı fiille (veya zamanla) aynı olmalıdır: be->be, do/does/did->do/does/did, have->have, modal->aynı modal.
- Bu yapılarda özne-fiil devrik sırayla kullanılır (yardımcı fiil özneden ÖNCE gelir), normal cümle sırası değil.', '[{"en": "A: I''ve never been to Italy. B: Neither have I.", "tr": "A: Hiç İtalya''ya gitmedim. B: Ben de gitmedim."}, {"en": "A: She can speak French. B: So can I.", "tr": "A: O Fransızca konuşabiliyor. B: Ben de konuşabiliyorum."}, {"en": "A: I''m not hungry. B: Neither am I.", "tr": "A: Aç değilim. B: Ben de değilim."}]'::jsonb, '[{"wrong": "I don''t smoke. -- So don''t I.", "correct": "I don''t smoke. -- Neither do I.", "note": "Olumsuz bir cümleye katılırken so değil neither/nor kullanılmalıdır."}, {"wrong": "She likes tea. -- So I do.", "correct": "She likes tea. -- So do I.", "note": "so ile katılma yapısında yardımcı fiil özneden ÖNCE gelmelidir (devrik sıra)."}]'::jsonb, 'published', 'manual', 3);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('1b0d00d0-3043-4f5a-aa61-e1c43d08455f', 'on-time-in-time', (SELECT id FROM grammar_categories WHERE slug = 'prepositions'), 'en', 'on time / in time Farkı', 'on time planlanan tam saatte olmayı, in time ise bir şey olmadan/geç kalmadan önce yetişmeyi ifade eder.', 'b1', ARRAY['yokdil','toefl'], '- **on time**: önceden belirlenmiş, planlanan tam saatte/zamanda -- ne erken ne geç: "The train arrived on time."
- **in time (for something / to do something)**: bir şey olmadan ÖNCE, son ana yetişerek: "We got to the airport in time to catch our flight."
- "just in time" ifadesi çok kısa sürede, son anda yetişmeyi vurgular: "He arrived just in time for the meeting."
- on time genellikle programlara/randevulara, in time ise bir fırsatı kaçırmamaya odaklanır.', '[{"en": "Please make sure the report is submitted on time.", "tr": "Lütfen raporun zamanında teslim edildiğinden emin ol."}, {"en": "We didn''t get there in time to see the beginning of the film.", "tr": "Filmin başlangıcını görecek kadar erken yetişemedik."}, {"en": "She arrived just in time before the doors closed.", "tr": "Kapılar kapanmadan tam vaktinde geldi."}]'::jsonb, '[{"wrong": "The meeting started in time, at exactly 9 o''clock.", "correct": "The meeting started on time, at exactly 9 o''clock.", "note": "Tam olarak planlanan saatte gerçekleşen bir olay için on time kullanılır."}, {"wrong": "We arrived on time to catch the last bus, just before it left.", "correct": "We arrived in time to catch the last bus, just before it left.", "note": "Bir şeyi kaçırmadan önce son anda yetişmek anlatılırken in time kullanılır."}]'::jsonb, 'published', 'manual', 4);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('c1679b42-8651-49e9-9080-cd63b7d5e7bb', 'by-until', (SELECT id FROM grammar_categories WHERE slug = 'prepositions'), 'en', 'by / until Farkı', 'by bir eylemin en geç ne zamana kadar tamamlanmış olması gerektiğini, until ise bir durumun ne zamana kadar SÜRECEĞİNİ belirtir.', 'b1', ARRAY['yds','yokdil'], '- **by** + zaman: bir eylemin o zamana kadar veya daha ÖNCE TAMAMLANMIŞ olması gerektiğini belirtir: "Please finish the report by Friday."
- **until/till** + zaman: bir durumun/eylemin o ana kadar DEVAM ettiğini, o andan sonra duracağını belirtir: "I''ll be at work until 6 pm."
- by genellikle tamamlanma/son teslim tarihi bildiren fiillerle (finish, submit, complete, arrive) kullanılır.
- until genellikle süreklilik bildiren fiillerle (wait, stay, work, live) kullanılır.', '[{"en": "You need to hand in your assignment by Monday.", "tr": "Ödevini pazartesiye kadar (en geç pazartesi) teslim etmen gerekiyor."}, {"en": "We waited until midnight, but she never came.", "tr": "Gece yarısına kadar bekledik ama hiç gelmedi."}, {"en": "The offer is valid until the end of the month.", "tr": "Teklif ay sonuna kadar geçerlidir."}]'::jsonb, '[{"wrong": "I will have finished the project until Friday.", "correct": "I will have finished the project by Friday.", "note": "Bir eylemin en geç ne zaman TAMAMLANMIŞ olacağı belirtilirken by kullanılır."}, {"wrong": "She will stay in London by next year.", "correct": "She will stay in London until next year.", "note": "Bir durumun ne zamana kadar SÜRECEĞİ anlatılırken until kullanılır."}]'::jsonb, 'published', 'manual', 5);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('4a0b094c-7d61-453f-bf92-740650eb7332', 'during-while', (SELECT id FROM grammar_categories WHERE slug = 'prepositions'), 'en', 'during / while Farkı', 'during bir isimle, while ise özne+fiil içeren bir cümlecikle birlikte kullanılır; ikisi de -esnasında/sırasında anlamı taşır.', 'a2', ARRAY['toefl','ielts'], '- **during** + isim tamlaması: bir olayın/dönemin sürdüğü zaman dilimini belirtir: "during the meeting", "during the summer".
- **while** + özne + fiil (genellikle continuous): iki eylemin aynı anda gerçekleştiğini belirten bir cümlecik kurar: "while I was cooking".
- during''den sonra asla özne+fiil içeren tam bir cümlecik gelmez, sadece isim/isim tamlaması gelir.
- while genellikle geçmişte sürmekte olan bir eylemin ARASINA giren ani bir olayı anlatmak için de kullanılır: "The phone rang while we were having dinner."', '[{"en": "She fell asleep during the film.", "tr": "Film sırasında uyuyakaldı."}, {"en": "While I was walking to work, it started to rain.", "tr": "İşe yürürken yağmur yağmaya başladı."}, {"en": "Please turn off your phone during the exam.", "tr": "Sınav sırasında lütfen telefonunu kapat."}]'::jsonb, '[{"wrong": "During I was studying, the lights went out.", "correct": "While I was studying, the lights went out.", "note": "Özne+fiil içeren bir cümlecikten önce during değil while kullanılır."}, {"wrong": "He called me while the meeting.", "correct": "He called me during the meeting.", "note": "Sadece bir isim (the meeting) geldiği için while değil during kullanılır."}]'::jsonb, 'published', 'manual', 6);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('37a83fce-4d5d-4f53-aafd-d1e236f93dcf', 'prepositions-of-movement', (SELECT id FROM grammar_categories WHERE slug = 'prepositions'), 'en', 'Hareket Edatları (to / into / onto / through / across)', 'Bir yöne doğru hareketi anlatan edatlar (to, into, onto, through, across vb.) hedefe, geçişe veya yüzeye göre değişir.', 'a2', ARRAY['yds','yokdil'], '- **to**: bir hedefe doğru genel yönelim/hareket: "She walked to the station."
- **into**: bir alanın/mekânın İÇİNE doğru hareket: "He ran into the room."
- **onto**: bir yüzeyin ÜZERİNE doğru hareket: "The cat jumped onto the table."
- **through**: bir şeyin içinden GEÇEREK hareket: "We drove through the tunnel."
- **across**: bir yüzeyin/alanın BİR YANINDAN DİĞER YANINA hareket: "They swam across the lake."', '[{"en": "The children ran across the playground.", "tr": "Çocuklar oyun alanının bir ucundan diğerine koştu."}, {"en": "He climbed onto the roof to fix the antenna.", "tr": "Anteni tamir etmek için çatıya çıktı."}, {"en": "She walked into the office without knocking.", "tr": "Kapıyı çalmadan ofise girdi."}]'::jsonb, '[{"wrong": "The ball rolled to the box and stayed inside it.", "correct": "The ball rolled into the box and stayed inside it.", "note": "Bir şeyin bir alanın İÇİNE girdiği vurgulanıyorsa to değil into kullanılmalıdır."}, {"wrong": "We walked across the tunnel to get to the other side of the hill.", "correct": "We walked through the tunnel to get to the other side of the hill.", "note": "Bir şeyin İÇİNDEN geçilerek yapılan hareket için across değil through kullanılır."}]'::jsonb, 'published', 'manual', 7);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('60d3b6ac-2619-4cb6-8edf-f944cd6f8106', 'by-with-agent-instrument', (SELECT id FROM grammar_categories WHERE slug = 'prepositions'), 'en', 'by / with: Edilgen Çatıda Fail ve Araç', 'Edilgen (passive) cümlelerde eylemi yapan kişi/özne by ile, kullanılan araç/alet ise with ile belirtilir.', 'b2', ARRAY['yds','toefl'], '- Edilgen cümlelerde eylemi GERÇEKLEŞTİREN kişi veya kurum **by** ile belirtilir: "The window was broken by the boys."
- Eylemi gerçekleştirmek için kullanılan ARAÇ/ALET ise **with** ile belirtilir: "The window was broken with a hammer."
- Bir cümlede hem fail (by) hem araç (with) birlikte kullanılabilir: "The letter was written by Ali with a fountain pen."
- Fail belirtilmesi zorunlu değildir; özellikle fail belirsiz, önemsiz veya bilinen bir durumsa by ile eklenmez.', '[{"en": "The bridge was designed by a famous engineer.", "tr": "Köprü ünlü bir mühendis tarafından tasarlandı."}, {"en": "The door was opened with a key.", "tr": "Kapı bir anahtarla açıldı."}, {"en": "The cake was decorated by my sister with fresh strawberries.", "tr": "Pasta kız kardeşim tarafından taze çileklerle süslendi."}]'::jsonb, '[{"wrong": "The wall was painted with the workers.", "correct": "The wall was painted by the workers.", "note": "Eylemi gerçekleştiren kişi/fail belirtilirken with değil by kullanılır."}, {"wrong": "The nail was hammered by a hammer.", "correct": "The nail was hammered with a hammer.", "note": "Kullanılan araç/alet belirtilirken by değil with kullanılır."}]'::jsonb, 'published', 'manual', 8);

-- new exam_questions
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('5b6c9269-707e-46ec-9912-53ea43fe7907', 'yds', 'My hands are dirty because I ------- in the garden all morning.', '[{"id": "a", "text": "work"}, {"id": "b", "text": "have been working"}, {"id": "c", "text": "had worked"}, {"id": "d", "text": "was working"}]'::jsonb, 'b', 'Eylemin sonucu (kirli eller) şu anda görülüyor ve sabahtan beri süren bir eylem söz konusu olduğu için present perfect continuous kullanılır.', '[{"word": "have been -ing (süregelen eylem)", "example": "I''ve been waiting for you.", "meaning": "geçmişten şu ana kadar süren eylem"}]'::jsonb, 'medium', true, 'en', 'present-perfect-continuous', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('340a5532-3059-45d1-b57e-6a447b270f99', 'toefl', 'A: You look exhausted. B: I know, I ------- since 6 a.m.', '[{"id": "a", "text": "work"}, {"id": "b", "text": "worked"}, {"id": "c", "text": "have been working"}, {"id": "d", "text": "am working"}]'::jsonb, 'c', 'since ile birlikte, sabahtan beri süren ve şu anki yorgunluğun nedenini açıklayan bir eylem anlatıldığı için present perfect continuous kullanılır.', '[{"word": "since (başlangıç noktası)", "example": "I''ve lived here since 2015.", "meaning": "eylemin başladığı nokta"}]'::jsonb, 'easy', true, 'en', 'present-perfect-continuous', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('61609c18-85a6-44fa-9530-9fa961449536', 'yokdil', 'I ------- five chapters of this novel, and I''m planning to finish it tonight.', '[{"id": "a", "text": "have been reading"}, {"id": "b", "text": "have read"}, {"id": "c", "text": "am reading"}, {"id": "d", "text": "read"}]'::jsonb, 'b', 'Belirli bir sayı (five chapters) vurgulandığı için sürece değil sonuca odaklanan present perfect simple kullanılmalıdır.', '[{"word": "have read (sonuç vurgusu)", "example": "I''ve read the whole book.", "meaning": "tamamlanmış, sayılabilir sonuç"}]'::jsonb, 'hard', true, 'en', 'present-perfect-simple-vs-continuous', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('6c18fa2c-4537-4fdd-bced-cb5d4ae105df', 'ielts', 'Her English has really improved -- she ------- every day this month.', '[{"id": "a", "text": "has been practising"}, {"id": "b", "text": "practised"}, {"id": "c", "text": "practises"}, {"id": "d", "text": "is practising"}]'::jsonb, 'a', 'Sürecin kendisi ve devamlılığı vurgulandığı için (her gün, bu ay boyunca) present perfect continuous daha doğaldır.', '[{"word": "has been -ing (süreç vurgusu)", "example": "She''s been practising a lot.", "meaning": "devam eden, süregelen çaba"}]'::jsonb, 'medium', true, 'en', 'present-perfect-simple-vs-continuous', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('e54abd2d-dacc-41b8-83a5-9b2ba741ff39', 'yds', '------- have you been waiting here?', '[{"id": "a", "text": "How long"}, {"id": "b", "text": "How much"}, {"id": "c", "text": "How far"}, {"id": "d", "text": "How often"}]'::jsonb, 'a', 'Bir eylemin süresi sorulduğu için how long kullanılır.', '[{"word": "how long (süre sorusu)", "example": "How long have you been here?", "meaning": "süre sormak için kullanılır"}]'::jsonb, 'easy', true, 'en', 'for-since-how-long', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('7d762ba0-1d02-4d87-a7d6-3fb4096e8fb2', 'yokdil', 'I haven''t spoken to my cousin ------- her wedding last year.', '[{"id": "a", "text": "for"}, {"id": "b", "text": "since"}, {"id": "c", "text": "during"}, {"id": "d", "text": "while"}]'::jsonb, 'b', 'Belirli bir başlangıç noktası (geçen yılki düğünü) belirtildiği için for değil since kullanılır.', '[{"word": "since (belirli başlangıç noktası)", "example": "since her wedding", "meaning": "olayın başladığı nokta"}]'::jsonb, 'medium', true, 'en', 'for-since-how-long', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('77bccaf4-232d-4b0d-a440-3eca8e6ed380', 'toefl', 'Have you finished your homework -------?', '[{"id": "a", "text": "yet"}, {"id": "b", "text": "already"}, {"id": "c", "text": "still"}, {"id": "d", "text": "since"}]'::jsonb, 'a', 'Bir şeyin henüz olup olmadığını soran nötr bir soruda yet kullanılır.', '[{"word": "yet (henüz, soru/olumsuz)", "example": "I haven''t eaten yet.", "meaning": "henüz gerçekleşmemiş"}]'::jsonb, 'easy', true, 'en', 'already-yet-still', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('eb087a51-c122-4072-9dc3-0fc7dcd20ba5', 'yds', 'Don''t worry about dinner, I ------- cooked it.', '[{"id": "a", "text": "yet"}, {"id": "b", "text": "still"}, {"id": "c", "text": "already"}, {"id": "d", "text": "since"}]'::jsonb, 'c', 'Bir şeyin beklenenden erken/çoktan gerçekleştiğini vurgulayan olumlu bir cümlede already kullanılır.', '[{"word": "already (çoktan)", "example": "I''ve already eaten.", "meaning": "beklenenden önce gerçekleşmiş"}]'::jsonb, 'medium', true, 'en', 'already-yet-still', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('6cef3f15-153f-4642-8bbe-313a1c9bd043', 'yokdil', 'Where''s Elif? -- She ------- to the pharmacy; she''ll be back in ten minutes.', '[{"id": "a", "text": "has been"}, {"id": "b", "text": "has gone"}, {"id": "c", "text": "went"}, {"id": "d", "text": "is going"}]'::jsonb, 'b', 'Elif şu anda konuşmanın yapıldığı yerde olmadığı, eczaneye gittiği ve henüz dönmediği için has gone to kullanılır.', '[{"word": "has gone to (hâlâ orada)", "example": "He''s gone to work.", "meaning": "gidip henüz dönmedi"}]'::jsonb, 'medium', true, 'en', 'gone-vs-been', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('b18f4427-5028-4117-ac8e-eed5dba1fdba', 'yds', 'I ------- to Egypt twice, and both times I visited the pyramids.', '[{"id": "a", "text": "have gone"}, {"id": "b", "text": "have been"}, {"id": "c", "text": "went"}, {"id": "d", "text": "had gone"}]'::jsonb, 'b', 'Bir yere daha önce gidip geri dönmüş olma (deneyim) anlatıldığı için have gone değil have been kullanılır.', '[{"word": "have been to (deneyim)", "example": "I''ve been to Egypt twice.", "meaning": "gidip geri dönmüş olma deneyimi"}]'::jsonb, 'hard', true, 'en', 'gone-vs-been', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('236855de-fc7e-4163-9fb8-95faf91d89ad', 'yds', 'By the time the firefighters arrived, the fire ------- most of the building.', '[{"id": "a", "text": "destroyed"}, {"id": "b", "text": "has destroyed"}, {"id": "c", "text": "had destroyed"}, {"id": "d", "text": "was destroying"}]'::jsonb, 'c', 'İtfaiyecilerin varışından ÖNCE gerçekleşmiş bir eylem söz konusu olduğu için past perfect kullanılır.', '[{"word": "by the time (past perfect tetikleyicisi)", "example": "By the time we left, it had stopped raining.", "meaning": "bir olaydan önce tamamlanmış eylem"}]'::jsonb, 'medium', true, 'en', 'past-perfect', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('b61a2d0c-65fb-460f-9d25-8dd3ac5cba33', 'toefl', 'She told me that she ------- the letter the day before.', '[{"id": "a", "text": "sends"}, {"id": "b", "text": "has sent"}, {"id": "c", "text": "had sent"}, {"id": "d", "text": "sent"}]'::jsonb, 'c', 'Aktarılan cümlede, mektup gönderme eylemi konuşmadan önceki bir geçmiş zamana ait olduğu için past perfect kullanılır.', '[{"word": "reported speech + had (aktarım)", "example": "He said he had finished.", "meaning": "aktarılan cümlede daha önceki geçmiş"}]'::jsonb, 'medium', true, 'en', 'past-perfect', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('b379e6dd-16a1-42d7-9f36-759289381861', 'yokdil', 'His eyes were red because he ------- for hours before the interview.', '[{"id": "a", "text": "had been studying"}, {"id": "b", "text": "has studied"}, {"id": "c", "text": "studied"}, {"id": "d", "text": "was studying"}]'::jsonb, 'a', 'Görüşmeden ÖNCE, saatlerce süren bir eylemin nedeni açıklandığı için past perfect continuous kullanılır.', '[{"word": "had been -ing (geçmişte süregelen neden)", "example": "He was wet because he had been swimming.", "meaning": "bir geçmiş olaydan önce süren eylem"}]'::jsonb, 'hard', true, 'en', 'past-perfect-continuous', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('6f218bb6-4b4d-4979-8550-a3450ab3d483', 'ielts', 'The ground was wet because it ------- all night.', '[{"id": "a", "text": "rained"}, {"id": "b", "text": "has rained"}, {"id": "c", "text": "had been raining"}, {"id": "d", "text": "was raining"}]'::jsonb, 'c', 'Geçmişteki bir durumun (ıslak zemin) nedeni, ondan önce süren bir eylemle açıklandığı için had been raining kullanılır.', '[{"word": "had been raining (neden açıklaması)", "example": "The streets were flooded because it had been raining.", "meaning": "geçmişte süren, sonucu görülen eylem"}]'::jsonb, 'medium', true, 'en', 'past-perfect-continuous', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('b5e9f4b7-d30e-4799-a5ef-9758fd87778c', 'yds', '------- does this word mean in English?', '[{"id": "a", "text": "What"}, {"id": "b", "text": "Which"}, {"id": "c", "text": "Who"}, {"id": "d", "text": "Whose"}]'::jsonb, 'a', 'Bir kelimenin anlamı sorulurken what kullanılır ve aksiyon fiili (mean) olduğu için does yardımcı fiili gerekir.', '[{"word": "what does...mean (anlam sorma)", "example": "What does this sign mean?", "meaning": "bir kelimenin/işaretin anlamını sormak"}]'::jsonb, 'easy', true, 'en', 'question-word-order', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('b923b11d-abe8-43bb-9d7d-cf00819b888e', 'toefl', '------- broke the window yesterday?', '[{"id": "a", "text": "Who does"}, {"id": "b", "text": "Who did"}, {"id": "c", "text": "Who"}, {"id": "d", "text": "Who was"}]'::jsonb, 'c', 'Soru kelimesi (who) cümlenin öznesi olduğu için yardımcı fiil kullanılmaz, düz cümle sırası korunur.', '[{"word": "who (özne sorusu)", "example": "Who called you?", "meaning": "özneyi soran soru kelimesi, yardımcı fiil almaz"}]'::jsonb, 'medium', true, 'en', 'question-word-order', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('794863f3-ac29-4fe7-9689-fe80ecb2c3ca', 'yokdil', 'You''ve never been to Berlin, -------?', '[{"id": "a", "text": "haven''t you"}, {"id": "b", "text": "have you"}, {"id": "c", "text": "don''t you"}, {"id": "d", "text": "didn''t you"}]'::jsonb, 'b', 'Ana cümle olumsuz (never) olduğu için soru eki olumlu olmalıdır; yardımcı fiil have olduğu için ''have you'' kullanılır.', '[{"word": "never (gizli olumsuzluk)", "example": "You''ve never met her, have you?", "meaning": "cümleyi olumsuz yapan zarf"}]'::jsonb, 'medium', true, 'en', 'question-tags', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('99e65b5a-12f2-439e-b281-b4958a8af999', 'yds', 'Let''s take a short break, -------?', '[{"id": "a", "text": "do we"}, {"id": "b", "text": "don''t we"}, {"id": "c", "text": "shall we"}, {"id": "d", "text": "will we"}]'::jsonb, 'c', '''Let''s'' ile başlayan öneri cümlelerinde soru eki her zaman ''shall we'' olur.', '[{"word": "Let''s...shall we? (öneri sorusu)", "example": "Let''s go now, shall we?", "meaning": "öneri cümlelerinin sabit soru eki"}]'::jsonb, 'easy', true, 'en', 'question-tags', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('e6ce918a-b918-4f5f-9aef-b432dc948aa5', 'ielts', 'A: I haven''t finished the report yet. B: ------- I.', '[{"id": "a", "text": "So have"}, {"id": "b", "text": "Neither have"}, {"id": "c", "text": "So has"}, {"id": "d", "text": "Neither has"}]'::jsonb, 'b', 'Olumsuz bir cümleye aynı durumun geçerli olduğunu eklerken neither + yardımcı fiil + özne kullanılır.', '[{"word": "neither have I (olumsuz katılma)", "example": "I haven''t seen it. -- Neither have I.", "meaning": "olumsuz bir duruma katılma"}]'::jsonb, 'medium', true, 'en', 'so-neither-agreement', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('71fee534-8a23-42d6-aea5-7a57bd5b592b', 'yds', 'A: My brother can speak three languages. B: ------- mine.', '[{"id": "a", "text": "So can"}, {"id": "b", "text": "Neither can"}, {"id": "c", "text": "So does"}, {"id": "d", "text": "So is"}]'::jsonb, 'a', 'Olumlu bir cümledeki modal fiil (can) aynen korunarak katılma yapısı kurulur: so can + özne.', '[{"word": "so can I (olumlu katılma)", "example": "He can swim. -- So can I.", "meaning": "olumlu bir duruma katılma"}]'::jsonb, 'medium', true, 'en', 'so-neither-agreement', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('d5c2549a-19e7-4f12-80ed-4fd29158d8e4', 'yokdil', 'We left the house early and got to the airport ------- to check in our luggage.', '[{"id": "a", "text": "on time"}, {"id": "b", "text": "in time"}, {"id": "c", "text": "by time"}, {"id": "d", "text": "until then"}]'::jsonb, 'b', 'Bagajı check-in yaptırmayı kaçırmadan önce, son anda yetişmek anlatıldığı için in time kullanılır.', '[{"word": "in time for/to (son anda yetişmek)", "example": "We got there in time for the show.", "meaning": "bir şeyi kaçırmadan önce yetişmek"}]'::jsonb, 'medium', true, 'en', 'on-time-in-time', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('26f06b16-23f2-4518-aad2-e0fb28aba837', 'toefl', 'The flight departed exactly -------, at 10 a.m. as scheduled.', '[{"id": "a", "text": "in time"}, {"id": "b", "text": "on time"}, {"id": "c", "text": "by time"}, {"id": "d", "text": "until then"}]'::jsonb, 'b', 'Planlanan tam saatte gerçekleşen bir olay için on time kullanılır.', '[{"word": "on time (tam vaktinde)", "example": "The bus left on time.", "meaning": "ne erken ne geç, planlanan saatte"}]'::jsonb, 'easy', true, 'en', 'on-time-in-time', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('5e12f6d3-189f-45c8-86bb-98545c933bd8', 'yds', 'I need this document translated ------- tomorrow morning at the latest.', '[{"id": "a", "text": "until"}, {"id": "b", "text": "by"}, {"id": "c", "text": "during"}, {"id": "d", "text": "since"}]'::jsonb, 'b', 'Bir işin en geç ne zamana kadar tamamlanmış olması gerektiği belirtildiği için by kullanılır.', '[{"word": "by (son tarih)", "example": "Submit it by Friday.", "meaning": "en geç o zamana kadar tamamlanmış olma"}]'::jsonb, 'medium', true, 'en', 'by-until', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('3b3ad36d-a59d-4a42-8981-7efd0431eae2', 'yokdil', 'We can''t leave the office ------- the manager gives us permission.', '[{"id": "a", "text": "by"}, {"id": "b", "text": "until"}, {"id": "c", "text": "during"}, {"id": "d", "text": "for"}]'::jsonb, 'b', 'Bir durumun ne zamana kadar süreceği (izin verilene kadar) belirtildiği için until kullanılır.', '[{"word": "until (süreklilik sınırı)", "example": "Wait until I call you.", "meaning": "bir durumun devam edeceği son nokta"}]'::jsonb, 'medium', true, 'en', 'by-until', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('fa78fd86-63a0-4078-8646-5425b41304b5', 'toefl', 'Please remain seated ------- the flight.', '[{"id": "a", "text": "while"}, {"id": "b", "text": "during"}, {"id": "c", "text": "for"}, {"id": "d", "text": "since"}]'::jsonb, 'b', 'Sonrasında sadece bir isim (the flight) geldiği için while değil during kullanılır.', '[{"word": "during + isim", "example": "during the flight", "meaning": "bir dönemin/olayın sürdüğü zaman"}]'::jsonb, 'easy', true, 'en', 'during-while', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('016e29a5-3fe9-4dfe-9a06-7feeead21f5b', 'ielts', 'She met her husband ------- she was studying abroad.', '[{"id": "a", "text": "during"}, {"id": "b", "text": "while"}, {"id": "c", "text": "for"}, {"id": "d", "text": "by"}]'::jsonb, 'b', 'Sonrasında özne+fiil içeren bir cümlecik geldiği için during değil while kullanılır.', '[{"word": "while + özne+fiil", "example": "while she was studying", "meaning": "aynı anda süren iki eylem"}]'::jsonb, 'medium', true, 'en', 'during-while', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('b029e363-424b-428c-ab21-80830c9c90b2', 'yds', 'The thief climbed ------- the window to enter the house.', '[{"id": "a", "text": "through"}, {"id": "b", "text": "across"}, {"id": "c", "text": "onto"}, {"id": "d", "text": "to"}]'::jsonb, 'a', 'Pencereden içeri girmek, bir açıklıktan geçmeyi ifade ettiği için through kullanılır.', '[{"word": "through (içinden geçerek)", "example": "He climbed through the window.", "meaning": "bir açıklıktan/boşluktan geçerek hareket"}]'::jsonb, 'easy', true, 'en', 'prepositions-of-movement', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('fab12f24-2e81-4b85-b12c-348ed806e126', 'yokdil', 'The dog jumped ------- the sofa and fell asleep.', '[{"id": "a", "text": "into"}, {"id": "b", "text": "onto"}, {"id": "c", "text": "through"}, {"id": "d", "text": "across"}]'::jsonb, 'b', 'Bir yüzeyin (kanepe) üzerine doğru hareket anlatıldığı için onto kullanılır.', '[{"word": "onto (yüzeyin üzerine)", "example": "The cat jumped onto the shelf.", "meaning": "bir yüzeyin üstüne doğru hareket"}]'::jsonb, 'medium', true, 'en', 'prepositions-of-movement', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('433192ca-cbe9-49ef-af50-74ffc8973d7c', 'yds', 'The vase was accidentally broken ------- the cat''s tail.', '[{"id": "a", "text": "by"}, {"id": "b", "text": "with"}, {"id": "c", "text": "from"}, {"id": "d", "text": "of"}]'::jsonb, 'b', 'Kırılmaya neden olan araç (kedinin kuyruğu) belirtildiği için by değil with kullanılır.', '[{"word": "with (araç)", "example": "cut with a knife", "meaning": "eylemi gerçekleştirmek için kullanılan araç"}]'::jsonb, 'medium', true, 'en', 'by-with-agent-instrument', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('74a64713-7b22-46d2-9897-10c6e516d7fb', 'toefl', 'This novel was written ------- one of the most famous authors of the 20th century.', '[{"id": "a", "text": "with"}, {"id": "b", "text": "by"}, {"id": "c", "text": "from"}, {"id": "d", "text": "through"}]'::jsonb, 'b', 'Eylemi gerçekleştiren fail (yazar) belirtildiği için by kullanılır.', '[{"word": "by (fail)", "example": "painted by a famous artist", "meaning": "eylemi gerçekleştiren kişi"}]'::jsonb, 'medium', true, 'en', 'by-with-agent-instrument', 'system', 'approved');
