-- 032_grammar_reference_wave3.sql
--
-- Gramer Rehberi 3. dalga genisleme -- Cambridge "English Grammar in Use"
-- (Murphy, 5. baski) icerigine paralel, kitaptaki 3 bolum: Articles and
-- Nouns (bolum 10), Adjectives and Adverbs (bolum 13), Modals (bolum 4).
--
-- ICERIK KAYNAGI VE TELIF NOTU: Bu migration'daki grammar_topics kayitlarinin
-- SADECE unite/konu basliklari kitaptaki standart dilbilgisi terminolojisinden
-- esinlenerek adlandirilmistir -- bunlar telife konu olmayan genel gramer
-- kavramlaridir. Kural aciklamalari (rule_content_md), ornek cumleler
-- (example_sentences), sik hatalar (common_mistakes) ve tum exam_questions
-- sorulari %100 ozgun olarak yazilmistir. Kitaptan hicbir cumle, ornek veya
-- alistirma birebir kopyalanmamistir.
--
-- Icerik: yeni grammar_categories yok (mevcut articles-nouns, adjectives-adverbs,
-- modals kategorilerine eklendi), 14 yeni grammar_topics (articles-nouns'a +5,
-- adjectives-adverbs'e +5, modals'a +4), 28 yeni exam_questions (her yeni konu
-- icin 2 soru, topic_tag = grammar_topics.slug ile birebir eslesir).
--
-- Bu SQL, Supabase MCP apply_migration araciyla proje mrxeuxscyztpiuagsumh
-- uzerinde 2 parcada (topics, questions) zaten uygulanmistir; bu dosya repo
-- gecmisi icin ayniyla tekrar eder.

-- new grammar_topics
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('25df068a-4147-42cb-959c-6c99b934b3ea', 'the-specific-vs-general', (SELECT id FROM grammar_categories WHERE slug = 'articles-nouns'), 'en', 'the: Belirli ve Genel Anlam Ayrımı', 'Bir isim konuşan ve dinleyen için ortak olarak bilinen, tek olan veya daha önce bahsedilmiş bir şeyi işaret ediyorsa the kullanılır; genel bir kategoriden bahsedilirken artikel kullanılmaz.', 'b1', ARRAY['yds','yokdil'], '- Bir isimden cümlede İLK KEZ bahsediliyorsa a/an, aynı isimden İKİNCİ kez bahsediliyorsa the kullanılır: "I saw a dog. The dog was barking."
- Dünyada TEK olan veya bağlamdan hangisi olduğu belli olan şeylerde the kullanılır: the sun, the internet, the door (odadaki tek kapı).
- Genel bir kategori/kavramdan bahsedilirken (isim çoğul veya sayılamayan formda) artikel kullanılMAZ: "Dogs are loyal animals.", "Music makes me happy."
- Süperlatifler ve sıra bildiren sıfatlardan önce (the first, the best, the only) her zaman the kullanılır.', '[{"en": "I bought a book yesterday. The book was really interesting.", "tr": "Dün bir kitap aldım. Kitap gerçekten ilginçti."}, {"en": "Cats are independent animals.", "tr": "Kediler bağımsız hayvanlardır."}, {"en": "She was the first person to arrive.", "tr": "Gelen ilk kişi oydu."}]'::jsonb, '[{"wrong": "The dogs are loyal animals.", "correct": "Dogs are loyal animals.", "note": "Genel bir kategoriden bahsedilirken the kullanılmaz, çıplak çoğul isim yeterlidir."}, {"wrong": "I need to talk to a manager, he is waiting for me.", "correct": "I need to talk to the manager, he is waiting for me.", "note": "Zaten bahsedilmiş/bilinen bir kişi ikinci kez anılırken a değil the kullanılır."}]'::jsonb, 'published', 'manual', 4);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('3247f333-3c3d-4748-aa56-5f2325617ca2', 'subject-verb-agreement-nouns', (SELECT id FROM grammar_categories WHERE slug = 'articles-nouns'), 'en', 'İsimlerde Özne-Yüklem Uyumu', 'Sayılamayan isimler, bazı toplu isimler ve -s ile biten bazı isimler tekil fiil alır; bazı çoğul görünümlü isimler her zaman çoğul fiil alır.', 'b2', ARRAY['yds','yokdil','toefl'], '- Sayılamayan isimler (information, news, advice, furniture, luggage) her zaman TEKİL fiil alır: "The news is good."
- Konu/bilim adları (mathematics, physics, economics) -s ile bitse de tekil fiil alır: "Mathematics is difficult."
- police, people, cattle gibi bazı isimler tekil formda olsalar da her zaman ÇOĞUL fiil alır: "The police are investigating."
- İngilizce''de "-s" ile biten bazı isimler (news, physics) tekil, bazı hep çoğul isimler (clothes, trousers, scissors) ise her zaman çoğul fiil alır -- ezber gerektirir.', '[{"en": "The information you gave me was very helpful.", "tr": "Bana verdiğin bilgi çok yardımcı oldu."}, {"en": "The police are looking for the suspect.", "tr": "Polis şüpheliyi arıyor."}, {"en": "My trousers are too tight.", "tr": "Pantolonum çok dar."}]'::jsonb, '[{"wrong": "The furniture in this room are very old.", "correct": "The furniture in this room is very old.", "note": "furniture sayılamayan bir isimdir, her zaman tekil fiil alır."}, {"wrong": "The police is investigating the case.", "correct": "The police are investigating the case.", "note": "police her zaman çoğul fiil alan bir isimdir."}]'::jsonb, 'published', 'manual', 5);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('9473fdfe-0873-41d2-b027-710c4c2dab32', 'possessive-s-vs-of', (SELECT id FROM grammar_categories WHERE slug = 'articles-nouns'), 'en', 'İyelik ''s ve of Farkı', 'Canlı varlıklar ve zaman ifadeleri için genellikle ''s, cansız nesneler ve soyut kavramlar için genellikle of yapısı tercih edilir.', 'a2', ARRAY['yds','yokdil'], '- İnsanlar, hayvanlar ve zaman ifadeleriyle genellikle ''s kullanılır: "Ali''s car", "the dog''s tail", "today''s newspaper".
- Cansız nesneler ve soyut kavramlarla genellikle of yapısı tercih edilir: "the roof of the house", "the result of the exam".
- Kurumlar, ülkeler ve organizasyonlar genellikle ''s ile de kullanılabilir: "the company''s profits", "Turkey''s economy".
- Çoğul isimler -s ile bitiyorsa sadece kesme işareti ('') eklenir, ikinci bir s eklenmez: "the students'' books".', '[{"en": "This is my sister''s laptop.", "tr": "Bu kız kardeşimin dizüstü bilgisayarı."}, {"en": "The roof of the building needs repair.", "tr": "Binanın çatısı tamir edilmeli."}, {"en": "The children''s toys are all over the floor.", "tr": "Çocukların oyuncakları yerlere saçılmış."}]'::jsonb, '[{"wrong": "The color of the car''s is red.", "correct": "The color of the car is red.", "note": "Cansız bir nesne için genellikle of yapısı tercih edilir; ''s ile of aynı anda kullanılmaz."}, {"wrong": "The students''s books are on the desk.", "correct": "The students'' books are on the desk.", "note": "Çoğul, -s ile biten isimlerde sadece kesme işareti eklenir, ikinci bir s eklenmez."}]'::jsonb, 'published', 'manual', 6);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('7f3ac2be-ed37-476c-b7d4-b023da534a71', 'compound-nouns', (SELECT id FROM grammar_categories WHERE slug = 'articles-nouns'), 'en', 'Birleşik İsimler (Compound Nouns)', 'İki veya daha fazla kelimenin bir araya gelerek tek bir kavramı ifade ettiği birleşik isimlerde çoğul eki genellikle sadece son kelimeye eklenir.', 'b1', ARRAY['yds','toefl'], '- Birleşik isimler iki isim (bus stop), sıfat+isim (blackboard) veya fiil+isim (swimming pool) gibi farklı kombinasyonlarla oluşabilir.
- Birleşik isimler bitişik (bedroom), tireli (mother-in-law) veya ayrı yazılabilir (car park) -- kesin bir kural yoktur, ezber gerektirir.
- Çoğul eki normalde sadece SON kelimeye eklenir: "bus stops", "credit cards".
- Bazı istisnai birleşik isimlerde çoğul eki ilk kelimeye eklenir (özellikle "-in-law" kalıplarında): "mothers-in-law", "passers-by".', '[{"en": "We need to go to the bus stop.", "tr": "Otobüs durağına gitmemiz gerekiyor."}, {"en": "She bought a new pair of sunglasses.", "tr": "Yeni bir güneş gözlüğü aldı."}, {"en": "My mother-in-law is visiting us this weekend.", "tr": "Kayınvalidem bu hafta sonu bizi ziyaret ediyor."}]'::jsonb, '[{"wrong": "There are three bus stop near my house.", "correct": "There are three bus stops near my house.", "note": "Birleşik isimlerde çoğul eki normalde son kelimeye eklenir."}, {"wrong": "I have two mother-in-laws.", "correct": "I have two mothers-in-law.", "note": "''-in-law'' kalıplı birleşik isimlerde çoğul eki genellikle ilk kelimeye eklenir."}]'::jsonb, 'published', 'manual', 7);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('55e40395-7cc1-40ed-a25f-e09caf0754c7', 'irregular-plurals', (SELECT id FROM grammar_categories WHERE slug = 'articles-nouns'), 'en', 'Düzensiz Çoğul İsimler', 'Bazı isimler -s/-es kuralını izlemez; kök değişimi, aynı kalma veya tamamen farklı bir çoğul form alma gibi düzensiz yapılar gösterir.', 'a2', ARRAY['yds','yokdil'], '- Bazı isimler kök harflerini değiştirerek çoğul olur: man→men, woman→women, child→children, foot→feet, tooth→teeth, mouse→mice.
- Bazı isimler tekil ve çoğul formda AYNI kalır: sheep, fish, deer, series, species.
- -f/-fe ile biten bazı isimler çoğulda -ves alır: knife→knives, leaf→leaves, wife→wives (roof→roofs gibi istisnalar da vardır).
- Latin/Yunan kökenli bazı isimler kendi düzensiz çoğul formunu korur: crisis→crises, phenomenon→phenomena, cactus→cacti.', '[{"en": "There were three sheep in the field.", "tr": "Tarlada üç koyun vardı."}, {"en": "The children were playing in the garden.", "tr": "Çocuklar bahçede oynuyordu."}, {"en": "Scientists are studying several unusual phenomena.", "tr": "Bilim insanları birkaç sıra dışı olguyu inceliyor."}]'::jsonb, '[{"wrong": "I saw three sheeps in the field.", "correct": "I saw three sheep in the field.", "note": "sheep tekil ve çoğul formda aynı kalır, sonuna -s eklenmez."}, {"wrong": "She has two childs.", "correct": "She has two children.", "note": "child kelimesinin düzensiz çoğul formu children''dır, childs değildir."}]'::jsonb, 'published', 'manual', 8);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('6ca30eaa-9336-4046-a4ca-bd8e948c950b', 'good-well-difference', (SELECT id FROM grammar_categories WHERE slug = 'adjectives-adverbs'), 'en', 'good / well Farkı', 'good bir sıfattır ve isimleri niteler; well genellikle bir zarftır ve fiilleri niteler, ancak sağlık durumunu anlatırken sıfat olarak da kullanılabilir.', 'a2', ARRAY['yds','toefl'], '- **good** bir SIFATTIR, bir ismi (veya be fiilinden sonra özneyi) niteler: "This is a good book.", "The food was good."
- **well** genellikle bir ZARFTIR, bir fiilin nasıl yapıldığını anlatır: "She sings well."
- İstisna: well, SAĞLIK durumunu anlatırken (be/feel/look fiillerinden sonra) sıfat olarak kullanılır: "I don''t feel well today." (hasta hissediyorum)
- "do good" (iyilik yapmak) ile "do well" (başarılı olmak) farklı anlamlar taşır, karıştırılmamalıdır.', '[{"en": "He is a good doctor and he treats his patients well.", "tr": "O iyi bir doktor ve hastalarına iyi davranıyor."}, {"en": "She played really well in the final match.", "tr": "Final maçında gerçekten iyi oynadı."}, {"en": "I felt well after taking the medicine.", "tr": "İlacı aldıktan sonra iyi hissettim."}]'::jsonb, '[{"wrong": "He speaks English very good.", "correct": "He speaks English very well.", "note": "Fiili nitelemek için good değil zarf olan well kullanılmalıdır."}, {"wrong": "This soup tastes well.", "correct": "This soup tastes good.", "note": "taste gibi duyu fiillerinden sonra özneyi niteleyen sıfat (good) gelir, zarf (well) değil."}]'::jsonb, 'published', 'manual', 4);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('9e8ce75d-6e3f-47c8-8cc6-6b23dafa4454', 'quite-rather-fairly', (SELECT id FROM grammar_categories WHERE slug = 'adjectives-adverbs'), 'en', 'quite / rather / fairly / pretty Kullanımı', 'Bu dereceleme zarfları bir sıfat veya zarfın yoğunluğunu azaltır, ancak quite''in anlamı sıfatın derecelenebilir olup olmamasına göre değişir.', 'b2', ARRAY['yds','ielts'], '- **fairly**, **rather** ve **pretty** genellikle "oldukça" anlamında, orta derecede bir yoğunluk belirtir: "The exam was fairly difficult."
- **quite**, DERECELENEBİLİR sıfatlarla (gradable: good, big, interesting) "oldukça" anlamına gelir; DERECELENEMEYEN sıfatlarla (non-gradable: perfect, impossible, amazing) ise "tamamen" anlamına gelir.
- **rather**, beklenenden daha fazla veya olumsuz bir sürprizi vurgulamak için de kullanılabilir: "It''s rather cold today." (beklenenden soğuk)
- Bu zarflar sıfattan veya diğer zarftan hemen ÖNCE gelir: "quite expensive", "fairly quickly".', '[{"en": "The film was quite interesting, but not amazing.", "tr": "Film oldukça ilginçti, ama muhteşem değildi."}, {"en": "That''s quite impossible!", "tr": "Bu kesinlikle imkânsız!"}, {"en": "The hotel room was rather small.", "tr": "Otel odası beklediğimden küçüktü."}]'::jsonb, '[{"wrong": "This machine is very impossible to fix.", "correct": "This machine is quite impossible to fix.", "note": "impossible derecelenemeyen (non-gradable) bir sıfattır; very değil, ''tamamen'' anlamındaki quite ile kullanılır."}, {"wrong": "It''s quite cold today, I didn''t expect this at all.", "correct": "It''s rather cold today, I didn''t expect this at all.", "note": "Beklenmedik, biraz olumsuz bir durumu vurgularken quite yerine rather daha doğaldır."}]'::jsonb, 'published', 'manual', 5);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('c2b9f29d-8b8d-42ea-8cfe-aa5f4582eb1b', 'as-as-comparison', (SELECT id FROM grammar_categories WHERE slug = 'adjectives-adverbs'), 'en', 'as...as Kullanımı', 'İki şeyin eşit derecede olduğunu belirtmek için as + sıfat/zarf + as kullanılır; olumsuz formda not as...as ile eşitsizlik anlatılır.', 'b1', ARRAY['yds','toefl'], '- **as + sıfat/zarf + as** iki şeyin AYNI derecede olduğunu belirtir: "This book is as interesting as that one."
- **not as + sıfat/zarf + as** birinin diğerinden daha AZ olduğunu anlatır: "This exam wasn''t as difficult as the last one."
- **twice/three times as...as** gibi kalıplar oranı belirtmek için kullanılır: "This bag is twice as heavy as that one."
- as...as arasına sadece sıfat/zarfın YALIN hali gelir, karşılaştırma hali (-er) KULLANILMAZ: "as big as" (doğru), "as bigger as" (yanlış).', '[{"en": "She is as tall as her brother.", "tr": "Kardeşi kadar uzun."}, {"en": "This test wasn''t as easy as I expected.", "tr": "Bu sınav beklediğim kadar kolay değildi."}, {"en": "The new phone is twice as expensive as the old one.", "tr": "Yeni telefon eskisinden iki kat daha pahalı."}]'::jsonb, '[{"wrong": "This car is as faster as that one.", "correct": "This car is as fast as that one.", "note": "as...as arasına sıfatın yalın hali gelir, -er hali (faster) kullanılmaz."}, {"wrong": "He isn''t as tall than his father.", "correct": "He isn''t as tall as his father.", "note": "as...as yapısında than değil as kullanılır; than sadece -er karşılaştırmalarında kullanılır."}]'::jsonb, 'published', 'manual', 6);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('54c9fda7-a526-43ed-96d4-d4d8decba398', 'adjectives-ending-in-ly', (SELECT id FROM grammar_categories WHERE slug = 'adjectives-adverbs'), 'en', '-ly ile Biten Sıfatlar (friendly, lovely vb.)', '-ly eki genellikle zarf oluşturur, ancak friendly, lovely, lonely, silly gibi bazı kelimeler -ly ile bitmesine rağmen sıfattır, zarf değildir.', 'b2', ARRAY['yokdil','yds'], '- friendly, lovely, lonely, silly, ugly, likely, elderly gibi kelimeler -ly ile biter ama bunlar SIFATTIR, zarf değildir.
- Bu kelimeler bir ismi niteler veya be fiilinden sonra kullanılır: "a friendly dog", "She looks lonely."
- Bu sıfatları ZARF olarak kullanmak gerektiğinde genellikle "in a friendly way/manner" gibi bir kalıba başvurulur, çünkü "friendlily" gibi bir form doğal değildir.
- Tersine, early, daily, weekly gibi bazı kelimeler hem sıfat HEM zarf olarak kullanılabilir: "a daily routine" (sıfat), "I exercise daily" (zarf).', '[{"en": "Our neighbours are very friendly.", "tr": "Komşularımız çok arkadaş canlısı."}, {"en": "He greeted us in a friendly way.", "tr": "Bizi dostça karşıladı."}, {"en": "She felt lonely after moving to a new city.", "tr": "Yeni bir şehre taşındıktan sonra kendini yalnız hissetti."}]'::jsonb, '[{"wrong": "She smiled friendly at everyone.", "correct": "She smiled in a friendly way at everyone.", "note": "friendly bir sıfattır, zarf gibi doğrudan fiili nitelemek için kullanılamaz."}, {"wrong": "He is a lonely person, he lives lonely.", "correct": "He is a lonely person, he lives alone.", "note": "''yalnız yaşamak'' anlamı için lonely (sıfat) değil alone kullanılır."}]'::jsonb, 'published', 'manual', 7);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('187ecd47-a3c8-4658-ae7a-106a83f54b91', 'adverbs-of-manner-formation', (SELECT id FROM grammar_categories WHERE slug = 'adjectives-adverbs'), 'en', 'Tarz Zarfları (Adverbs of Manner) Yapımı', 'Tarz zarfları genellikle sıfata -ly eklenerek oluşturulur, ancak bazı sıfatların zarf hali düzensizdir veya sıfatla aynıdır.', 'a2', ARRAY['yds','yokdil'], '- Çoğu zarf, sıfata -ly eklenerek oluşturulur: quick→quickly, careful→carefully, slow→slowly.
- -y ile biten sıfatlarda -y, -ily olarak değişir: happy→happily, easy→easily.
- **good**''un zarf hali **well**''dir (düzensiz); **fast**, **hard**, **late** gibi bazı kelimeler hem sıfat hem zarf olarak AYNI şekilde kullanılır: "a fast car" (sıfat), "He drives fast." (zarf).
- **hardly** ve **lately** dikkat gerektirir: hardly "zar zor/neredeyse hiç" anlamına gelir (hard''ın zarf hali DEĞİLDİR), lately ise "son zamanlarda" anlamına gelir.', '[{"en": "He solved the problem quickly and carefully.", "tr": "Problemi hızlı ve dikkatli bir şekilde çözdü."}, {"en": "She works hard every day.", "tr": "Her gün sıkı çalışıyor."}, {"en": "I''ve hardly slept this week.", "tr": "Bu hafta neredeyse hiç uyumadım."}]'::jsonb, '[{"wrong": "He drives very fastly.", "correct": "He drives very fast.", "note": "fast hem sıfat hem zarf olarak aynı şekilde kullanılır, ''fastly'' diye bir kelime yoktur."}, {"wrong": "I hardly worked today, so I''m very tired.", "correct": "I worked hard today, so I''m very tired.", "note": "''çok/sıkı çalışmak'' anlamı için hard kullanılır; hardly ''neredeyse hiç'' anlamına gelir ve cümlenin anlamını tersine çevirir."}]'::jsonb, 'published', 'manual', 8);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('8653af61-23f4-463e-9e80-5ebf3c914ddf', 'modals-permission-requests', (SELECT id FROM grammar_categories WHERE slug = 'modals'), 'en', 'İzin ve Rica Modalları (can/could/may)', 'İzin istemek veya vermek, ve rica etmek için can, could ve may kullanılır; could ve may daha resmi/kibardır.', 'a2', ARRAY['yds','toefl'], '- **can** günlük, samimi durumlarda izin istemek/vermek için kullanılır: "Can I open the window?"
- **could** ve **may**, can''e göre daha KİBAR ve resmi bir izin isteme biçimidir: "Could I ask you something?", "May I come in?"
- Rica ederken de benzer yapı kullanılır: "Could you help me with this?", "Can you pass the salt?"
- **may** aynı zamanda resmi yazışmalarda/kurumsal bağlamlarda izin vermek için de kullanılır: "Students may leave the room after the exam."', '[{"en": "Could I borrow your pen for a moment?", "tr": "Kalemini bir dakikalığına ödünç alabilir miyim?"}, {"en": "May I ask you a question?", "tr": "Size bir soru sorabilir miyim?"}, {"en": "Can you open the door for me, please?", "tr": "Lütfen benim için kapıyı açar mısın?"}]'::jsonb, '[{"wrong": "Can I to use your phone?", "correct": "Can I use your phone?", "note": "Modal fiillerden sonra to olmadan fiilin yalın hali gelir."}, {"wrong": "May you help me with my bags?", "correct": "Could you help me with my bags?", "note": "Rica ederken may değil could/can kullanılır; may genellikle izin istemek için kullanılır."}]'::jsonb, 'published', 'manual', 6);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('3dd6f31e-6ccc-4be8-aed5-d71a051ca21c', 'must-vs-have-to', (SELECT id FROM grammar_categories WHERE slug = 'modals'), 'en', 'must / have to Farkı', 'must konuşanın kendi görüşüne dayanan bir zorunluluğu, have to ise dışarıdan (kural, otorite) gelen bir zorunluluğu anlatır.', 'b1', ARRAY['yds','yokdil'], '- **must**, konuşan kişinin KENDİ değerlendirmesine/görüşüne dayanan bir zorunluluğu ifade eder: "I must call my mother." (kendi kararım)
- **have to**, dışarıdan gelen bir kural, yasa veya otoriteye dayanan zorunluluğu ifade eder: "I have to wear a uniform at work." (şirket kuralı)
- Olumsuz formda anlam TAMAMEN değişir: **mustn''t** yasaklama anlamı taşır, **don''t have to** ise zorunluluğun olmadığını anlatır -- bkz. needn''t/mustn''t.
- must''ın geçmiş zaman formu yoktur; geçmişte zorunluluk anlatmak için had to kullanılır.', '[{"en": "You must see this movie, it''s amazing!", "tr": "Bu filmi kesinlikle görmelisin, harika!"}, {"en": "I have to submit this report by Friday.", "tr": "Bu raporu cuma gününe kadar teslim etmem gerekiyor."}, {"en": "We had to wait two hours at the airport.", "tr": "Havaalanında iki saat beklemek zorunda kaldık."}]'::jsonb, '[{"wrong": "Yesterday I must go to the dentist.", "correct": "Yesterday I had to go to the dentist.", "note": "must''ın geçmiş zaman formu yoktur, geçmişte zorunluluk için had to kullanılır."}, {"wrong": "At school, we must wear a uniform, it''s the rule.", "correct": "At school, we have to wear a uniform, it''s the rule.", "note": "Dışarıdan gelen bir kurala dayanan zorunlulukta genellikle have to tercih edilir."}]'::jsonb, 'published', 'manual', 7);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('161dbec4-2dcc-4280-b97f-d81f5e1c019b', 'neednt-vs-mustnt', (SELECT id FROM grammar_categories WHERE slug = 'modals'), 'en', 'needn''t / mustn''t Farkı', 'needn''t (don''t need to) bir şeyin yapılmasının gerekmediğini, mustn''t ise bir şeyin yasak olduğunu, kesinlikle yapılmaması gerektiğini anlatır.', 'b2', ARRAY['yds','ielts'], '- **needn''t / don''t need to**, bir eylemin yapılmasının gerekli OLMADIĞINI anlatır -- yapılsa da olur, yapılmasa da: "You needn''t bring anything, we have everything."
- **mustn''t**, bir eylemin kesinlikle YAPILMAMASI gerektiğini, yasak olduğunu anlatır: "You mustn''t smoke in here."
- Bu iki yapı birbirinin zıttı DEĞİLDİR: needn''t''ün zıttı must/have to, mustn''t''ın zıttı ise can (izin).
- needn''t have + V3 yapısı, GEÇMİŞTE gereksiz yere yapılmış bir eylemi anlatır: "You needn''t have bought a gift." (hediye almana gerek yoktu ama aldın.)', '[{"en": "You needn''t wait for me, I''ll catch up later.", "tr": "Beni beklemene gerek yok, sonra yetişirim."}, {"en": "You mustn''t tell anyone about this secret.", "tr": "Bu sırrı kimseye söylememelisin."}, {"en": "She needn''t have worried, everything went fine.", "tr": "Endişelenmesine gerek yoktu, her şey yolunda gitti."}]'::jsonb, '[{"wrong": "You mustn''t come if you don''t want to, it''s not necessary.", "correct": "You needn''t come if you don''t want to, it''s not necessary.", "note": "Gereklilik olmadığı anlatılıyor, yasaklama değil; bu yüzden mustn''t değil needn''t kullanılır."}, {"wrong": "You needn''t smoke here, it''s forbidden.", "correct": "You mustn''t smoke here, it''s forbidden.", "note": "Kesin bir yasak söz konusu olduğu için needn''t değil mustn''t kullanılmalıdır."}]'::jsonb, 'published', 'manual', 8);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('2c520304-0527-40ab-bf4f-df1f74570568', 'had-better-would-rather', (SELECT id FROM grammar_categories WHERE slug = 'modals'), 'en', 'had better / would rather Kullanımı', 'had better bir tavsiye veya uyarıyı, olumsuz sonuç tehlikesiyle birlikte anlatır; would rather bir tercihi ifade eder.', 'b2', ARRAY['yds','toefl'], '- **had better + fiil (yalın)**, güçlü bir tavsiye/uyarı anlatır; yapılmazsa olumsuz bir sonuç doğabileceğini ima eder: "You''d better hurry, or you''ll miss the bus."
- **had better**''ın olumsuz formu "had better not"tur (didn''t had better DEĞİL): "You''d better not be late."
- **would rather + fiil (yalın)**, iki seçenek arasında bir TERCİHİ ifade eder: "I''d rather stay home than go out tonight."
- İki farklı özne varsa would rather''dan sonra fiil değil past simple bir cümlecik gelir: "I''d rather you called me tomorrow."', '[{"en": "You''d better take an umbrella, it looks like rain.", "tr": "Yanına şemsiye alsan iyi olur, yağmur yağacak gibi görünüyor."}, {"en": "I''d rather have tea than coffee.", "tr": "Kahve yerine çay içmeyi tercih ederim."}, {"en": "You''d better not forget your passport.", "tr": "Pasaportunu unutmasan iyi olur."}]'::jsonb, '[{"wrong": "You better hurry up, the train is leaving.", "correct": "You''d better hurry up, the train is leaving.", "note": "had better yapısında had (genellikle ''d olarak kısaltılır) atlanmamalıdır."}, {"wrong": "I would rather to stay home tonight.", "correct": "I would rather stay home tonight.", "note": "would rather''dan sonra to almadan fiilin yalın hali gelir."}]'::jsonb, 'published', 'manual', 9);

-- new exam_questions
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('4c3abd62-faa3-44b2-b4ae-9aeb49bbd0b6', 'yds', 'I don''t like ------- coffee in the morning, but I love it in the afternoon.', '[{"id": "a", "text": "the"}, {"id": "b", "text": "a"}, {"id": "c", "text": "(artikel yok)"}, {"id": "d", "text": "an"}]'::jsonb, 'c', 'Genel bir kategoriden (kahve) bahsedilirken artikel kullanılmaz.', '[{"word": "artikelsiz genel isim", "example": "Music makes me happy.", "meaning": "genel bir kategoriden bahsetme"}]'::jsonb, 'medium', true, 'en', 'the-specific-vs-general', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('6b9601a2-37c8-4ecc-a9f2-7f15bcfc548e', 'yokdil', 'I bought a laptop yesterday. ------- laptop was very expensive.', '[{"id": "a", "text": "A"}, {"id": "b", "text": "The"}, {"id": "c", "text": "(artikel yok)"}, {"id": "d", "text": "An"}]'::jsonb, 'b', 'İkinci kez bahsedilen, artık bilinen bir isim için the kullanılır.', '[{"word": "the (ikinci bahsediş)", "example": "I saw a cat. The cat was black.", "meaning": "daha önce bahsedilmiş, bilinen isim"}]'::jsonb, 'medium', true, 'en', 'the-specific-vs-general', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('84440c6c-8d0c-4151-b147-6aaa1525c101', 'yokdil', 'The news about the merger ------- quite surprising to everyone.', '[{"id": "a", "text": "is"}, {"id": "b", "text": "are"}, {"id": "c", "text": "were"}, {"id": "d", "text": "have been"}]'::jsonb, 'a', 'news sayılamayan bir isimdir ve her zaman tekil fiil alır.', '[{"word": "news (tekil)", "example": "The news is on TV now.", "meaning": "sayılamayan, hep tekil fiil alan isim"}]'::jsonb, 'medium', true, 'en', 'subject-verb-agreement-nouns', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('d7a9d4f1-8793-4ed6-8bac-4b186aa63731', 'toefl', 'The police ------- still investigating the robbery downtown.', '[{"id": "a", "text": "is"}, {"id": "b", "text": "are"}, {"id": "c", "text": "was"}, {"id": "d", "text": "has been"}]'::jsonb, 'b', 'police her zaman çoğul fiil alan bir isimdir.', '[{"word": "police (hep çoğul)", "example": "The police are on their way.", "meaning": "tekil formda olsa da hep çoğul fiil alır"}]'::jsonb, 'medium', true, 'en', 'subject-verb-agreement-nouns', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('ac868756-dbce-4775-8bc3-197479c4a1fd', 'yds', 'This is my ------- car; he just bought it last week.', '[{"id": "a", "text": "brother"}, {"id": "b", "text": "brother''s"}, {"id": "c", "text": "brothers"}, {"id": "d", "text": "of brother"}]'::jsonb, 'b', 'Canlı bir varlık (kardeş) için iyelik ''s kullanılır.', '[{"word": "''s (canlı varlık)", "example": "my brother''s car", "meaning": "insan/hayvan için tercih edilen iyelik yapısı"}]'::jsonb, 'easy', true, 'en', 'possessive-s-vs-of', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('b58faa34-9ea8-4421-b57f-f09f37538bb4', 'yokdil', 'The ------- was covered with snow all winter.', '[{"id": "a", "text": "mountain''s top"}, {"id": "b", "text": "top of the mountain"}, {"id": "c", "text": "top''s mountain"}, {"id": "d", "text": "mountain top''s"}]'::jsonb, 'b', 'Cansız bir nesne (dağ) için genellikle of yapısı tercih edilir.', '[{"word": "of (cansız nesne)", "example": "the top of the mountain", "meaning": "cansız nesneler için tercih edilen yapı"}]'::jsonb, 'medium', true, 'en', 'possessive-s-vs-of', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('ca49099a-82a8-4089-bbbe-00ab154eb036', 'toefl', 'There are two ------- right next to the shopping mall.', '[{"id": "a", "text": "car park"}, {"id": "b", "text": "car parks"}, {"id": "c", "text": "cars park"}, {"id": "d", "text": "car''s parks"}]'::jsonb, 'b', 'Birleşik isimlerde çoğul eki normalde son kelimeye eklenir.', '[{"word": "çoğul + birleşik isim", "example": "bus stops", "meaning": "çoğul eki son kelimeye eklenir"}]'::jsonb, 'easy', true, 'en', 'compound-nouns', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('fcbd5582-623a-432d-9618-211349470497', 'yds', 'My ------- are coming to visit us this weekend.', '[{"id": "a", "text": "mother-in-laws"}, {"id": "b", "text": "mothers-in-law"}, {"id": "c", "text": "mother-in-law''s"}, {"id": "d", "text": "mothers-in-laws"}]'::jsonb, 'b', '''-in-law'' kalıplı birleşik isimlerde çoğul eki genellikle ilk kelimeye eklenir.', '[{"word": "mothers-in-law (istisna)", "example": "passers-by", "meaning": "çoğul ekinin ilk kelimeye eklendiği istisnai birleşik isimler"}]'::jsonb, 'medium', true, 'en', 'compound-nouns', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('602c19d5-9c72-4849-86e8-76a2ede9d8d6', 'yokdil', 'There were about fifty ------- grazing in the field.', '[{"id": "a", "text": "sheeps"}, {"id": "b", "text": "sheep"}, {"id": "c", "text": "a sheep"}, {"id": "d", "text": "sheep''s"}]'::jsonb, 'b', 'sheep tekil ve çoğul formda aynı kalır.', '[{"word": "sheep (değişmeyen çoğul)", "example": "fish, deer, sheep", "meaning": "tekil ve çoğulu aynı olan isimler"}]'::jsonb, 'easy', true, 'en', 'irregular-plurals', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('3f65ad96-ec47-4ba3-b0a4-8d52587d9272', 'ielts', 'Scientists are studying several unusual ------- related to climate change.', '[{"id": "a", "text": "phenomenons"}, {"id": "b", "text": "phenomena"}, {"id": "c", "text": "phenomenas"}, {"id": "d", "text": "phenomenon''s"}]'::jsonb, 'b', 'phenomenon''un düzensiz çoğul formu phenomena''dır.', '[{"word": "phenomenon → phenomena", "example": "crisis → crises", "meaning": "Latin/Yunan kökenli düzensiz çoğullar"}]'::jsonb, 'medium', true, 'en', 'irregular-plurals', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('70aaa0eb-1ad7-4304-8baa-29f108c6348c', 'yds', 'She sings very ------- ; everyone loves her voice.', '[{"id": "a", "text": "good"}, {"id": "b", "text": "well"}, {"id": "c", "text": "best"}, {"id": "d", "text": "better"}]'::jsonb, 'b', 'sings fiilini nitelemek için sıfat (good) değil zarf (well) kullanılır.', '[{"word": "well (zarf)", "example": "She sings well.", "meaning": "fiili niteleyen zarf"}]'::jsonb, 'easy', true, 'en', 'good-well-difference', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('83f28a98-e4cb-49a2-b9cc-6cafaf1a07bd', 'toefl', 'I don''t feel ------- today, I think I have a fever.', '[{"id": "a", "text": "good"}, {"id": "b", "text": "well"}, {"id": "c", "text": "nicely"}, {"id": "d", "text": "better"}]'::jsonb, 'b', 'Sağlık durumu anlatılırken well, feel fiilinden sonra sıfat olarak kullanılır.', '[{"word": "feel well (sağlık)", "example": "I don''t feel well.", "meaning": "sağlık durumunu anlatan sıfat kullanımı"}]'::jsonb, 'medium', true, 'en', 'good-well-difference', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('7663a544-a2d7-4bc1-b968-f8e30a4ee718', 'yokdil', 'This machine is ------- impossible to repair; we should just buy a new one.', '[{"id": "a", "text": "very"}, {"id": "b", "text": "quite"}, {"id": "c", "text": "so"}, {"id": "d", "text": "too"}]'::jsonb, 'b', 'impossible derecelenemeyen bir sıfattır; bu bağlamda quite ''tamamen'' anlamına gelir.', '[{"word": "quite + non-gradable", "example": "quite impossible", "meaning": "derecelenemeyen sıfatlarla ''tamamen'' anlamı"}]'::jsonb, 'medium', true, 'en', 'quite-rather-fairly', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('55bad0c4-521d-4e73-99c4-23bdc4441cb8', 'ielts', 'It''s ------- cold today, I didn''t bring a coat with me.', '[{"id": "a", "text": "quite"}, {"id": "b", "text": "rather"}, {"id": "c", "text": "so"}, {"id": "d", "text": "too"}]'::jsonb, 'b', 'Beklenmedik, olumsuz bir sürprizi vurgularken rather daha doğaldır.', '[{"word": "rather (beklenmedik sürpriz)", "example": "It''s rather expensive.", "meaning": "beklenenden fazla/olumsuz bir durumu vurgular"}]'::jsonb, 'medium', true, 'en', 'quite-rather-fairly', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('2f5238e7-e8ba-49ee-bed9-b21d20e86fcb', 'yds', 'This laptop is ------- that one, but it''s much cheaper.', '[{"id": "a", "text": "as fast as"}, {"id": "b", "text": "as faster as"}, {"id": "c", "text": "faster as"}, {"id": "d", "text": "so fast"}]'::jsonb, 'a', 'Eşitlik karşılaştırmasında as + yalın sıfat + as kalıbı kullanılır.', '[{"word": "as fast as (eşitlik)", "example": "as good as", "meaning": "iki şeyin eşit derecede olduğunu belirtir"}]'::jsonb, 'medium', true, 'en', 'as-as-comparison', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('4c8bf513-b54a-4dbc-8fa9-d235117928f1', 'toefl', 'He isn''t as tall ------- his older brother.', '[{"id": "a", "text": "than"}, {"id": "b", "text": "as"}, {"id": "c", "text": "that"}, {"id": "d", "text": "like"}]'::jsonb, 'b', 'as...as yapısında than değil as kullanılır.', '[{"word": "not as...as", "example": "not as difficult as", "meaning": "eşitsizlik/daha az olma durumu"}]'::jsonb, 'easy', true, 'en', 'as-as-comparison', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('67c8df28-5180-4c4e-a1b8-67aa364cdd8c', 'yokdil', 'The staff at this hotel are extremely -------.', '[{"id": "a", "text": "friendly"}, {"id": "b", "text": "friendlily"}, {"id": "c", "text": "friend"}, {"id": "d", "text": "friendliness"}]'::jsonb, 'a', 'friendly bir sıfattır, ''friendlily'' diye bir kelime yoktur.', '[{"word": "friendly (sıfat)", "example": "a friendly smile", "meaning": "-ly ile biten ama sıfat olan kelime"}]'::jsonb, 'hard', true, 'en', 'adjectives-ending-in-ly', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('6b374c94-5694-4d3a-ba9b-f53931edc9d0', 'yds', 'After the divorce, he felt very -------.', '[{"id": "a", "text": "lonely"}, {"id": "b", "text": "lonelily"}, {"id": "c", "text": "alonely"}, {"id": "d", "text": "lone"}]'::jsonb, 'a', 'lonely -ly ile bitmesine rağmen bir sıfattır.', '[{"word": "lonely (sıfat)", "example": "a lonely house", "meaning": "-ly ile biten ama sıfat olan kelime"}]'::jsonb, 'medium', true, 'en', 'adjectives-ending-in-ly', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('509f6443-fcc7-4ba7-a105-120fcc3c9b99', 'ielts', 'He has been working ------- all week, so he deserves a good rest.', '[{"id": "a", "text": "hard"}, {"id": "b", "text": "hardly"}, {"id": "c", "text": "harder"}, {"id": "d", "text": "hardness"}]'::jsonb, 'a', '''çok/sıkı çalışmak'' anlamı için hard kullanılır; hardly ''neredeyse hiç'' anlamına gelir.', '[{"word": "work hard", "example": "She studies hard.", "meaning": "çok/sıkı çalışmak"}]'::jsonb, 'medium', true, 'en', 'adverbs-of-manner-formation', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('dc8b6429-5d42-454e-8298-f7064a91a8e8', 'yds', 'The car drives very -------, it''s really powerful.', '[{"id": "a", "text": "fast"}, {"id": "b", "text": "fastly"}, {"id": "c", "text": "faster"}, {"id": "d", "text": "fastness"}]'::jsonb, 'a', 'fast hem sıfat hem zarf olarak aynı şekilde kullanılır, ''fastly'' diye bir kelime yoktur.', '[{"word": "fast (sıfat=zarf)", "example": "a fast car / drive fast", "meaning": "hem sıfat hem zarf olarak aynı form"}]'::jsonb, 'easy', true, 'en', 'adverbs-of-manner-formation', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('69fe3869-5490-440a-bf92-a88c6815eda2', 'yds', '------- I use your phone for a minute? Mine is out of battery.', '[{"id": "a", "text": "Must"}, {"id": "b", "text": "Could"}, {"id": "c", "text": "Should"}, {"id": "d", "text": "Need"}]'::jsonb, 'b', 'İzin isterken could kibar bir kullanımdır.', '[{"word": "could (kibar izin isteme)", "example": "Could I sit here?", "meaning": "can''e göre daha kibar izin isteme"}]'::jsonb, 'easy', true, 'en', 'modals-permission-requests', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('983c5900-06a3-41f5-bfaf-e1b23c1de225', 'toefl', '------- you help me carry these boxes upstairs, please?', '[{"id": "a", "text": "May"}, {"id": "b", "text": "Could"}, {"id": "c", "text": "Should"}, {"id": "d", "text": "Must"}]'::jsonb, 'b', 'Rica ederken could/can kullanılır; may genellikle izin istemek için tercih edilir.', '[{"word": "could you...? (rica)", "example": "Could you pass the salt?", "meaning": "kibar bir ricada bulunma kalıbı"}]'::jsonb, 'medium', true, 'en', 'modals-permission-requests', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('9e6cf3c3-6e74-43e2-8589-0cefb07b802e', 'yds', 'Yesterday, I ------- go to the dentist because of a terrible toothache.', '[{"id": "a", "text": "must"}, {"id": "b", "text": "had to"}, {"id": "c", "text": "have to"}, {"id": "d", "text": "must have"}]'::jsonb, 'b', 'must''ın geçmiş zaman formu yoktur, geçmişte zorunluluk için had to kullanılır.', '[{"word": "had to (geçmiş zorunluluk)", "example": "I had to leave early.", "meaning": "must''ın geçmiş karşılığı"}]'::jsonb, 'medium', true, 'en', 'must-vs-have-to', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('334fd8e0-0680-4ccd-b1ff-aef3321cebbf', 'yokdil', 'I really ------- call my grandmother today, I miss her so much.', '[{"id": "a", "text": "have to"}, {"id": "b", "text": "must"}, {"id": "c", "text": "had"}, {"id": "d", "text": "has to"}]'::jsonb, 'b', 'Kişisel görüşe/isteğe dayanan zorunluluk must ile ifade edilir.', '[{"word": "must (kişisel zorunluluk)", "example": "I must call her.", "meaning": "konuşanın kendi görüşüne dayanan zorunluluk"}]'::jsonb, 'hard', true, 'en', 'must-vs-have-to', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('e38e489f-ad9f-4811-b32d-57315ae5fd35', 'ielts', 'You ------- worry about the exam, you''ve prepared really well.', '[{"id": "a", "text": "mustn''t"}, {"id": "b", "text": "needn''t"}, {"id": "c", "text": "can''t"}, {"id": "d", "text": "haven''t"}]'::jsonb, 'b', 'Gereklilik olmadığı anlatıldığı için needn''t kullanılır.', '[{"word": "needn''t (gereksiz)", "example": "You needn''t hurry.", "meaning": "bir şeyin yapılmasının gerekmediğini anlatır"}]'::jsonb, 'medium', true, 'en', 'neednt-vs-mustnt', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('48c49e31-8eb1-4810-9d88-db60abe3cb12', 'yds', 'You ------- reveal this information to anyone, it''s strictly confidential.', '[{"id": "a", "text": "needn''t"}, {"id": "b", "text": "mustn''t"}, {"id": "c", "text": "don''t have to"}, {"id": "d", "text": "may"}]'::jsonb, 'b', 'Kesin bir yasak söz konusu olduğu için mustn''t kullanılmalıdır.', '[{"word": "mustn''t (yasak)", "example": "You mustn''t smoke here.", "meaning": "kesinlikle yapılmaması gereken bir şeyi anlatır"}]'::jsonb, 'medium', true, 'en', 'neednt-vs-mustnt', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('2c5c0808-efa9-4e85-adf9-9a38b781eef3', 'toefl', 'You ------- take an umbrella, it looks like it''s going to rain.', '[{"id": "a", "text": "had better"}, {"id": "b", "text": "would rather"}, {"id": "c", "text": "must to"}, {"id": "d", "text": "should to"}]'::jsonb, 'a', 'Olumsuz bir sonuç riskiyle birlikte güçlü bir tavsiye verildiği için had better kullanılır.', '[{"word": "had better (güçlü tavsiye)", "example": "You''d better see a doctor.", "meaning": "yapılmazsa olumsuz sonuç doğabilecek tavsiye"}]'::jsonb, 'medium', true, 'en', 'had-better-would-rather', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('5c5fb5f1-b15a-4ee9-a6dd-b97667ffd89d', 'yds', 'I ------- stay home tonight than go to the party.', '[{"id": "a", "text": "had better"}, {"id": "b", "text": "would rather"}, {"id": "c", "text": "must"}, {"id": "d", "text": "should"}]'::jsonb, 'b', 'İki seçenek arasında bir tercih belirtildiği için would rather kullanılır.', '[{"word": "would rather...than", "example": "I''d rather walk than drive.", "meaning": "iki seçenek arasında tercih belirtir"}]'::jsonb, 'easy', true, 'en', 'had-better-would-rather', 'system', 'approved');
