-- 033_grammar_reference_wave4.sql
--
-- Gramer Rehberi 4. dalga genisleme -- Cambridge "English Grammar in Use"
-- (Murphy, 5. baski) icerigine paralel, kitaptaki 3 bolum: -ing ve to
-- (bolum 9), Pronouns and Determiners (bolum 11), Relative Clauses
-- (bolum 12).
--
-- ICERIK KAYNAGI VE TELIF NOTU: Bu migration'daki grammar_topics kayitlarinin
-- SADECE unite/konu basliklari kitaptaki standart dilbilgisi terminolojisinden
-- esinlenerek adlandirilmistir -- bunlar telife konu olmayan genel gramer
-- kavramlaridir. Kural aciklamalari (rule_content_md), ornek cumleler
-- (example_sentences), sik hatalar (common_mistakes) ve tum exam_questions
-- sorulari %100 ozgun olarak yazilmistir. Kitaptan hicbir cumle, ornek veya
-- alistirma birebir kopyalanmamistir.
--
-- Icerik: yeni grammar_categories yok (mevcut ing-to-infinitive,
-- pronouns-determiners, clauses kategorilerine eklendi), 12 yeni
-- grammar_topics (ing-to-infinitive'e +5, pronouns-determiners'a +4,
-- clauses'a +3), 24 yeni exam_questions (her yeni konu icin 2 soru,
-- topic_tag = grammar_topics.slug ile birebir eslesir).
--
-- Bu SQL, Supabase MCP apply_migration araciyla proje mrxeuxscyztpiuagsumh
-- uzerinde 2 parcada (topics, questions) zaten uygulanmistir; bu dosya repo
-- gecmisi icin ayniyla tekrar eder.

-- new grammar_topics
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('2145f46f-fdf9-4caa-b359-a338c7421112', 'verb-object-infinitive', (SELECT id FROM grammar_categories WHERE slug = 'ing-to-infinitive'), 'en', 'Fiil + Nesne + to-infinitive Yapısı', 'want, tell, ask, would like, expect gibi fiillerden sonra nesne + to-infinitive kalıbı kullanılır.', 'b1', ARRAY['yds','yokdil'], '- want, would like, expect, need gibi fiillerden sonra bir nesne (kişi) ve ardından to-infinitive gelir: "I want you to help me."
- tell, ask, advise, warn, remind, order gibi fiillerde de aynı yapı kullanılır: "She told him to wait."
- Bu fiillerden sonra that-cümleciği DEĞİL, nesne + to-infinitive kullanılmalıdır: "I want that you help me" YANLIŞ.
- make ve let fiilleri İSTİSNADIR: bunlardan sonra to OLMADAN bare infinitive kullanılır: "She made him apologize.", "Let me help you."', '[{"en": "I want you to call me tonight.", "tr": "Bu gece beni aramanı istiyorum."}, {"en": "The teacher told the students to be quiet.", "tr": "Öğretmen öğrencilere sessiz olmalarını söyledi."}, {"en": "My parents let me stay out late.", "tr": "Ailem geç saatlere kadar dışarıda kalmama izin verdi."}]'::jsonb, '[{"wrong": "I want that you come with us.", "correct": "I want you to come with us.", "note": "want fiilinden sonra that-cümleciği değil nesne+to-infinitive kullanılır."}, {"wrong": "She made him to apologize.", "correct": "She made him apologize.", "note": "make fiilinden sonra to olmadan bare infinitive kullanılır."}]'::jsonb, 'published', 'manual', 4);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('e6f2e325-b668-4577-9860-75c7a29b1081', 'adjective-preposition-ing', (SELECT id FROM grammar_categories WHERE slug = 'ing-to-infinitive'), 'en', 'Sıfat + Edat + -ing Yapısı', 'Birçok sıfattan sonra sabit bir edat gelir ve bu edattan sonra fiil -ing (gerund) formunda kullanılır.', 'b1', ARRAY['yds','yokdil','toefl'], '- İngilizce''de birçok sıfat belirli bir edatla birlikte kalıplaşmıştır: interested in, afraid of, good at, tired of, worried about, keen on.
- Bu sıfat+edat kalıplarından sonra bir fiil geliyorsa, fiil MUTLAKA -ing (gerund) formunda kullanılır, çünkü edattan sonra fiil her zaman -ing alır: "I''m interested in learning Spanish."
- to-infinitive bu yapıda kullanılmaz; sınav İngilizcesinde "sıfat + edat + -ing" kalıbı doğru kabul edilir.
- Sıfat+edat kalıpları ezber gerektirir, kesin bir kural yoktur; en sık kullanılanları öğrenmek önemlidir.', '[{"en": "She''s really good at solving puzzles.", "tr": "Bulmaca çözmekte gerçekten iyidir."}, {"en": "I''m tired of waiting for the bus.", "tr": "Otobüsü beklemekten yoruldum."}, {"en": "He''s worried about losing his job.", "tr": "İşini kaybetmekten endişeleniyor."}]'::jsonb, '[{"wrong": "I''m interested in learn new languages.", "correct": "I''m interested in learning new languages.", "note": "edattan sonra fiil mutlaka -ing formunda kullanılır."}, {"wrong": "She''s afraid to spiders.", "correct": "She''s afraid of spiders.", "note": "afraid sıfatı \"of\" edatıyla kullanılır, \"to\" ile değil."}]'::jsonb, 'published', 'manual', 5);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('422569b8-3c9f-4d90-aae3-ea79542596af', 'see-someone-do-vs-doing', (SELECT id FROM grammar_categories WHERE slug = 'ing-to-infinitive'), 'en', 'Algı Fiilleri: see/hear/watch + Nesne + do / doing Farkı', 'see, hear, watch gibi algı fiillerinden sonra nesne+bare infinitive eylemin tamamını, nesne+-ing ise eylemin sürerken yakalandığını ifade eder.', 'b2', ARRAY['yds','yokdil','toefl'], '- see, hear, watch, notice, feel gibi algı (perception) fiillerinden sonra nesne + BARE infinitive (to''suz) kullanıldığında, eylemin BAŞTAN SONA tamamlandığı/tamamının görüldüğü anlatılır: "I saw him cross the street."
- Aynı fiillerden sonra nesne + -ing kullanıldığında, eylemin SÜRERKEN, yarıda yakalandığı anlatılır: "I saw him crossing the street." (yol ortasındayken gördüm)
- Uzun süren veya tekrar eden eylemlerde genellikle -ing formu tercih edilir: "I heard her singing all afternoon."
- to-infinitive bu yapıda aktif çatıda kullanılmaz; sadece edilgen çatıda geri döner: "He was seen to leave the building."', '[{"en": "I saw the thief steal the bag and run away.", "tr": "Hırsızın çantayı çalıp kaçtığını gördüm."}, {"en": "I saw a man standing at the corner when I arrived.", "tr": "Vardığımda köşede duran bir adam gördüm."}, {"en": "We heard the dog barking all night.", "tr": "Köpeğin bütün gece havladığını duyduk."}]'::jsonb, '[{"wrong": "I saw him to fall off his bike.", "correct": "I saw him fall off his bike.", "note": "aktif yapıda algı fiillerinden sonra to-infinitive değil bare infinitive kullanılır."}, {"wrong": "I saw him falling off his bike, breaking his arm, getting up and walking away as one complete sequence.", "correct": "I saw him fall off his bike, break his arm, get up and walk away.", "note": "eylemin tamamı baştan sona anlatılıyorsa bare infinitive, sadece süren bir an anlatılıyorsa -ing kullanılmalıdır."}]'::jsonb, 'published', 'manual', 6);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('866ebe5b-a2ab-4b0c-af28-41118423441a', 'gerund-as-subject-object', (SELECT id FROM grammar_categories WHERE slug = 'ing-to-infinitive'), 'en', 'Özne ve Nesne Olarak -ing (Gerund)', '-ing formu bir cümlede özne veya nesne olarak isim gibi kullanılabilir; enjoy, avoid, mind gibi fiillerden sonra sadece -ing kullanılır.', 'a2', ARRAY['yds','yokdil'], '- -ing formu (gerund) bir cümlede tıpkı bir isim gibi ÖZNE olarak kullanılabilir: "Swimming is good exercise."
- -ing formu edat (preposition) sonrasında her zaman NESNE olarak kullanılır: "She is good at cooking.", "Thank you for helping me."
- to-infinitive de bazen özne olarak kullanılabilir ("To swim every day is good exercise.") ama bu yapı daha resmi/az kullanılır; günlük ve sınav İngilizcesinde -ing tercih edilir.
- enjoy, avoid, mind, finish, suggest, admit, deny gibi fiillerden sonra nesne olarak SADECE -ing kullanılır, to-infinitive kullanılmaz: "I enjoy reading."', '[{"en": "Learning a new language takes time and patience.", "tr": "Yeni bir dil öğrenmek zaman ve sabır gerektirir."}, {"en": "I really enjoy cooking for my friends.", "tr": "Arkadaşlarım için yemek pişirmekten gerçekten keyif alıyorum."}, {"en": "Would you mind closing the window?", "tr": "Pencereyi kapatır mısınız?"}]'::jsonb, '[{"wrong": "I enjoy to travel to new places.", "correct": "I enjoy traveling to new places.", "note": "enjoy fiilinden sonra sadece -ing kullanılır, to-infinitive kullanılmaz."}, {"wrong": "Smoke is bad for your health.", "correct": "Smoking is bad for your health.", "note": "bir eylemi özne olarak isimleştirmek için -ing (gerund) kullanılır, fiilin yalın hali değil."}]'::jsonb, 'published', 'manual', 7);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('63c140b7-ee63-422a-82ea-be86da121f39', 'verb-ing-infinitive-meaning-change', (SELECT id FROM grammar_categories WHERE slug = 'ing-to-infinitive'), 'en', 'remember/stop/try + -ing / to-infinitive: Anlam Değişimi', 'remember, stop, try gibi bazı fiillerden sonra -ing veya to-infinitive kullanılması cümlenin anlamını tamamen değiştirir.', 'b2', ARRAY['yds','yokdil','toefl'], '- remember + -ing: geçmişte yapılan ve HATIRLANAN bir eylem: "I remember locking the door." (kilitleme eylemi geçmişte gerçekleşti)
- remember + to-infinitive: bir GÖREVİ hatırlamak, unutmadan yapmak: "Remember to lock the door."
- stop + -ing: bir eylemi YAPMAYI BIRAKMAK: "He stopped smoking."
- stop + to-infinitive: başka bir şey yapmak İÇİN durmak (amaç bildiren to-infinitive): "He stopped to smoke."
- try + -ing: bir çözüm/yöntemi DENEMEK: "Try restarting the computer."
- try + to-infinitive: zor bir işte bir şeyi yapmak için ÇABA GÖSTERMEK: "I tried to open the door but it was locked."', '[{"en": "I remember meeting her at the conference last year.", "tr": "Onunla geçen yıl konferansta tanıştığımı hatırlıyorum."}, {"en": "Please remember to send me the file before you leave.", "tr": "Lütfen gitmeden önce dosyayı bana göndermeyi unutma."}, {"en": "She stopped eating meat five years ago.", "tr": "Beş yıl önce et yemeyi bıraktı."}]'::jsonb, '[{"wrong": "I stopped to eat meat five years ago.", "correct": "I stopped eating meat five years ago.", "note": "bir alışkanlığı bırakmak anlamı için stop+-ing kullanılmalı; stop+to-infinitive farklı bir anlam (durup başka bir şey yapmak için) taşır."}, {"wrong": "Remember locking the door before you leave tonight.", "correct": "Remember to lock the door before you leave tonight.", "note": "henüz yapılmamış, gelecekte yapılacak bir görevi hatırlatmak için remember+to-infinitive kullanılır."}]'::jsonb, 'published', 'manual', 8);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('feff372c-ff14-4dfa-95ad-518d6b1d2d3d', 'some-any-no-none', (SELECT id FROM grammar_categories WHERE slug = 'pronouns-determiners'), 'en', 'some / any / no / none Kullanımı', 'some olumlu cümlelerde, any olumsuz ve soru cümlelerinde, no isimle birlikte, none ise isim olmadan olumsuzluk bildirmek için kullanılır.', 'a2', ARRAY['yds','yokdil'], '- some genellikle OLUMLU cümlelerde kullanılır: "I have some money." Bir şey teklif ederken veya rica ederken de kullanılır: "Would you like some tea?"
- any genellikle OLUMSUZ cümlelerde ve SORU cümlelerinde kullanılır: "I don''t have any money.", "Do you have any questions?"
- no, bir isimle birlikte kullanılarak cümleyi olumsuz yapar, fiil olumlu kalır: "I have no money." (= I don''t have any money.)
- none, bir isim OLMADAN tek başına kullanılır, genellikle "of" ile bir grubu işaret eder: "None of my friends came to the party."', '[{"en": "There''s some milk in the fridge if you want it.", "tr": "Buzdolabında biraz süt var, istersen."}, {"en": "I didn''t get any replies to my email.", "tr": "E-postama hiç cevap alamadım."}, {"en": "None of the students passed the exam.", "tr": "Öğrencilerin hiçbiri sınavı geçemedi."}]'::jsonb, '[{"wrong": "I don''t have some time today.", "correct": "I don''t have any time today.", "note": "olumsuz cümlelerde some değil any kullanılır."}, {"wrong": "No of the shops were open on Sunday.", "correct": "None of the shops were open on Sunday.", "note": "isimden önce \"of\" ile kullanıldığında no değil none tercih edilir."}]'::jsonb, 'published', 'manual', 4);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('5a7e2c27-d8c0-4a43-958d-ccd0a4199451', 'most-most-of', (SELECT id FROM grammar_categories WHERE slug = 'pronouns-determiners'), 'en', 'most / most of Farkı', 'most genel bir çoğunluğu belirtmek için doğrudan isimden önce, most of ise belirli/tanımlanmış bir grubun çoğunluğunu belirtmek için the/this/my gibi belirteçlerle birlikte kullanılır.', 'b1', ARRAY['yds','yokdil','toefl'], '- most, GENEL bir çoğunluktan bahsederken doğrudan isimden önce kullanılır, araya belirteç girmez: "Most students like holidays."
- most of, BELİRLİ/tanımlı bir grup söz konusu olduğunda kullanılır ve araya the, this, my, these gibi bir belirteç girer: "Most of the students in my class like holidays."
- most of, zamirlerle de kullanılır: "Most of them agreed with the plan."
- "most of the" yapısı çoğul isimlerle çoğul fiil, sayılamayan isimlerle tekil fiil alır: "Most of the water was gone."', '[{"en": "Most people enjoy spending time with family.", "tr": "Çoğu insan aileyle vakit geçirmekten hoşlanır."}, {"en": "Most of the books on this shelf belong to my sister.", "tr": "Bu raftaki kitapların çoğu kız kardeşime ait."}, {"en": "Most of the water in the bottle had leaked out.", "tr": "Şişedeki suyun çoğu sızmıştı."}]'::jsonb, '[{"wrong": "Most of people like sunny weather.", "correct": "Most people like sunny weather.", "note": "genel bir çoğunluktan bahsederken \"most\" doğrudan isimden önce gelir, \"of\" kullanılmaz."}, {"wrong": "Most the students in my class passed the exam.", "correct": "Most of the students in my class passed the exam.", "note": "belirli bir grup söz konusu olduğunda \"most of the\" kullanılmalıdır, sadece \"most the\" yanlıştır."}]'::jsonb, 'published', 'manual', 5);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('0258f58c-ad44-4b8b-88a5-6dc0cc733b1f', 'each-every-difference', (SELECT id FROM grammar_categories WHERE slug = 'pronouns-determiners'), 'en', 'each / every Farkı', 'each bireyleri tek tek ele alırken, every bir grubu bütün olarak, genelleme yaparak ifade eder; each ikili gruplarda da kullanılabilirken every en az üç öğe gerektirir.', 'b1', ARRAY['yds','yokdil'], '- each ve every genellikle TEKİL isimle ve TEKİL fiille kullanılır: "Each student has a locker.", "Every student has a locker."
- each, bir gruptaki üyeleri TEK TEK, birer birer vurgulayarak ele alır: "Each student answered the question differently."
- every, bir grubu BÜTÜN olarak, genelleme yaparak ifade eder, bireysel farklılık vurgusu yoktur: "Every student must wear a uniform."
- each, İKİ veya daha fazla öğe için kullanılabilir; every en az ÜÇ öğe gerektirir, ikili gruplarda kullanılmaz.
- each, "of" ile bir grup içinden bahsedebilir: "each of us"; every doğrudan "of" ile kullanılmaz, bunun yerine "every one of" denir.', '[{"en": "Each of the two candidates gave a short speech.", "tr": "İki adayın her biri kısa bir konuşma yaptı."}, {"en": "Every child deserves a good education.", "tr": "Her çocuk iyi bir eğitimi hak eder."}, {"en": "Each employee received a different bonus based on performance.", "tr": "Her çalışan performansına göre farklı bir prim aldı."}]'::jsonb, '[{"wrong": "Every of the students passed the test.", "correct": "Every one of the students passed the test.", "note": "every doğrudan \"of\" ile kullanılmaz; \"of\" ile kullanmak için each veya \"every one of\" tercih edilmelidir."}, {"wrong": "Every of the two doors was locked.", "correct": "Each of the two doors was locked.", "note": "sadece iki öğe söz konusu olduğunda every değil each kullanılır."}]'::jsonb, 'published', 'manual', 6);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('dabf4e6e-2831-4b1c-8b73-93b34a5a52ca', 'one-ones-substitution', (SELECT id FROM grammar_categories WHERE slug = 'pronouns-determiners'), 'en', 'one / ones ile İsim Tekrarından Kaçınma', 'Daha önce bahsedilen bir ismi tekrar etmemek için tekilde one, çoğulda ones zamiri kullanılır.', 'a2', ARRAY['yds','yokdil'], '- Bir isim cümlede zaten geçtiyse ve tekrar bahsedilmesi gerekiyorsa, tekrarı önlemek için TEKİL isim yerine one kullanılır: "I need a pen. Do you have one?"
- ÇOĞUL isim yerine ones kullanılır: "These shoes are too small. Do you have any bigger ones?"
- one/ones genellikle bir sıfatla birlikte kullanılır, çünkü amaç genelde belirli bir özelliğe göre seçim yapmaktır: "I like the red one."
- Sayılamayan isimlerin yerine one/ones kullanılmaz; sayılamayan isimler doğrudan tekrar edilir veya hiç tekrarlanmaz: "I need some information. Do you have any?"', '[{"en": "This jacket is too big. Can I try a smaller one?", "tr": "Bu ceket çok büyük. Daha küçük bir tanesini deneyebilir miyim?"}, {"en": "I don''t like these earrings. I prefer the silver ones.", "tr": "Bu küpeleri sevmedim. Gümüş olanları tercih ederim."}, {"en": "Which book do you want, the new one or the old one?", "tr": "Hangi kitabı istiyorsun, yeniyi mi eskiyi mi?"}]'::jsonb, '[{"wrong": "I need some advice. Can you give me one?", "correct": "I need some advice. Can you give me some?", "note": "advice sayılamayan bir isimdir, yerine \"one\" kullanılmaz."}, {"wrong": "These trousers are too long. I need shorter one.", "correct": "These trousers are too long. I need shorter ones.", "note": "çoğul bir isim tekrarının yerine tekil \"one\" değil çoğul \"ones\" kullanılmalıdır."}]'::jsonb, 'published', 'manual', 7);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('0d36bacc-27ea-4ae7-9208-d2ddf206b4a6', 'relative-clauses-non-defining', (SELECT id FROM grammar_categories WHERE slug = 'clauses'), 'en', 'Tanımlamayan İlgi Cümlecikleri (Non-defining Relative Clauses)', 'Tanımlamayan ilgi cümlecikleri, zaten kim/ne olduğu belli olan bir isim hakkında ek bilgi verir, virgüllerle ayrılır ve that ile kullanılamaz.', 'b2', ARRAY['yds','yokdil','toefl'], '- Tanımlamayan (non-defining) ilgi cümlecikleri, ismin KİMLİĞİNİ belirlemek için değil, hakkında EK BİLGİ vermek için kullanılır; isim zaten tek/belli olduğu için cümlecik çıkarılsa da cümlenin anlamı bozulmaz.
- Bu tür cümlecikler mutlaka VİRGÜLLERLE ayrılır: "My brother, who lives in Izmir, is a doctor."
- Tanımlamayan ilgi cümleciklerinde that KULLANILMAZ, sadece who, which, whom, whose kullanılır.
- which, bir önceki CÜMLENİN TAMAMINA da atıfta bulunabilir: "She passed the exam, which made her very happy."', '[{"en": "London, which is the capital of England, has a population of over 8 million.", "tr": "İngiltere''nin başkenti olan Londra''nın nüfusu 8 milyonun üzerindedir."}, {"en": "My colleague, who studied in Canada, speaks perfect English.", "tr": "Kanada''da okumuş olan meslektaşım kusursuz İngilizce konuşur."}, {"en": "He forgot my birthday, which upset me a lot.", "tr": "Doğum günümü unuttu, bu da beni çok üzdü."}]'::jsonb, '[{"wrong": "My mother, that is a teacher, lives in Ankara.", "correct": "My mother, who is a teacher, lives in Ankara.", "note": "tanımlamayan ilgi cümleciklerinde that kullanılmaz, who/which kullanılmalıdır."}, {"wrong": "My car which is red is very old.", "correct": "My car, which is red, is very old.", "note": "tanımlamayan ilgi cümlecikleri mutlaka virgüllerle ayrılmalıdır."}]'::jsonb, 'published', 'manual', 4);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('efd3e673-20f1-4c83-88dc-5eb956b540f8', 'relative-clauses-participle-reduction', (SELECT id FROM grammar_categories WHERE slug = 'clauses'), 'en', 'İlgi Cümleciklerinin -ing / -ed ile Kısaltılması', 'Özneyi tekrarlayan ilgi cümlecikleri, etken anlamda -ing (present participle), edilgen anlamda -ed/-en (past participle) kullanılarak kısaltılabilir.', 'b2', ARRAY['yds','yokdil','toefl'], '- İlgi cümleciğinde özne, ilgi zamiri (who/which/that) ile aynıysa, cümlecik bir participle (ortaç) yapısına indirgenebilir; bu, resmi ve akıcı bir anlatım sağlar.
- Cümlecik ETKEN (aktif) anlamdaysa -ing (present participle) kullanılır: "The man who is standing near the door" → "The man standing near the door."
- Cümlecik EDİLGEN (pasif) anlamdaysa -ed/-en (past participle) kullanılır: "The report which was written by the manager" → "The report written by the manager."
- "be" fiili içermeyen cümleciklerde de (örn. "who works", "who wrote") -ing formu türetilerek kısaltma yapılır: "The people who work here" → "The people working here."', '[{"en": "The woman talking to the manager is my aunt.", "tr": "Müdürle konuşan kadın halamdır."}, {"en": "The car parked outside belongs to my neighbor.", "tr": "Dışarıda park edilmiş araba komşuma ait."}, {"en": "Students studying abroad often face cultural challenges.", "tr": "Yurt dışında okuyan öğrenciler genellikle kültürel zorluklarla karşılaşır."}]'::jsonb, '[{"wrong": "The letter writing by my grandmother is very old.", "correct": "The letter written by my grandmother is very old.", "note": "edilgen anlam taşıyan cümlecik -ing değil -ed/-en ile kısaltılmalıdır."}, {"wrong": "The man stands near the door is my father.", "correct": "The man standing near the door is my father.", "note": "ilgi cümleciği kısaltılırken fiil çekimli halde değil -ing formunda kullanılmalıdır."}]'::jsonb, 'published', 'manual', 5);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('ce982c62-188b-497e-8b20-e3da0dc141f6', 'relative-clauses-omission', (SELECT id FROM grammar_categories WHERE slug = 'clauses'), 'en', 'İlgi Zamirinin Düşürülmesi (Object Relative Pronoun Omission)', 'Tanımlayan ilgi cümleciklerinde, ilgi zamiri cümlecik içinde nesne görevindeyse düşürülebilir; özne görevindeyse düşürülemez.', 'b2', ARRAY['yds','yokdil'], '- Tanımlayan (defining) bir ilgi cümleciğinde, ilgi zamiri (who/whom/which/that) cümlecik içinde NESNE görevi görüyorsa, bu zamir tamamen DÜŞÜRÜLEBİLİR: "The book (that) I read last week was amazing."
- İlgi zamiri cümlecik içinde ÖZNE görevi görüyorsa, ASLA düşürülemez: "The man who called you is my uncle." ("who" düşürülürse anlam bozulur)
- Tanımlamayan (virgüllü, ek bilgi veren) ilgi cümleciklerinde zamir hiçbir zaman düşürülmez, özne olsun nesne olsun.
- Zamir düşürüldüğünde, cümlecik doğrudan özneyle başlar: "The people (who/that) we met on holiday were very friendly."', '[{"en": "The film (that) we watched last night was really boring.", "tr": "Dün gece izlediğimiz film gerçekten sıkıcıydı."}, {"en": "Is this the restaurant (which) you were talking about?", "tr": "Bahsettiğin restoran bu mu?"}, {"en": "The woman who answered the phone was very polite.", "tr": "Telefonu açan kadın çok kibardı."}]'::jsonb, '[{"wrong": "The man called me yesterday is my old friend.", "correct": "The man who called me yesterday is my old friend.", "note": "ilgi zamiri cümlecik içinde özne görevindeyse asla düşürülemez."}, {"wrong": "This is the house which in I grew up.", "correct": "This is the house (which) I grew up in.", "note": "edat cümlecik sonuna taşınırsa zamir düşürülebilir; ama edat zamirin hemen önünde kalacaksa zamir düşürülemez."}]'::jsonb, 'published', 'manual', 6);

-- new exam_questions
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('d66aab69-fdcf-4d53-a30e-32b6bb06895b', 'yds', 'I would like ------- with me to the conference next week.', '[{"id": "a", "text": "you to come"}, {"id": "b", "text": "that you come"}, {"id": "c", "text": "you come"}, {"id": "d", "text": "for you coming"}]'::jsonb, 'a', 'would like fiilinden sonra nesne + to-infinitive gelir, that-cümleciği veya bare infinitive kullanılmaz.', '[{"word": "nesne+to-infinitive", "example": "I want you to stay.", "meaning": "birine bir şey yapmasını istemek"}]'::jsonb, 'medium', true, 'en', 'verb-object-infinitive', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('9473ef9c-0898-4020-b417-b1ab3a0d1f9f', 'yokdil', 'The security guard ------- everyone leave the building immediately.', '[{"id": "a", "text": "made"}, {"id": "b", "text": "told"}, {"id": "c", "text": "asked"}, {"id": "d", "text": "advised"}]'::jsonb, 'a', 'make fiilinden sonra to olmadan bare infinitive kullanılır; cümlede zaten "leave" bare halde olduğu için made doğru seçimdir.', '[{"word": "make sb do", "example": "She made him wait outside.", "meaning": "birini bir şeyi yapmaya zorlamak"}]'::jsonb, 'hard', true, 'en', 'verb-object-infinitive', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('be527d1d-6819-463b-bbc7-6272d8047f7f', 'yds', 'My brother is really keen ------- video games in his free time.', '[{"id": "a", "text": "on playing"}, {"id": "b", "text": "to play"}, {"id": "c", "text": "on play"}, {"id": "d", "text": "playing"}]'::jsonb, 'a', 'keen sıfatı "on" edatıyla kullanılır ve edattan sonra fiil -ing formunda gelir.', '[{"word": "keen on", "example": "She''s keen on painting.", "meaning": "bir şeye çok meraklı/hevesli olmak"}]'::jsonb, 'medium', true, 'en', 'adjective-preposition-ing', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('d0fe2d39-38d3-4b55-ad47-13970b8edfc5', 'toefl', 'I''m not very good ------- in public, so the presentation made me nervous.', '[{"id": "a", "text": "at speaking"}, {"id": "b", "text": "to speak"}, {"id": "c", "text": "at speak"}, {"id": "d", "text": "speaking"}]'::jsonb, 'a', 'good sıfatı "at" edatıyla kullanılır, edattan sonra fiil -ing formunda gelmelidir.', '[{"word": "good at", "example": "He''s good at solving problems.", "meaning": "bir konuda yetenekli olmak"}]'::jsonb, 'medium', true, 'en', 'adjective-preposition-ing', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('e7d3652e-7104-4dbc-aeec-bf83085f90e2', 'yds', 'When I looked out of the window, I saw the children ------- football in the park.', '[{"id": "a", "text": "playing"}, {"id": "b", "text": "play"}, {"id": "c", "text": "to play"}, {"id": "d", "text": "played"}]'::jsonb, 'a', 'Anlık, süren bir görüntü anlatıldığı için algı fiilinden sonra nesne+-ing kullanılır.', '[{"word": "see sb doing", "example": "I saw her waiting at the bus stop.", "meaning": "birini bir eylemi sürdürürken görmek"}]'::jsonb, 'medium', true, 'en', 'see-someone-do-vs-doing', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('13190854-937d-4282-86b7-14994d6d1342', 'toefl', 'I watched the whole film from beginning to end; I saw the hero ------- the villain in the final scene.', '[{"id": "a", "text": "defeat"}, {"id": "b", "text": "defeating"}, {"id": "c", "text": "to defeat"}, {"id": "d", "text": "defeated"}]'::jsonb, 'a', 'Eylemin baştan sona tamamı anlatıldığı için algı fiilinden sonra bare infinitive kullanılır.', '[{"word": "see sb do", "example": "I saw him finish the race.", "meaning": "birinin bir eylemi tamamladığını görmek"}]'::jsonb, 'hard', true, 'en', 'see-someone-do-vs-doing', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('cec58ae2-f816-4f86-8762-0713de01917b', 'yds', '------- regularly is one of the best ways to stay healthy.', '[{"id": "a", "text": "Exercising"}, {"id": "b", "text": "Exercise"}, {"id": "c", "text": "To exercising"}, {"id": "d", "text": "Exercised"}]'::jsonb, 'a', 'Bir eylemi cümlenin öznesi yapmak için -ing (gerund) formu kullanılır.', '[{"word": "gerund as subject", "example": "Reading improves your vocabulary.", "meaning": "eylemi isim gibi özne yapmak"}]'::jsonb, 'easy', true, 'en', 'gerund-as-subject-object', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('702621d9-a2ac-4ccc-80d6-6963a5275345', 'yokdil', 'I don''t mind ------- late if it means finishing the project properly.', '[{"id": "a", "text": "working"}, {"id": "b", "text": "to work"}, {"id": "c", "text": "work"}, {"id": "d", "text": "worked"}]'::jsonb, 'a', 'mind fiilinden sonra nesne olarak sadece -ing kullanılır.', '[{"word": "mind + -ing", "example": "Would you mind waiting a moment?", "meaning": "bir şeyden rahatsız olup olmadığını sormak"}]'::jsonb, 'medium', true, 'en', 'gerund-as-subject-object', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('45cebc7c-1c2b-4919-b030-26de77e82a8a', 'yds', 'On the way to the meeting, he stopped ------- a coffee.', '[{"id": "a", "text": "to buy"}, {"id": "b", "text": "buying"}, {"id": "c", "text": "buy"}, {"id": "d", "text": "bought"}]'::jsonb, 'a', 'stop + to-infinitive, başka bir şey yapmak için durmak anlamı taşır: kahve almak için durdu.', '[{"word": "stop to do sth", "example": "She stopped to answer the phone.", "meaning": "bir şey yapmak için durmak"}]'::jsonb, 'hard', true, 'en', 'verb-ing-infinitive-meaning-change', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('59929df6-fe34-4a6a-aa7e-c0f7619f0e7c', 'yokdil', 'I clearly remember ------- the front door before we left the house this morning.', '[{"id": "a", "text": "locking"}, {"id": "b", "text": "to lock"}, {"id": "c", "text": "lock"}, {"id": "d", "text": "locked"}]'::jsonb, 'a', 'remember + -ing, geçmişte yapılan ve hatırlanan bir eylemi ifade eder.', '[{"word": "remember + -ing", "example": "I remember meeting him before.", "meaning": "geçmişte yapılan bir eylemi hatırlamak"}]'::jsonb, 'hard', true, 'en', 'verb-ing-infinitive-meaning-change', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('f2c880c3-7dcb-4a3a-a9ed-66c004db1753', 'yds', 'I''m afraid there isn''t ------- coffee left in the pot.', '[{"id": "a", "text": "any"}, {"id": "b", "text": "some"}, {"id": "c", "text": "no"}, {"id": "d", "text": "none"}]'::jsonb, 'a', 'Olumsuz cümlelerde some değil any kullanılır.', '[{"word": "any + olumsuz", "example": "I don''t have any siblings.", "meaning": "olumsuz cümlede miktar belirtme"}]'::jsonb, 'easy', true, 'en', 'some-any-no-none', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('51eb5627-629c-4c63-8866-6b92dea154ff', 'yokdil', '------- of the answers she gave were correct.', '[{"id": "a", "text": "None"}, {"id": "b", "text": "No"}, {"id": "c", "text": "Any"}, {"id": "d", "text": "Some of"}]'::jsonb, 'a', '"of" ile bir grubu işaret ederken no değil none kullanılır.', '[{"word": "none of", "example": "None of us knew the answer.", "meaning": "bir grubun hiçbiri"}]'::jsonb, 'medium', true, 'en', 'some-any-no-none', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('1c7fc4cd-aeb9-47bb-85fb-780298b98006', 'yds', '------- students prefer studying in groups rather than alone.', '[{"id": "a", "text": "Most"}, {"id": "b", "text": "Most of"}, {"id": "c", "text": "Almost of"}, {"id": "d", "text": "The most"}]'::jsonb, 'a', 'Genel bir çoğunluktan bahsedilirken "most" doğrudan isimden önce gelir, belirteç veya "of" kullanılmaz.', '[{"word": "most + isim", "example": "Most children love cartoons.", "meaning": "genel çoğunluk"}]'::jsonb, 'medium', true, 'en', 'most-most-of', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('58659fad-4c7e-4b89-b82c-eaf16cbbb3c2', 'yokdil', 'I couldn''t answer many questions because ------- the exam was based on topics we hadn''t studied.', '[{"id": "a", "text": "most of"}, {"id": "b", "text": "most"}, {"id": "c", "text": "almost"}, {"id": "d", "text": "the most of"}]'::jsonb, 'a', '"the exam" gibi belirli bir grup söz konusu olduğunda "most of the" yapısı kullanılmalıdır.', '[{"word": "most of the", "example": "Most of the food was cold.", "meaning": "belirli bir grubun çoğunluğu"}]'::jsonb, 'hard', true, 'en', 'most-most-of', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('6b3f7efd-9083-4fee-8f46-c4409a22f031', 'yds', '------- of the two applicants had excellent qualifications, so the decision was difficult.', '[{"id": "a", "text": "Each"}, {"id": "b", "text": "Every"}, {"id": "c", "text": "All"}, {"id": "d", "text": "Most"}]'::jsonb, 'a', 'İki öğeden bahsedildiği ve "of" ile kullanıldığı için each doğru seçimdir.', '[{"word": "each of", "example": "Each of the boxes was checked.", "meaning": "bir grubun her bir üyesi"}]'::jsonb, 'medium', true, 'en', 'each-every-difference', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('a965c5e9-22cd-40da-ae99-7eb465982068', 'yokdil', 'The rule applies to ------- employee, without exception.', '[{"id": "a", "text": "every"}, {"id": "b", "text": "each of"}, {"id": "c", "text": "all of"}, {"id": "d", "text": "most"}]'::jsonb, 'a', 'İstisnasız bir genelleme yapıldığı için every doğru seçimdir.', '[{"word": "every", "example": "Every rule has an exception.", "meaning": "istisnasız genelleme"}]'::jsonb, 'medium', true, 'en', 'each-every-difference', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('fcd84875-c58f-46bb-89e7-7d080c0beb59', 'yds', 'I don''t like this design. Could you show me a different -------?', '[{"id": "a", "text": "one"}, {"id": "b", "text": "ones"}, {"id": "c", "text": "it"}, {"id": "d", "text": "that"}]'::jsonb, 'a', 'Tekil bir ismin (design) tekrarından kaçınmak için one kullanılır.', '[{"word": "one", "example": "I want a bigger one.", "meaning": "tekil isim tekrarından kaçınma"}]'::jsonb, 'easy', true, 'en', 'one-ones-substitution', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('39de3160-feb2-488f-99c1-d3fdcaf224bf', 'yokdil', 'My old headphones broke, so I bought some new -------.', '[{"id": "a", "text": "ones"}, {"id": "b", "text": "one"}, {"id": "c", "text": "it"}, {"id": "d", "text": "those"}]'::jsonb, 'a', 'Çoğul bir ismin (headphones) tekrarından kaçınmak için ones kullanılır.', '[{"word": "ones", "example": "These shoes are old, I need new ones.", "meaning": "çoğul isim tekrarından kaçınma"}]'::jsonb, 'easy', true, 'en', 'one-ones-substitution', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('1981f805-e0cc-4a98-ae2b-b5742bb3014a', 'yds', 'Mount Everest, ------- is the highest mountain in the world, attracts thousands of climbers every year.', '[{"id": "a", "text": "which"}, {"id": "b", "text": "that"}, {"id": "c", "text": "who"}, {"id": "d", "text": "what"}]'::jsonb, 'a', 'Tanımlamayan ilgi cümleciklerinde that değil which/who kullanılır; burada bir dağdan bahsedildiği için which doğrudur.', '[{"word": "non-defining clause", "example": "Paris, which I visited last year, is beautiful.", "meaning": "ek bilgi veren ilgi cümleciği"}]'::jsonb, 'medium', true, 'en', 'relative-clauses-non-defining', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('056b028f-95d0-412f-a80b-c6ab99328239', 'yokdil', 'He finally passed his driving test, ------- surprised everyone in the family.', '[{"id": "a", "text": "which"}, {"id": "b", "text": "that"}, {"id": "c", "text": "who"}, {"id": "d", "text": "it"}]'::jsonb, 'a', 'which, kendisinden önceki cümlenin tamamına atıfta bulunabilir.', '[{"word": "which (whole clause)", "example": "She was late, which annoyed her boss.", "meaning": "bir önceki cümlenin tamamına atıf"}]'::jsonb, 'hard', true, 'en', 'relative-clauses-non-defining', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('cca2c689-4045-46c6-8812-be910988c8db', 'yds', 'The passengers ------- for the delayed flight were getting impatient.', '[{"id": "a", "text": "waiting"}, {"id": "b", "text": "waited"}, {"id": "c", "text": "wait"}, {"id": "d", "text": "who waiting"}]'::jsonb, 'a', 'Etken anlamlı ilgi cümleciği -ing (present participle) ile kısaltılır.', '[{"word": "present participle", "example": "The kids playing outside are my nephews.", "meaning": "etken ilgi cümleciği kısaltması"}]'::jsonb, 'medium', true, 'en', 'relative-clauses-participle-reduction', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('fd0d49fb-538e-4225-9376-1fb1dcf49a40', 'yokdil', 'All the documents ------- by the committee will be reviewed next week.', '[{"id": "a", "text": "submitted"}, {"id": "b", "text": "submitting"}, {"id": "c", "text": "submit"}, {"id": "d", "text": "who submitted"}]'::jsonb, 'a', 'Edilgen anlamlı ilgi cümleciği -ed/-en (past participle) ile kısaltılır.', '[{"word": "past participle", "example": "The book written by her is a bestseller.", "meaning": "edilgen ilgi cümleciği kısaltması"}]'::jsonb, 'hard', true, 'en', 'relative-clauses-participle-reduction', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('c6d3afc3-b7de-4c65-869c-0436378a04fe', 'yds', 'The scientist ------- discovered this vaccine won a Nobel Prize.', '[{"id": "a", "text": "who"}, {"id": "b", "text": "whom"}, {"id": "c", "text": "which"}, {"id": "d", "text": "whose"}]'::jsonb, 'a', 'İlgi zamiri cümlecik içinde özne (discovered fiilinin öznesi) görevinde olduğu için düşürülemez ve who kullanılmalıdır.', '[{"word": "subject relative pronoun", "example": "The teacher who taught us was excellent.", "meaning": "düşürülemeyen özne ilgi zamiri"}]'::jsonb, 'medium', true, 'en', 'relative-clauses-omission', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('12307cc0-1d21-47ec-863f-614da0fbae60', 'yokdil', 'This is the novel ------- I''ve been telling you about for weeks.', '[{"id": "a", "text": "that"}, {"id": "b", "text": "who"}, {"id": "c", "text": "whose"}, {"id": "d", "text": "it"}]'::jsonb, 'a', 'İlgi zamiri cümlecik içinde nesne görevinde olduğu için düşürülebilir ya da that ile kullanılabilir.', '[{"word": "object relative pronoun", "example": "The car (that) I bought is second-hand.", "meaning": "düşürülebilen nesne ilgi zamiri"}]'::jsonb, 'medium', true, 'en', 'relative-clauses-omission', 'system', 'approved');
