-- 034_grammar_reference_wave5.sql
--
-- Gramer Rehberi 5. dalga genisleme -- Cambridge "English Grammar in Use"
-- (Murphy, 5. baski) icerigine paralel, kitaptaki 3 bolum ve kucuk
-- eksiklerin bir kismi: Present and Past (bolum 1), Conjunctions and
-- Prepositions (bolum 14), Phrasal Verbs (bolum 16).
--
-- ICERIK KAYNAGI VE TELIF NOTU: Bu migration'daki grammar_topics kayitlarinin
-- SADECE unite/konu basliklari kitaptaki standart dilbilgisi terminolojisinden
-- esinlenerek adlandirilmistir -- bunlar telife konu olmayan genel gramer
-- kavramlaridir. Kural aciklamalari (rule_content_md), ornek cumleler
-- (example_sentences), sik hatalar (common_mistakes) ve tum exam_questions
-- sorulari %100 ozgun olarak yazilmistir. Kitaptan hicbir cumle, ornek veya
-- alistirma birebir kopyalanmamistir.
--
-- Icerik: yeni grammar_categories yok (mevcut tenses, sentence-structure,
-- phrasal-vocab kategorilerine eklendi), 8 yeni grammar_topics
-- (tenses'e +1, sentence-structure'a +3, phrasal-vocab'a +4), 16 yeni
-- exam_questions (her yeni konu icin 2 soru, topic_tag = grammar_topics.slug
-- ile birebir eslesir).
--
-- Bu SQL, Supabase MCP apply_migration araciyla proje mrxeuxscyztpiuagsumh
-- uzerinde 2 parcada (topics, questions) zaten uygulanmistir; bu dosya repo
-- gecmisi icin ayniyla tekrar eder.

-- new grammar_topics
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('0adfe64c-d01f-4f70-aee9-e5f20cb9adf1', 'present-simple-vs-continuous', (SELECT id FROM grammar_categories WHERE slug = 'tenses'), 'en', 'Present Simple ve Present Continuous Farkı', 'Present Simple alışkanlıkları ve genel gerçekleri, Present Continuous ise şu an veya bu dönemde süren eylemleri anlatır.', 'a2', ARRAY['yds','yokdil'], '- Present Simple, düzenli tekrar eden ALIŞKANLIKLARI, rutinleri ve genel gerçekleri anlatır: "I go to work by bus every day.", "Water boils at 100°C."
- Present Simple, sıklık zarflarıyla (always, usually, often, sometimes, never) sıkça kullanılır: "She always arrives on time."
- Present Continuous, KONUŞMA ANINDA süren bir eylemi anlatır: "I am writing an email right now."
- Present Continuous, şu anki dönemde (geçici olarak) süren, henüz bitmemiş durumları da anlatabilir: "I''m reading a great book these days."
- like, want, know, believe, understand gibi DURUM (state) fiilleri normalde Present Continuous''ta kullanılmaz, Present Simple ile kullanılır: "I want a coffee."', '[{"en": "My father works in a bank.", "tr": "Babam bir bankada çalışıyor."}, {"en": "Look! The bus is coming.", "tr": "Bak! Otobüs geliyor."}, {"en": "I understand the instructions now.", "tr": "Talimatları şimdi anlıyorum."}]'::jsonb, '[{"wrong": "I am knowing the answer.", "correct": "I know the answer.", "note": "know bir durum fiilidir, Present Continuous''ta kullanılmaz."}, {"wrong": "She usually is watching TV in the evening.", "correct": "She usually watches TV in the evening.", "note": "düzenli tekrar eden bir alışkanlık anlatıldığı için Present Simple kullanılmalı, sıklık zarfı da bunu destekler."}]'::jsonb, 'published', 'manual', 10);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('689f8e53-93fd-4be6-8096-7f44c5061ca2', 'time-clauses-future-meaning', (SELECT id FROM grammar_categories WHERE slug = 'sentence-structure'), 'en', 'Zaman Cümleciklerinde Gelecek Anlamı: when/while/before/after/until + Present', 'when, while, before, after, until gibi bağlaçlarla kurulan zaman cümleciklerinde, gelecekteki bir eylemden bahsedilse bile will değil Present Simple/Present Perfect kullanılır.', 'b1', ARRAY['yds','yokdil','toefl'], '- when, while, before, after, until, till, as soon as, by the time gibi zaman bağlaçlarıyla kurulan CÜMLECİKLERDE, anlam gelecekle ilgili olsa bile will KULLANILMAZ, bunun yerine Present Simple kullanılır: "I will call you when I arrive."
- Bu kural sadece zaman cümleciği için geçerlidir; ANA cümlede will kullanılmaya devam eder: "When she gets home, she will cook dinner."
- Zaman cümleciğinde anlatılan eylem ana cümledeki eylemden ÖNCE tamamlanmış olacaksa, Present Perfect de kullanılabilir: "I''ll give you the book after I have finished it."
- Bu kural if-cümlecikleri (koşul cümlecikleri, birinci tip şart) için de aynı şekilde geçerlidir.', '[{"en": "I''ll text you as soon as I land.", "tr": "İner inmez sana mesaj atacağım."}, {"en": "We won''t leave until everyone arrives.", "tr": "Herkes gelene kadar ayrılmayacağız."}, {"en": "By the time you finish reading this, I will have left.", "tr": "Bunu okumayı bitirdiğinde ben çoktan gitmiş olacağım."}]'::jsonb, '[{"wrong": "I will call you when I will arrive.", "correct": "I will call you when I arrive.", "note": "zaman cümleciğinde gelecek anlamı olsa bile will kullanılmaz, present simple kullanılır."}, {"wrong": "She will cook dinner when she will get home.", "correct": "She will cook dinner when she gets home.", "note": "zaman bağlacından sonraki cümlecikte will değil present simple kullanılır."}]'::jsonb, 'published', 'manual', 4);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('9312cf0a-f84e-4723-b5b5-69e5e4482074', 'if-unless-in-case', (SELECT id FROM grammar_categories WHERE slug = 'sentence-structure'), 'en', 'if / unless / in case Farkı', 'if bir koşulu, unless "eğer ...olmazsa" anlamında olumsuz bir koşulu, in case ise gerçekleşmesi muhtemel bir durum için önceden alınan tedbiri anlatır.', 'b1', ARRAY['yds','yokdil'], '- if, bir eylemin gerçekleşmesinin BAŞKA bir eyleme bağlı olduğu koşul cümlelerinde kullanılır: "If it rains, we will stay home."
- unless, "eğer ... OLMAZSA / ...MEDİKÇE" anlamına gelir, yani "if not" ile eş değerdir: "Unless you hurry, you''ll miss the bus."
- unless SADECE olumsuz koşul anlatır; unless''ten sonraki fiil zaten olumlu formda olmalıdır, "unless...not" gibi çift olumsuzluk yapılmaz.
- in case, bir şey OLABİLİR diye önceden ÖNLEM/TEDBİR almayı anlatır; sonucu değil, ihtimale karşı hazırlığı ifade eder: "Take an umbrella in case it rains."', '[{"en": "If you study hard, you''ll pass the exam.", "tr": "Sıkı çalışırsan sınavı geçersin."}, {"en": "Unless you apologize, she won''t forgive you.", "tr": "Özür dilemedikçe seni affetmeyecek."}, {"en": "I''ll take my laptop in case I need to work during the trip.", "tr": "Yolculukta çalışmam gerekebilir diye dizüstü bilgisayarımı yanıma alacağım."}]'::jsonb, '[{"wrong": "Unless you don''t study, you will fail.", "correct": "Unless you study, you will fail.", "note": "unless zaten olumsuz anlam taşır, ayrıca \"don''t\" ile çift olumsuzluk yapılmaz."}, {"wrong": "I''ll take an umbrella if it rains, just to be prepared for the possibility.", "correct": "I''ll take an umbrella in case it rains.", "note": "önceden alınan bir tedbir anlatılıyorsa if değil in case kullanılmalıdır."}]'::jsonb, 'published', 'manual', 5);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('dc6d177b-63e2-4b63-95c3-23df6a78e32c', 'so-that-such-that', (SELECT id FROM grammar_categories WHERE slug = 'sentence-structure'), 'en', 'so...that / such...that: Sonuç Cümlecikleri', 'so, sıfat veya zarftan önce; such ise bir isim grubundan önce kullanılarak "o kadar...ki" anlamıyla bir sonucu ifade eder.', 'b1', ARRAY['yds','yokdil','toefl'], '- so + sıfat/zarf + that: "o kadar [sıfat/zarf] ki" anlamı taşır, so doğrudan bir SIFAT veya ZARFTAN önce gelir: "The exam was so difficult that nobody finished it."
- such + (a/an) + (sıfat) + isim + that: such bir İSİM grubundan önce kullanılır, isim tekilse araya a/an girer: "It was such a difficult exam that nobody finished it."
- so + many/much/few/little + isim yapısı da mevcuttur: "There were so many people that we couldn''t find a seat."
- Anlam olarak so...that ile such...that genelde birbirinin yerine geçebilir, sadece SÖZ DİZİMİ (sıfat mı isim mi vurgulanıyor) farklıdır.', '[{"en": "She was so tired that she fell asleep on the sofa.", "tr": "O kadar yorgundu ki kanepede uyuyakaldı."}, {"en": "It was such a boring film that we left before the end.", "tr": "O kadar sıkıcı bir filmdi ki bitmeden çıktık."}, {"en": "He speaks so quickly that I can''t understand him.", "tr": "O kadar hızlı konuşuyor ki onu anlayamıyorum."}]'::jsonb, '[{"wrong": "It was such difficult exam that nobody passed.", "correct": "It was such a difficult exam that nobody passed.", "note": "such''tan sonra tekil sayılabilir bir isim geliyorsa araya a/an eklenmelidir."}, {"wrong": "The weather was such cold that we stayed inside.", "correct": "The weather was so cold that we stayed inside.", "note": "doğrudan bir sıfattan (cold) önce such değil so kullanılır."}]'::jsonb, 'published', 'manual', 6);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('0d85a206-1886-4450-ad3a-9074482bfb96', 'phrasal-verbs-up-down', (SELECT id FROM grammar_categories WHERE slug = 'phrasal-vocab'), 'en', 'Phrasal Verb''lerde up / down Parçacıklarının Anlam Grupları', 'up parçacığı genellikle artış, tamamlanma veya ortaya çıkma; down parçacığı ise azalma, durma veya kaydetme anlamı katar.', 'b1', ARRAY['yds','yokdil','toefl'], '- up parçacığı bir eylemi TAMAMLAMA/bitirme anlamı katabilir: finish up, use up, eat up, clean up ("Eat up your vegetables.")
- up parçacığı ARTIŞ, yükselme anlamı da katabilir: speed up (hızlanmak), turn up the volume (sesi açmak/yükseltmek)
- up parçacığı bir şeyin ORTAYA ÇIKMASI/belirmesi anlamı da katabilir: come up (gündeme gelmek), show up / turn up (beklenmedik şekilde gelmek)
- down parçacığı AZALMA, yavaşlama anlamı katar: slow down (yavaşlamak), turn down (sesi kısmak/reddetmek), calm down (sakinleşmek)
- down parçacığı bir şeyin YAZIYA GEÇİRİLMESİ/kaydedilmesi anlamını da katabilir: write down (not almak), note down (kaydetmek)', '[{"en": "Please finish up your work before you leave.", "tr": "Lütfen gitmeden önce işini bitir."}, {"en": "Could you turn the music down? It''s too loud.", "tr": "Müziği kısar mısın? Çok yüksek."}, {"en": "An unexpected problem came up during the meeting.", "tr": "Toplantı sırasında beklenmedik bir sorun ortaya çıktı."}]'::jsonb, '[{"wrong": "Please turn up the music, it''s too loud.", "correct": "Please turn down the music, it''s too loud.", "note": "sesi azaltmak/kısmak anlamı için up değil down kullanılmalıdır."}, {"wrong": "I need to write up your phone number so I don''t forget it.", "correct": "I need to write down your phone number so I don''t forget it.", "note": "bir bilgiyi not almak/kaydetmek anlamı için down kullanılır."}]'::jsonb, 'published', 'manual', 3);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('9954566f-1b47-4e93-ba4f-83d79ad6f666', 'phrasal-verbs-in-out', (SELECT id FROM grammar_categories WHERE slug = 'phrasal-vocab'), 'en', 'Phrasal Verb''lerde in / out Parçacıklarının Anlam Grupları', 'in parçacığı genellikle katılma, dahil olma veya teslim etme; out parçacığı ise tükenme veya bir bilgiyi ortaya çıkarma anlamı katar.', 'b1', ARRAY['yds','yokdil','toefl'], '- in parçacığı bir gruba/faaliyete KATILMA, dahil olma anlamı katabilir: join in (katılmak), fit in (uyum sağlamak)
- in parçacığı bir şeyi TESLİM ETME/doldurma anlamı da katabilir: hand in (teslim etmek), fill in (doldurmak, örn. form)
- out parçacığı bir şeyin TÜKENMESİ/bitmesi anlamı katabilir: run out (tükenmek), sell out (tükenmek, satılıp bitmek)
- out parçacığı bir bilginin ORTAYA ÇIKARILMASI/keşfedilmesi anlamı da katabilir: find out (öğrenmek), figure out (çözmek, anlamak), point out (belirtmek)
- out parçacığı bir şeyin SİLİNMESİ anlamı da katabilir: cross out (üzerini çizmek)', '[{"en": "Please fill in this form before your appointment.", "tr": "Randevunuzdan önce lütfen bu formu doldurun."}, {"en": "We''ve run out of milk, can you buy some?", "tr": "Sütümüz bitti, biraz alabilir misin?"}, {"en": "It took me a while to figure out how the machine works.", "tr": "Makinenin nasıl çalıştığını çözmem biraz zaman aldı."}]'::jsonb, '[{"wrong": "I need to hand out my homework before Friday.", "correct": "I need to hand in my homework before Friday.", "note": "bir ödevi/işi teslim etmek anlamı için out değil in kullanılmalıdır (hand out = dağıtmak, farklı bir anlam taşır)."}, {"wrong": "We finally found in the truth about what happened.", "correct": "We finally found out the truth about what happened.", "note": "bir bilgiyi öğrenmek anlamı için in değil out kullanılmalıdır."}]'::jsonb, 'published', 'manual', 4);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('9c9e87c4-f1b0-4189-b81d-78190c6b17e9', 'phrasal-verbs-on-off', (SELECT id FROM grammar_categories WHERE slug = 'phrasal-vocab'), 'en', 'Phrasal Verb''lerde on / off Parçacıklarının Anlam Grupları', 'on parçacığı genellikle devam etme veya bir cihazı çalıştırma; off parçacığı ise durdurma, iptal etme veya ayrılma anlamı katar.', 'b1', ARRAY['yds','yokdil','toefl'], '- on parçacığı bir eylemin DEVAM ETMESİ anlamı katabilir: carry on (devam etmek), go on (devam etmek), keep on (ısrarla devam etmek)
- on parçacığı bir cihazı ÇALIŞTIRMA/açma anlamı da katabilir: turn on, switch on (açmak)
- off parçacığı bir cihazı KAPATMA/durdurma anlamı katabilir: turn off, switch off (kapatmak)
- off parçacığı bir etkinliğin İPTAL EDİLMESİ/ertelenmesi anlamı da katabilir: call off (iptal etmek), put off (ertelemek)
- off parçacığı bir yerden AYRILMA/hareket etme anlamı da katabilir: set off (yola çıkmak), take off (uçağın kalkması)', '[{"en": "Despite the difficulties, they decided to carry on with the project.", "tr": "Zorluklara rağmen projeye devam etmeye karar verdiler."}, {"en": "The wedding was called off at the last minute.", "tr": "Düğün son anda iptal edildi."}, {"en": "We set off early to avoid the traffic.", "tr": "Trafikten kaçınmak için erken yola çıktık."}]'::jsonb, '[{"wrong": "The meeting was put on because the manager was ill.", "correct": "The meeting was put off because the manager was ill.", "note": "bir etkinliği ertelemek anlamı için on değil off kullanılmalıdır."}, {"wrong": "Please turn off the lights, I can''t see anything.", "correct": "Please turn on the lights, I can''t see anything.", "note": "bir cihazı açmak anlamı için off değil on kullanılmalıdır."}]'::jsonb, 'published', 'manual', 5);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('c1f2a5fd-fdcf-49dd-81ea-635564fb4b62', 'separable-inseparable-phrasal-verbs', (SELECT id FROM grammar_categories WHERE slug = 'phrasal-vocab'), 'en', 'Ayrılabilir ve Ayrılamaz Phrasal Verb''ler', 'Bazı phrasal verb''lerde fiil ve parçacık arasına nesne girebilir (ayrılabilir), bazılarında ise giremez (ayrılamaz); nesne zamir olduğunda ayrılabilir yapılarda mutlaka araya girmesi gerekir.', 'b2', ARRAY['yds','yokdil','toefl'], '- AYRILABİLİR (separable) phrasal verb''lerde nesne fiil ile parçacık ARASINA girebilir veya parçacıktan sonra gelebilir: "Turn off the light." = "Turn the light off."
- Nesne bir ZAMİR (it, them, him, her vb.) olduğunda, ayrılabilir phrasal verb''lerde zamir MUTLAKA fiil ile parçacık arasına girer: "Turn it off." ("Turn off it" YANLIŞ)
- AYRILAMAZ (inseparable) phrasal verb''lerde nesne HER ZAMAN parçacıktan sonra gelir, araya giremez: "Look after the children." = "Look after them."
- Nesnesiz (intransitive) phrasal verb''ler zaten hiçbir nesne almaz, bu kural onlar için geçerli değildir: "The plane took off."', '[{"en": "I picked up my sister from school.", "tr": "Kız kardeşimi okuldan aldım."}, {"en": "Can you look after my cat this weekend?", "tr": "Bu hafta sonu kedime bakabilir misin?"}, {"en": "She turned the offer down immediately.", "tr": "Teklifi hemen reddetti."}]'::jsonb, '[{"wrong": "I picked up her from school.", "correct": "I picked her up from school.", "note": "nesne zamir olduğunda ayrılabilir phrasal verb''lerde zamir mutlaka araya girmelidir."}, {"wrong": "Look the children after while I''m out.", "correct": "Look after the children while I''m out.", "note": "look after ayrılamaz bir phrasal verb''dür, nesne her zaman parçacıktan sonra gelir."}]'::jsonb, 'published', 'manual', 6);

-- new exam_questions
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('760faa5b-de07-4d56-859b-f666b11a8ff4', 'yds', 'Please be quiet, I ------- to concentrate on this problem.', '[{"id": "a", "text": "am trying"}, {"id": "b", "text": "try"}, {"id": "c", "text": "tried"}, {"id": "d", "text": "have tried"}]'::jsonb, 'a', 'Konuşma anında süren bir eylem anlatıldığı için Present Continuous kullanılır.', '[{"word": "Present Continuous", "example": "She is cooking dinner right now.", "meaning": "konuşma anında süren eylem"}]'::jsonb, 'easy', true, 'en', 'present-simple-vs-continuous', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('f5361ee0-e5da-47d1-9cef-31fd0e04e6a1', 'yokdil', 'Sugar ------- in hot water quickly.', '[{"id": "a", "text": "dissolves"}, {"id": "b", "text": "is dissolving"}, {"id": "c", "text": "dissolved"}, {"id": "d", "text": "has dissolved"}]'::jsonb, 'a', 'Genel bir bilimsel gerçek anlatıldığı için Present Simple kullanılır.', '[{"word": "Present Simple", "example": "The sun rises in the east.", "meaning": "genel gerçekler"}]'::jsonb, 'medium', true, 'en', 'present-simple-vs-continuous', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('d0eae0dd-c826-41b1-96d8-589dd291da06', 'yds', 'I''ll let you know as soon as I ------- any news.', '[{"id": "a", "text": "hear"}, {"id": "b", "text": "will hear"}, {"id": "c", "text": "heard"}, {"id": "d", "text": "will have heard"}]'::jsonb, 'a', 'Zaman cümleciğinde (as soon as) gelecek anlamı olsa bile will değil present simple kullanılır.', '[{"word": "as soon as + present", "example": "Call me as soon as you land.", "meaning": "zaman cümleciğinde gelecek anlamı"}]'::jsonb, 'medium', true, 'en', 'time-clauses-future-meaning', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('c57f92c1-5a48-40f8-a176-c6424482672c', 'yokdil', 'We can''t start the meeting until everyone -------.', '[{"id": "a", "text": "arrives"}, {"id": "b", "text": "will arrive"}, {"id": "c", "text": "arrived"}, {"id": "d", "text": "is arriving"}]'::jsonb, 'a', 'until ile kurulan zaman cümleciğinde will değil present simple kullanılır.', '[{"word": "until + present", "example": "Wait here until I come back.", "meaning": "zaman cümleciğinde gelecek anlamı"}]'::jsonb, 'medium', true, 'en', 'time-clauses-future-meaning', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('a1d5f4c1-308f-4c25-bc11-313c3842e7c9', 'yds', '------- you finish your homework, you can''t go out and play.', '[{"id": "a", "text": "Unless"}, {"id": "b", "text": "If"}, {"id": "c", "text": "In case"}, {"id": "d", "text": "Even if"}]'::jsonb, 'a', '"Ödevini bitirmedikçe dışarı çıkamazsın" anlamı, if not yerine geçen unless ile kurulur.', '[{"word": "unless", "example": "Unless you leave now, you''ll be late.", "meaning": "eğer ...olmazsa"}]'::jsonb, 'medium', true, 'en', 'if-unless-in-case', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('6a193f75-0442-4b2b-b79a-2f1f2494275c', 'yokdil', 'I always carry a spare phone charger ------- my battery dies during the day.', '[{"id": "a", "text": "in case"}, {"id": "b", "text": "if"}, {"id": "c", "text": "unless"}, {"id": "d", "text": "when"}]'::jsonb, 'a', 'Bir ihtimale karşı önceden alınan tedbir anlatıldığı için in case kullanılır.', '[{"word": "in case", "example": "Take a map in case you get lost.", "meaning": "ihtimale karşı tedbir almak"}]'::jsonb, 'medium', true, 'en', 'if-unless-in-case', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('8b98f9cf-bdbf-4c63-99fa-6422335c4d79', 'yds', 'The traffic was ------- heavy that we arrived two hours late.', '[{"id": "a", "text": "so"}, {"id": "b", "text": "such"}, {"id": "c", "text": "such a"}, {"id": "d", "text": "too"}]'::jsonb, 'a', 'Doğrudan bir sıfattan (heavy) önce so kullanılır.', '[{"word": "so + sıfat + that", "example": "It was so hot that we stayed indoors.", "meaning": "o kadar ... ki"}]'::jsonb, 'medium', true, 'en', 'so-that-such-that', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('066dafca-5ded-4a12-a38f-82339f435e4f', 'yokdil', 'It was ------- interesting book that I finished it in one day.', '[{"id": "a", "text": "such an"}, {"id": "b", "text": "so"}, {"id": "c", "text": "so an"}, {"id": "d", "text": "such"}]'::jsonb, 'a', 'Tekil sayılabilir bir isim grubundan (interesting book) önce such an kullanılır.', '[{"word": "such a/an + isim + that", "example": "It was such a good film that I watched it twice.", "meaning": "o kadar ... ki"}]'::jsonb, 'medium', true, 'en', 'so-that-such-that', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('8e431a59-ce22-4fa3-89b8-a39ee67d15e4', 'yds', 'The company had to ------- production because of falling demand.', '[{"id": "a", "text": "slow down"}, {"id": "b", "text": "speed up"}, {"id": "c", "text": "turn up"}, {"id": "d", "text": "use up"}]'::jsonb, 'a', 'Azalan talep nedeniyle üretimin yavaşlatılması anlatıldığı için slow down doğru seçimdir.', '[{"word": "slow down", "example": "The car slowed down near the school.", "meaning": "yavaşlamak"}]'::jsonb, 'medium', true, 'en', 'phrasal-verbs-up-down', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('7445f298-4e5d-4d66-84de-a8bcf3d217bf', 'yokdil', 'An old friend I hadn''t seen for years suddenly ------- at the party.', '[{"id": "a", "text": "turned up"}, {"id": "b", "text": "turned down"}, {"id": "c", "text": "slowed down"}, {"id": "d", "text": "used up"}]'::jsonb, 'a', 'Beklenmedik şekilde ortaya çıkmak/gelmek anlamı için turn up kullanılır.', '[{"word": "turn up", "example": "He turned up late, as usual.", "meaning": "beklenmedik şekilde gelmek"}]'::jsonb, 'medium', true, 'en', 'phrasal-verbs-up-down', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('9f105ac7-a867-4f01-ad5a-5e3bc2ee2eaa', 'yds', 'The concert tickets ------- within an hour of going on sale.', '[{"id": "a", "text": "sold out"}, {"id": "b", "text": "filled in"}, {"id": "c", "text": "found out"}, {"id": "d", "text": "handed in"}]'::jsonb, 'a', 'Bir ürünün tükenmesi/satılıp bitmesi anlamı için sell out kullanılır.', '[{"word": "sell out", "example": "The tickets sold out in minutes.", "meaning": "tükenmek, satılıp bitmek"}]'::jsonb, 'medium', true, 'en', 'phrasal-verbs-in-out', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('807a4d77-dde3-47a3-9105-6e5ec80d69ab', 'yokdil', 'Could you please ------- this application form and return it to us?', '[{"id": "a", "text": "fill in"}, {"id": "b", "text": "find out"}, {"id": "c", "text": "sell out"}, {"id": "d", "text": "hand out"}]'::jsonb, 'a', 'Bir formu doldurmak anlamı için fill in kullanılır.', '[{"word": "fill in", "example": "Fill in your name and address.", "meaning": "formu doldurmak"}]'::jsonb, 'easy', true, 'en', 'phrasal-verbs-in-out', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('d75eabf0-5d47-485c-b929-792f75d5859a', 'yds', 'The flight was delayed for two hours before finally -------.', '[{"id": "a", "text": "taking off"}, {"id": "b", "text": "turning off"}, {"id": "c", "text": "calling off"}, {"id": "d", "text": "putting off"}]'::jsonb, 'a', 'Bir uçağın havalanması anlamı için take off kullanılır.', '[{"word": "take off", "example": "The plane took off on time.", "meaning": "uçağın havalanması"}]'::jsonb, 'medium', true, 'en', 'phrasal-verbs-on-off', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('7e5aa278-0c50-4bf3-8b63-61f59add7399', 'yokdil', 'Because of the storm, the outdoor concert had to be -------.', '[{"id": "a", "text": "called off"}, {"id": "b", "text": "turned on"}, {"id": "c", "text": "carried on"}, {"id": "d", "text": "set off"}]'::jsonb, 'a', 'Bir etkinliğin iptal edilmesi anlamı için call off kullanılır.', '[{"word": "call off", "example": "They called off the match due to rain.", "meaning": "iptal etmek"}]'::jsonb, 'medium', true, 'en', 'phrasal-verbs-on-off', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('ba61f0d0-ab07-4377-ad4e-0b4d6913785c', 'yds', 'My grandmother raised five children on her own; she brought ------- all by herself.', '[{"id": "a", "text": "them up"}, {"id": "b", "text": "up them"}, {"id": "c", "text": "up they"}, {"id": "d", "text": "they up"}]'::jsonb, 'a', 'Nesne zamir (them) olduğu için ayrılabilir phrasal verb''de zamir fiil ile parçacık arasına girmelidir.', '[{"word": "bring up", "example": "They brought him up in a small town.", "meaning": "büyütmek, yetiştirmek"}]'::jsonb, 'hard', true, 'en', 'separable-inseparable-phrasal-verbs', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('95a86334-555e-4616-88f5-3594cf79dd7f', 'yokdil', 'You can always count ------- when you need help.', '[{"id": "a", "text": "on me"}, {"id": "b", "text": "me on"}, {"id": "c", "text": "on I"}, {"id": "d", "text": "I on"}]'::jsonb, 'a', 'count on ayrılamaz bir phrasal verb''dür, nesne her zaman parçacıktan sonra gelir.', '[{"word": "count on", "example": "You can count on her.", "meaning": "güvenmek, dayanmak"}]'::jsonb, 'medium', true, 'en', 'separable-inseparable-phrasal-verbs', 'system', 'approved');
