-- 035_grammar_reference_wave6.sql
--
-- Gramer Rehberi 6. dalga genisleme -- Cambridge "English Grammar in Use"
-- (Murphy, 5. baski) icerigine paralel, kitabin ana govdesindeki son
-- kucuk eksikler: Future (bolum 3), If ve Wish / Conditionals (bolum 5),
-- Passive (bolum 6), Reported Speech (bolum 7).
--
-- ICERIK KAYNAGI VE TELIF NOTU: Bu migration'daki grammar_topics kayitlarinin
-- SADECE unite/konu basliklari kitaptaki standart dilbilgisi terminolojisinden
-- esinlenerek adlandirilmistir -- bunlar telife konu olmayan genel gramer
-- kavramlaridir. Kural aciklamalari (rule_content_md), ornek cumleler
-- (example_sentences), sik hatalar (common_mistakes) ve tum exam_questions
-- sorulari %100 ozgun olarak yazilmistir. Kitaptan hicbir cumle, ornek veya
-- alistirma birebir kopyalanmamistir.
--
-- Icerik: yeni grammar_categories yok (mevcut future, conditionals, passive,
-- reported-speech kategorilerine eklendi), 5 yeni grammar_topics
-- (future'a +1: be-about-to, conditionals'a +1: mixed-conditionals,
-- passive'e +2: reporting-passive, be-vs-get-passive, reported-speech'e +1:
-- reported-commands-requests), 10 yeni exam_questions (her yeni konu icin
-- 2 soru, topic_tag = grammar_topics.slug ile birebir eslesir).
--
-- Bu dalga ile kitabin (Murphy, 5. baski, 145 unite) ana govdesindeki
-- buyuk bolumler icerik olarak kapsanmis olur; kalan eksikler kucuk
-- ekler/referans tablolari seviyesindedir (bkz. devir notu).
--
-- Bu SQL, Supabase MCP apply_migration araciyla proje mrxeuxscyztpiuagsumh
-- uzerinde 2 parcada (topics, questions) zaten uygulanmistir; bu dosya repo
-- gecmisi icin ayniyla tekrar eder.

-- new grammar_topics
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('565af0a1-31d1-4d34-9816-c4ef6f50ad17', 'be-about-to', (SELECT id FROM grammar_categories WHERE slug = 'future'), 'en', 'be about to: Çok Yakın Gelecek', 'be about to, çok yakın bir gelecekte, neredeyse hemen gerçekleşecek bir eylemi anlatmak için kullanılır.', 'b1', ARRAY['yds','yokdil'], '- be about to + fiil (yalın hal), bir eylemin ÇOK YAKIN bir gelecekte, neredeyse şu anda gerçekleşeceğini anlatır: "The plane is about to take off."
- be about to, going to''dan daha KISA bir zaman dilimini ifade eder; going to genel bir niyeti/planı, about to ise anlık, hemen gerçekleşecek bir eylemi anlatır.
- "was/were about to" geçmişte YAPILMASI PLANLANIP SONRADAN GERÇEKLEŞMEYEN bir eylemi anlatmak için de kullanılır: "I was about to call you when you texted me."
- "just about to" ifadesi bu anlığı daha da vurgulamak için sıkça kullanılır: "We were just about to leave."', '[{"en": "Hurry up! The movie is about to start.", "tr": "Acele et! Film başlamak üzere."}, {"en": "She''s about to give birth any day now.", "tr": "Herhangi bir gün doğum yapmak üzere."}, {"en": "I was about to leave when the phone rang.", "tr": "Tam çıkacaktım ki telefon çaldı."}]'::jsonb, '[{"wrong": "I am about to go to Paris next month.", "correct": "I am going to go to Paris next month.", "note": "uzak bir gelecekteki plan için about to değil going to kullanılmalıdır."}, {"wrong": "The train was about to leaving when we arrived.", "correct": "The train was about to leave when we arrived.", "note": "about to''dan sonra fiilin yalın hali (bare infinitive) gelir, -ing değil."}]'::jsonb, 'published', 'manual', 4);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('ed45e65d-691c-443e-880a-d7335918aa9b', 'mixed-conditionals', (SELECT id FROM grammar_categories WHERE slug = 'conditionals'), 'en', 'Mixed Conditionals: Karma Şart Cümleleri', 'Karma şart cümleleri, geçmişteki bir durumun şimdiki bir sonucunu veya genel/sürekli bir durumun geçmişteki bir sonucunu anlatmak için ikinci ve üçüncü tip şart cümlelerinin farklı zaman dilimlerini bir arada kullanır.', 'c1', ARRAY['yds','yokdil','toefl'], '- TİP 1 Karma: if + past perfect (üçüncü tip koşul) + would + yalın fiil (ikinci tip sonuç) → GEÇMİŞTEKİ bir durumun ŞİMDİKİ bir sonucunu anlatır: "If I had studied medicine, I would be a doctor now."
- TİP 2 Karma: if + were/geçmiş zaman (ikinci tip koşul, genel/sürekli durum) + would have + üçüncü hal (üçüncü tip sonuç) → GENEL/SÜREKLİ bir özelliğin GEÇMİŞTEKİ bir sonucunu anlatır: "If she weren''t so shy, she would have applied for the job."
- Bu yapıların seçimi, koşulun ve sonucun hangi ZAMAN DİLİMİNDE (geçmiş mi şimdi/genel mi) gerçekleştiğine bağlıdır; standart ikinci/üçüncü tip kalıplarla karıştırılmamalıdır.
- Mixed conditionals genellikle gerçek hayattaki pişmanlık veya varsayımsal durumları daha kesin bir zaman ilişkisiyle anlatmak için kullanılır.', '[{"en": "If I hadn''t missed the flight, I would be at the conference right now.", "tr": "Uçağı kaçırmasaydım, şu anda konferansta olurdum."}, {"en": "If he weren''t so lazy, he would have finished the project by now.", "tr": "Bu kadar tembel olmasaydı, projeyi şimdiye kadar bitirmiş olurdu."}, {"en": "If you were more careful, you wouldn''t have broken the vase.", "tr": "Daha dikkatli olsaydın, vazoyu kırmazdın."}]'::jsonb, '[{"wrong": "If I had studied medicine, I would have been a doctor now.", "correct": "If I had studied medicine, I would be a doctor now.", "note": "sonuç şimdiki zamanla ilgiliyse \"would have + üçüncü hal\" değil \"would + yalın fiil\" kullanılmalıdır."}, {"wrong": "If she wasn''t so shy, she would apply for the job.", "correct": "If she weren''t so shy, she would have applied for the job.", "note": "sonuç geçmişte gerçekleşmiş/gerçekleşmemiş bir eylemi anlatıyorsa \"would have + üçüncü hal\" kullanılmalıdır."}]'::jsonb, 'published', 'manual', 5);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('b1079884-d3da-4b36-9f5f-fcb139600999', 'reporting-passive', (SELECT id FROM grammar_categories WHERE slug = 'passive'), 'en', 'Reporting Passive: it is said that... / be said to Yapısı', 'Genel bir görüşü veya inanışı kaynağını belirtmeden aktarmak için it + be + said/believed/thought/reported + that ya da özne + be + said/believed + to yapıları kullanılır.', 'b2', ARRAY['yds','yokdil','toefl'], '- Genel bir kanaat, söylenti veya inanışı KAYNAK belirtmeden aktarmak için "It is said/believed/thought/reported/known that + cümle" kalıbı kullanılır: "It is said that the company is losing money."
- Aynı anlam, "Özne + be + said/believed/thought + to + fiil" yapısıyla da kurulabilir: "The company is said to be losing money."
- Eylem ANA cümledeki zamandan ÖNCE gerçekleşmişse, "to have + üçüncü hal" kullanılır: "He is believed to have left the country."
- Bu yapı özellikle haber dilinde ve akademik/resmi metinlerde, iddiayı kime ait olduğunu belirtmeden aktarmak için tercih edilir.', '[{"en": "It is reported that the president will visit the region next week.", "tr": "Başkanın gelecek hafta bölgeyi ziyaret edeceği bildiriliyor."}, {"en": "She is thought to be one of the best scientists in her field.", "tr": "Alanındaki en iyi bilim insanlarından biri olduğu düşünülüyor."}, {"en": "The suspect is believed to have fled the country.", "tr": "Şüphelinin ülkeden kaçtığına inanılıyor."}]'::jsonb, '[{"wrong": "The company is said losing money.", "correct": "The company is said to be losing money.", "note": "\"be said\" yapısından sonra \"to + fiil\" gelmelidir, doğrudan -ing kullanılamaz."}, {"wrong": "He is believed to left the country.", "correct": "He is believed to have left the country.", "note": "bildirilen eylem ana cümledeki zamandan önce gerçekleştiyse \"to have + üçüncü hal\" kullanılmalıdır."}]'::jsonb, 'published', 'manual', 6);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('fa970f7a-e8c6-4239-8425-9381c20415e1', 'be-vs-get-passive', (SELECT id FROM grammar_categories WHERE slug = 'passive'), 'en', 'be passive ve get passive Farkı', 'be passive daha resmi ve nötr bir edilgen yapı oluştururken, get passive daha günlük konuşma dilinde kullanılır ve genellikle ani, beklenmedik veya olumsuz bir değişimi vurgular.', 'b2', ARRAY['yds','yokdil','toefl'], '- be + üçüncü hal (be passive), edilgen çatının STANDART ve RESMİ formudur, her bağlamda kullanılabilir: "The window was broken."
- get + üçüncü hal (get passive), daha GÜNLÜK/KONUŞMA diline özgüdür ve genellikle ANİ, BEKLENMEDİK veya bir SÜREÇ sonucu gerçekleşen bir değişimi vurgular: "The window got broken during the storm."
- get passive sıklıkla OLUMSUZ veya talihsiz bir durumu anlatır: get fired (kovulmak), get hurt (yaralanmak), get caught (yakalanmak).
- get passive RESMİ yazı dilinde (akademik metin, haber, iş yazışması) tercih edilmez; be passive kullanılmalıdır.', '[{"en": "He got fired for being late too many times.", "tr": "Çok fazla geç kaldığı için kovuldu."}, {"en": "The report was submitted to the manager yesterday.", "tr": "Rapor dün müdüre teslim edildi."}, {"en": "Be careful, you might get hurt on that ladder.", "tr": "Dikkat et, o merdivende yaralanabilirsin."}]'::jsonb, '[{"wrong": "The annual report get published every March.", "correct": "The annual report is published every March.", "note": "resmi/yazılı bir bağlamda get passive değil be passive tercih edilmelidir."}, {"wrong": "My phone was stolen while I wasn''t looking, it happened so suddenly, out of nowhere.", "correct": "My phone got stolen while I wasn''t looking.", "note": "ani ve beklenmedik bir olayı vurgulamak için günlük dilde get passive tercih edilir."}]'::jsonb, 'published', 'manual', 7);
INSERT INTO grammar_topics (id, slug, category_id, learning_lang, title_tr, summary_tr, level, exam_relevance, rule_content_md, example_sentences, common_mistakes, status, source_type, sort_order) VALUES ('aff3e586-240d-4057-be58-92ff3333882b', 'reported-commands-requests', (SELECT id FROM grammar_categories WHERE slug = 'reported-speech'), 'en', 'Reported Commands and Requests: Emir ve Rica Cümlelerinin Aktarımı', 'Emir, rica ve öneri cümleleri aktarılırken that-cümleciği yerine tell/ask/advise gibi fiillerden sonra nesne + to-infinitive yapısı kullanılır.', 'b1', ARRAY['yds','yokdil'], '- Doğrudan bir EMİR aktarılırken, tell (veya order, instruct) fiili + nesne + to-infinitive kullanılır: "Close the door." → "She told me to close the door."
- Doğrudan bir RİCA aktarılırken, ask fiili + nesne + to-infinitive kullanılır: "Could you help me?" → "She asked me to help her."
- OLUMSUZ bir emir/rica aktarılırken, to-infinitive''den önce not eklenir: "Don''t be late." → "He told us not to be late."
- please ile yapılan kibar bir rica da genellikle ask ile aktarılır, please kelimesi aktarılan cümlede TEKRARLANMAZ: "Please sit down." → "She asked us to sit down."
- Bu yapıda that-cümleciği ve doğrudan alıntı fiil çekimleri kullanılmaz; doğrudan nesne + to-infinitive kalıbı yeterlidir.', '[{"en": "The officer told us to wait there.", "tr": "Memur bizden orada beklememizi istedi."}, {"en": "She asked us not to smoke there.", "tr": "Orada sigara içmememizi rica etti."}, {"en": "The teacher told the students to turn off their phones.", "tr": "Öğretmen öğrencilerden telefonlarını kapatmalarını istedi."}]'::jsonb, '[{"wrong": "She told that I should close the door.", "correct": "She told me to close the door.", "note": "emir aktarımında that-cümleciği değil nesne + to-infinitive kullanılır."}, {"wrong": "He told us to not be late.", "correct": "He told us not to be late.", "note": "olumsuz emir/rica aktarımında not, to-infinitive''den ÖNCE gelir."}]'::jsonb, 'published', 'manual', 2);
-- new exam_questions
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('05bd7467-24cc-4ce2-922b-b5047df97bed', 'yds', 'Look at those dark clouds — it ------- rain any minute now.', '[{"id": "a", "text": "is about to"}, {"id": "b", "text": "is going to about"}, {"id": "c", "text": "about to"}, {"id": "d", "text": "will about to"}]'::jsonb, 'a', 'Çok yakın bir gelecekte gerçekleşecek bir eylem anlatıldığı için be about to kullanılır.', '[{"word": "be about to", "example": "The show is about to begin.", "meaning": "çok yakın gelecek"}]'::jsonb, 'medium', true, 'en', 'be-about-to', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('4365286d-d370-46d3-b008-1d4484b373c6', 'yokdil', 'I ------- leave the house when I remembered I''d left the oven on.', '[{"id": "a", "text": "was about to"}, {"id": "b", "text": "am about to"}, {"id": "c", "text": "was going about to"}, {"id": "d", "text": "about to"}]'::jsonb, 'a', 'Geçmişte yapılması planlanıp gerçekleşmeyen bir eylem anlatıldığı için was about to kullanılır.', '[{"word": "was about to", "example": "We were about to leave when it started raining.", "meaning": "geçmişte planlanıp gerçekleşmeyen an"}]'::jsonb, 'hard', true, 'en', 'be-about-to', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('f148ba69-89df-4293-a003-ea9fb5e71c7e', 'yds', 'If I ------- the map, we wouldn''t be lost right now.', '[{"id": "a", "text": "had brought"}, {"id": "b", "text": "brought"}, {"id": "c", "text": "would bring"}, {"id": "d", "text": "have brought"}]'::jsonb, 'a', 'Geçmişteki bir durumun şimdiki sonucu anlatıldığı için if-cümleciğinde past perfect (üçüncü tip koşul formu) kullanılır.', '[{"word": "mixed conditional (tip 1)", "example": "If I had saved money, I would be rich now.", "meaning": "geçmiş koşul + şimdiki sonuç"}]'::jsonb, 'hard', true, 'en', 'mixed-conditionals', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('85884530-9475-49d8-bee9-8d5d2978c76a', 'yokdil', 'If he ------- more organized, he would have completed the report on time last week.', '[{"id": "a", "text": "were"}, {"id": "b", "text": "had been"}, {"id": "c", "text": "would be"}, {"id": "d", "text": "is"}]'::jsonb, 'a', 'Genel/sürekli bir özelliğin geçmişteki sonucu anlatıldığı için if-cümleciğinde ikinci tip koşul formu (were) kullanılır.', '[{"word": "mixed conditional (tip 2)", "example": "If she were more patient, she wouldn''t have quit.", "meaning": "genel özellik + geçmiş sonuç"}]'::jsonb, 'hard', true, 'en', 'mixed-conditionals', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('2096e262-2585-4d80-a1dc-93b81878fc83', 'yds', 'The ancient bridge ------- built over 500 years ago.', '[{"id": "a", "text": "is said to have been"}, {"id": "b", "text": "is said to be"}, {"id": "c", "text": "is said having been"}, {"id": "d", "text": "said to have been"}]'::jsonb, 'a', 'Bildirilen eylem ana cümledeki zamandan önce gerçekleştiği ve edilgen olduğu için "is said to have been" kullanılır.', '[{"word": "be said to have + üçüncü hal", "example": "The castle is said to have been built in the 12th century.", "meaning": "geçmişte gerçekleşmiş, kaynağı belirsiz iddia"}]'::jsonb, 'hard', true, 'en', 'reporting-passive', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('432fb290-8a9e-4ca3-92b2-acc58eea222d', 'yokdil', 'It ------- that the new policy will reduce unemployment significantly.', '[{"id": "a", "text": "is expected"}, {"id": "b", "text": "expects"}, {"id": "c", "text": "is expecting"}, {"id": "d", "text": "expected"}]'::jsonb, 'a', 'Kaynağı belirtilmeyen genel bir beklentiyi aktarmak için "It is expected that..." kalıbı kullanılır.', '[{"word": "it is + reporting verb + that", "example": "It is believed that the plan will succeed.", "meaning": "kaynağı belirtilmeyen genel görüş"}]'::jsonb, 'medium', true, 'en', 'reporting-passive', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('39ca9c6b-0f77-4cd8-9d88-bfc3317de20f', 'yds', 'Be careful with that knife, you could ------- if you''re not paying attention.', '[{"id": "a", "text": "get cut"}, {"id": "b", "text": "be cutting"}, {"id": "c", "text": "cut"}, {"id": "d", "text": "getting cut"}]'::jsonb, 'a', 'Ani ve beklenmedik bir yaralanma ihtimali günlük dilde get passive ile anlatılır.', '[{"word": "get cut", "example": "She got cut while chopping vegetables.", "meaning": "ani, beklenmedik bir yaralanma"}]'::jsonb, 'medium', true, 'en', 'be-vs-get-passive', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('3ef1273b-886e-419b-8248-ebd120fd82fc', 'yokdil', 'According to the official announcement, the new regulations ------- next January.', '[{"id": "a", "text": "will be implemented"}, {"id": "b", "text": "will get implemented"}, {"id": "c", "text": "will getting implemented"}, {"id": "d", "text": "implement"}]'::jsonb, 'a', 'Resmi bir duyuru/bağlam söz konusu olduğu için get passive değil be passive tercih edilir.', '[{"word": "be implemented", "example": "The new law will be implemented next year.", "meaning": "resmi bağlamda edilgen yapı"}]'::jsonb, 'medium', true, 'en', 'be-vs-get-passive', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('caa66689-9d3d-4659-8e69-ed890a71e6e9', 'yds', '"Please don''t touch the paintings," the guide said. → The guide asked us ------- the paintings.', '[{"id": "a", "text": "not to touch"}, {"id": "b", "text": "to not touch"}, {"id": "c", "text": "don''t touch"}, {"id": "d", "text": "that we don''t touch"}]'::jsonb, 'a', 'Olumsuz bir rica aktarılırken not, to-infinitive''den önce gelir: not to touch.', '[{"word": "ask sb not to do", "example": "She asked him not to shout.", "meaning": "olumsuz rica aktarımı"}]'::jsonb, 'medium', true, 'en', 'reported-commands-requests', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('1e53b2ae-02f2-4d1d-8691-be28a9b6264d', 'yokdil', '"Finish your homework before dinner," my mother said. → My mother told me ------- my homework before dinner.', '[{"id": "a", "text": "to finish"}, {"id": "b", "text": "finish"}, {"id": "c", "text": "that I finish"}, {"id": "d", "text": "finishing"}]'::jsonb, 'a', 'Emir aktarımında tell fiilinden sonra nesne + to-infinitive kullanılır.', '[{"word": "tell sb to do", "example": "He told her to hurry up.", "meaning": "emir aktarımı"}]'::jsonb, 'easy', true, 'en', 'reported-commands-requests', 'system', 'approved');
