-- 036_grammar_reference_wave7_appendices_and_missing_questions.sql
--
-- Gramer Rehberi -- Madde 17 (Ekler) + eksik pratik sorularinin kapatilmasi.
--
-- BOLUM 1 -- Ekler: kitaptaki Eklerin (duzensiz fiiller, yazim kurallari,
-- kisaltmalar, fiil/sifat+edat kaliplari, Amerikan/Ingiliz Ingilizcesi
-- farklari, noktalama) SADECE genel/standart basliklarindan esinlenilerek,
-- 7 adet ozgun referans notu ayri grammar_topics satiri acmadan, ilgili
-- mevcut konularin rule_content_md alanina eklendi (UPDATE ... || ).
--
-- BOLUM 2 -- Eksik pratik sorulari: uygulamada "Bu konu icin henuz pratik
-- sorusu eklenmedi" uyarisi cikan 12 eski konu (2. dalgadan once eklenmis,
-- hic exam_questions'i olmayan konular) icin 2'ser ozgun soru yazildi (24
-- yeni soru). Artik TUM grammar_topics satirlarinin en az 1 pratik sorusu
-- var (dogrulandi: topics_without_q = 0).
--
-- ICERIK KAYNAGI VE TELIF NOTU: onceki migration'larla ayni ilke -- SADECE
-- standart dilbilgisi terminolojisi/basliklari kullanilmistir, tum metin
-- (kural notlari, sorular, aciklamalar) %100 ozgun yazilmistir.
--
-- Bu SQL, Supabase MCP apply_migration araciyla proje mrxeuxscyztpiuagsumh
-- uzerinde 2 parcada (appendices UPDATE, missing questions INSERT) zaten
-- uygulanmistir; bu dosya repo gecmisi icin ayniyla tekrar eder.

-- Madde 17: Ekler -- mevcut konulara referans notu ekleme (7 adet)
UPDATE grammar_topics SET rule_content_md = rule_content_md || '
' || '- **EK — Düzensiz Fiiller (Irregular Verbs):** İngilizcede çok sayıda fiil, past simple ve past participle (V2/V3) formlarını -ed eki almadan, kendine özgü bir şekilde oluşturur. Present Perfect ve Past Simple kurarken bu formları ezbere bilmek gerekir. En sık kullanılan bazı düzensiz fiiller (yalın hal — V2 — V3): be-was/were-been, begin-began-begun, break-broke-broken, bring-brought-brought, build-built-built, buy-bought-bought, catch-caught-caught, choose-chose-chosen, come-came-come, do-did-done, drink-drank-drunk, drive-drove-driven, eat-ate-eaten, fall-fell-fallen, feel-felt-felt, find-found-found, fly-flew-flown, forget-forgot-forgotten, get-got-got/gotten, give-gave-given, go-went-gone, have-had-had, hear-heard-heard, keep-kept-kept, know-knew-known, leave-left-left, lose-lost-lost, make-made-made, meet-met-met, pay-paid-paid, put-put-put, read-read-read, ring-rang-rung, run-ran-run, say-said-said, see-saw-seen, sell-sold-sold, send-sent-sent, sing-sang-sung, sit-sat-sat, speak-spoke-spoken, spend-spent-spent, swim-swam-swum, take-took-taken, teach-taught-taught, tell-told-told, think-thought-thought, understand-understood-understood, wake-woke-woken, wear-wore-worn, win-won-won, write-wrote-written.' WHERE slug = 'present-perfect-vs-past-simple';
UPDATE grammar_topics SET rule_content_md = rule_content_md || '
' || '- **EK — Kısaltılmış Yapılar (Contractions):** Günlük ve konuşma dilinde özne ile yardımcı fiil, ya da yardımcı fiil ile "not" kelimesi kısaltılarak birleştirilir. Yaygın kısaltmalar: I''m (I am), you''re (you are), he''s/she''s/it''s (he/she/it is), we''re (we are), they''re (they are), I''ve (I have), I''ll (I will), I''d (I would/had), isn''t (is not), aren''t (are not), wasn''t (was not), weren''t (were not), don''t (do not), doesn''t (does not), didn''t (did not), haven''t (have not), hasn''t (has not), hadn''t (had not), won''t (will not), wouldn''t (would not), can''t (cannot), couldn''t (could not), shouldn''t (should not), mustn''t (must not). Resmi/akademik yazıda ("essay", rapor) kısaltmalar genellikle TERCİH EDİLMEZ, açık form kullanılır; günlük konuşmada ve gayriresmi yazışmada kısaltmalar doğaldır.' WHERE slug = 'question-tags';
UPDATE grammar_topics SET rule_content_md = rule_content_md || '
' || '- **EK — Fiile -ing Eklenirken Yazım Kuralları:** (1) Sessiz "e" ile biten fiillerde "e" düşer: make→making, write→writing, have→having. (2) Tek heceli, tek sesli harfle biten ve tek ünsüzle biten fiillerde son ünsüz ikizlenir: run→running, sit→sitting, stop→stopping (ama fix→fixing, çünkü x tek harf sayılır ve ikizlenmez). (3) "ie" ile biten fiillerde "ie" → "y" olur: die→dying, lie→lying, tie→tying. (4) "ee", "oe", "ye" gibi çift sesli harfle bitenlerde normal şekilde -ing eklenir: see→seeing, agree→agreeing.' WHERE slug = 'present-simple-vs-continuous';
UPDATE grammar_topics SET rule_content_md = rule_content_md || '
' || '- **EK — Düzenli Fiillere -ed Eklenirken Yazım Kuralları:** (1) Fiil zaten "e" ile bitiyorsa sadece "-d" eklenir: like→liked, agree→agreed. (2) Tek heceli, tek sesli harfle biten ve tek ünsüzle biten fiillerde son ünsüz ikizlenir: stop→stopped, plan→planned (ama visit→visited, çünkü ikinci hece vurgulu değil). (3) Sessiz harften sonra "y" ile bitenlerde "y"→"i" olur ve "-ed" eklenir: study→studied, carry→carried (ama play→played, çünkü "y"den önce sesli harf var). Düzensiz fiiller için ayrı bir ek listesi mevcuttur (bkz. Present Perfect ve Past Simple Farkı konusu).' WHERE slug = 'past-simple-vs-continuous';
UPDATE grammar_topics SET rule_content_md = rule_content_md || '
' || '- **EK — Sık Kullanılan Fiil + Edat ve Sıfat + Edat Kalıpları:** Fiil + edat: listen TO, look AT/FOR, wait FOR, depend ON, believe IN, apologize FOR, congratulate sb ON, consist OF, deal WITH, insist ON, succeed IN, suffer FROM, worry ABOUT. Sıfat + edat: interested IN, afraid OF, good/bad AT, famous FOR, proud OF, responsible FOR, similar TO, different FROM, tired OF, satisfied WITH, aware OF, capable OF. Bu kalıplarda edat, fiilin/sıfatın anlamına göre SABİTTİR ve genellikle ezbere öğrenilmesi gerekir — Türkçedeki karşılığıyla birebir örtüşmeyebilir (ör. "interested in" Türkçede "-e ilgili" değil "ile ilgilenen" anlamındadır).' WHERE slug = 'dependent-prepositions';
UPDATE grammar_topics SET rule_content_md = rule_content_md || '
' || '- **EK — Amerikan ve İngiliz İngilizcesi Arasındaki Farklar:** Yazım: colour/color, favourite/favorite, centre/center, travelling/traveling, realise/realize. Kelime: flat/apartment, lorry/truck, holiday/vacation, lift/elevator, autumn/fall, rubbish/garbage, chemist''s/drugstore, mobile phone/cell phone, biscuit/cookie. YDS/YÖKDİL gibi sınavlarda genellikle İngiliz İngilizcesi esas alınır ama her iki varyantın da doğru kabul edildiği sorularla karşılaşılabilir; bir metin içinde tutarlı bir varyant kullanmak (ikisini karıştırmamak) yazma görevlerinde önemlidir.' WHERE slug = 'word-formation-collocations';
UPDATE grammar_topics SET rule_content_md = rule_content_md || '
' || '- **EK — Temel Noktalama ve Büyük Harf Kuralları:** (1) Bağlaçlarla (and, but, or, so, for, nor, yet) birleşen iki tam cümle arasına VİRGÜL konur: "I called her, but she didn''t answer." (2) Bir cümleyi ikiye bölebilecek iki bağımsız cümleyi bağlaç olmadan birleştirmek için NOKTALI VİRGÜL kullanılır: "It was raining; we stayed home." (3) Özel isimler, ülke/dil adları, ay ve gün isimleri ile cümlenin ilk harfi her zaman BÜYÜK HARFLE başlar: Turkey, Turkish, Monday, September. (4) "I" (ben) zamiri cümle içinde her zaman büyük harfle yazılır. Bu kurallar özellikle yazma (essay) bölümlerinde sık gözden kaçan hatalardandır.' WHERE slug = 'connectors-linking-words';
-- missing exam_questions for 12 pre-existing topics (2 each, 24 total)
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('f8c5661b-4e35-4365-ad92-642042403247', 'yds', 'I saw ------- elephant at the zoo yesterday; ------- elephant was enormous.', '[{"id": "a", "text": "an / the"}, {"id": "b", "text": "a / the"}, {"id": "c", "text": "the / an"}, {"id": "d", "text": "an / a"}]'::jsonb, 'a', 'İlk bahsedilişte ünlü sesle başlayan tekil sayılabilir isimden önce ''an'', ikinci bahsedilişte belirli hale geldiği için ''the'' kullanılır.', '[{"word": "a/an vs the", "example": "I bought a book. The book was expensive.", "meaning": "ilk bahsediş / belirli hale gelmiş"}]'::jsonb, 'easy', true, 'en', 'articles', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('6c8a03c9-f5e9-4082-b82a-076bc845a019', 'yokdil', '------- information she gave us was completely wrong.', '[{"id": "a", "text": "The"}, {"id": "b", "text": "A"}, {"id": "c", "text": "An"}, {"id": "d", "text": "(artikelsiz)"}]'::jsonb, 'a', 'information sayılamayan bir isimdir ama burada ''she gave us'' ile belirli hale getirilmiştir, bu yüzden ''the'' kullanılır.', '[{"word": "the + sayılamayan isim", "example": "The water in this bottle is cold.", "meaning": "belirli hale gelmiş sayılamayan isim"}]'::jsonb, 'medium', true, 'en', 'articles', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('edf337d5-68e4-43b2-8022-de0533dcd0d5', 'yds', 'The scientist ------- discovered the vaccine won a major award.', '[{"id": "a", "text": "who"}, {"id": "b", "text": "whom"}, {"id": "c", "text": "whose"}, {"id": "d", "text": "which"}]'::jsonb, 'a', 'Özne konumundaki bir kişiyi tanımlayan ilgi cümleciğinde ''who'' kullanılır.', '[{"word": "who (özne)", "example": "The man who called you is my uncle.", "meaning": "kişi + özne rolü"}]'::jsonb, 'easy', true, 'en', 'relative-clauses-defining', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('e026b767-e100-430b-a6f7-365eb0305fa1', 'yokdil', 'This is the company ------- products are exported to over 40 countries.', '[{"id": "a", "text": "whose"}, {"id": "b", "text": "who"}, {"id": "c", "text": "which"}, {"id": "d", "text": "that"}]'::jsonb, 'a', 'Bir şeye/kişiye ait olan bir isimden önce iyelik anlamı taşıyan ''whose'' kullanılır.', '[{"word": "whose", "example": "That''s the writer whose novel won the prize.", "meaning": "iyelik ilgi zamiri"}]'::jsonb, 'medium', true, 'en', 'relative-clauses-defining', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('0631c5d1-525d-4df4-8a7f-2ea549c3156b', 'yds', 'If you ------- this button, the machine ------- automatically.', '[{"id": "a", "text": "press / stops"}, {"id": "b", "text": "pressed / stopped"}, {"id": "c", "text": "will press / stops"}, {"id": "d", "text": "press / will have stopped"}]'::jsonb, 'a', 'Genel bir gerçek/otomatik sonuç anlatıldığı için zero conditional (if + present simple, present simple) kullanılır.', '[{"word": "zero conditional", "example": "If you heat water to 100°C, it boils.", "meaning": "her zaman geçerli gerçek"}]'::jsonb, 'easy', true, 'en', 'conditionals-zero-first', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('dc7ff458-128a-4d7b-aab4-59ea9c441722', 'yokdil', 'If it ------- tomorrow, we ------- the picnic.', '[{"id": "a", "text": "rains / will cancel"}, {"id": "b", "text": "will rain / cancel"}, {"id": "c", "text": "rains / cancel"}, {"id": "d", "text": "rained / will cancel"}]'::jsonb, 'a', 'Gelecekle ilgili gerçekçi bir koşul anlatıldığı için first conditional (if + present simple, will + yalın fiil) kullanılır.', '[{"word": "first conditional", "example": "If she studies hard, she will pass.", "meaning": "gerçekleşmesi olası gelecek koşulu"}]'::jsonb, 'easy', true, 'en', 'conditionals-zero-first', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('d68260f0-c780-4c36-a5b3-3f4d1ef0e9f8', 'yds', 'If I ------- you, I ------- that job offer immediately.', '[{"id": "a", "text": "were / would accept"}, {"id": "b", "text": "was / will accept"}, {"id": "c", "text": "am / would accept"}, {"id": "d", "text": "had been / would have accepted"}]'::jsonb, 'a', 'Şimdiki zamanla ilgili hayali/gerçek dışı bir durum anlatıldığı için second conditional (if + were, would + yalın fiil) kullanılır.', '[{"word": "if I were you", "example": "If I were you, I would apologize.", "meaning": "hayali tavsiye kalıbı"}]'::jsonb, 'medium', true, 'en', 'conditionals-second', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('85e13b17-faac-42fb-ac5e-a4198724574a', 'yokdil', 'If she ------- more free time, she ------- a musical instrument.', '[{"id": "a", "text": "had / would learn"}, {"id": "b", "text": "has / will learn"}, {"id": "c", "text": "had had / would have learned"}, {"id": "d", "text": "have / would learn"}]'::jsonb, 'a', 'Şu anki durumla ilgili gerçek dışı bir varsayım anlatıldığı için second conditional kullanılır.', '[{"word": "second conditional", "example": "If I had a car, I would drive to work.", "meaning": "şimdiki gerçek dışı durum"}]'::jsonb, 'medium', true, 'en', 'conditionals-second', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('6d366b5c-dc0c-4a05-a08a-16f680704d2a', 'yds', 'You ------- smoke in this building; it''s strictly against the rules.', '[{"id": "a", "text": "mustn''t"}, {"id": "b", "text": "don''t have to"}, {"id": "c", "text": "needn''t"}, {"id": "d", "text": "might not"}]'::jsonb, 'a', 'Kesin bir yasağı anlatmak için mustn''t kullanılır.', '[{"word": "mustn''t", "example": "You mustn''t park here.", "meaning": "kesin yasak"}]'::jsonb, 'easy', true, 'en', 'modals-obligation-advice', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('a60ce338-a59e-482a-bc66-d81f02ec43f8', 'yokdil', 'You look exhausted. You ------- take a break.', '[{"id": "a", "text": "should"}, {"id": "b", "text": "must"}, {"id": "c", "text": "can"}, {"id": "d", "text": "will"}]'::jsonb, 'a', 'Bir tavsiye verildiği için should kullanılır.', '[{"word": "should (tavsiye)", "example": "You should see a doctor.", "meaning": "tavsiye"}]'::jsonb, 'easy', true, 'en', 'modals-obligation-advice', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('789b6a36-cac3-42cf-9d2f-68746165bd5b', 'yds', 'She hasn''t answered any calls all day. She ------- be busy with something important.', '[{"id": "a", "text": "must"}, {"id": "b", "text": "can''t"}, {"id": "c", "text": "needn''t"}, {"id": "d", "text": "should"}]'::jsonb, 'a', 'Mevcut kanıtlara dayanarak güçlü bir olasılık çıkarımı yapıldığı için must kullanılır.', '[{"word": "must (çıkarım)", "example": "The lights are off, they must be asleep.", "meaning": "güçlü olasılık çıkarımı"}]'::jsonb, 'medium', true, 'en', 'modals-deduction', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('7fd0d257-e828-4220-978c-f83ce34e5288', 'yokdil', 'He said he''d never been to Paris before, but he knew the streets so well. That ------- true.', '[{"id": "a", "text": "can''t be"}, {"id": "b", "text": "must be"}, {"id": "c", "text": "might be"}, {"id": "d", "text": "should be"}]'::jsonb, 'a', 'Verilen bilgiyle çelişen, imkansız görünen bir durum için can''t be kullanılır.', '[{"word": "can''t be (imkansız çıkarım)", "example": "You can''t be serious!", "meaning": "imkansız/inanılmaz görünen durum"}]'::jsonb, 'medium', true, 'en', 'modals-deduction', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('79e3a201-f157-499a-a882-01c11cb634e0', 'yds', 'This bridge ------- by a famous Ottoman architect in the 16th century.', '[{"id": "a", "text": "was designed"}, {"id": "b", "text": "designed"}, {"id": "c", "text": "is designed"}, {"id": "d", "text": "has design"}]'::jsonb, 'a', 'Geçmişte gerçekleşmiş, faili önemli olmayan bir eylem edilgen ve past simple ile anlatılır.', '[{"word": "was/were + üçüncü hal", "example": "The email was sent yesterday.", "meaning": "geçmiş edilgen yapı"}]'::jsonb, 'easy', true, 'en', 'passive-present-past', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('935b8306-e614-4c0c-8999-c516f881aa67', 'yokdil', 'Thousands of packages ------- every day at this warehouse.', '[{"id": "a", "text": "are processed"}, {"id": "b", "text": "process"}, {"id": "c", "text": "processed"}, {"id": "d", "text": "is processed"}]'::jsonb, 'a', 'Şu anki genel/rutin bir eylem edilgen present simple ile anlatılır, özne çoğul olduğu için ''are'' kullanılır.', '[{"word": "is/are + üçüncü hal", "example": "These cars are made in Germany.", "meaning": "şimdiki edilgen yapı"}]'::jsonb, 'easy', true, 'en', 'passive-present-past', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('bee216d3-fc86-48c0-893e-d143a5c9836c', 'yds', 'The meeting had to be ------- because of the sudden power outage.', '[{"id": "a", "text": "called off"}, {"id": "b", "text": "called on"}, {"id": "c", "text": "called up"}, {"id": "d", "text": "called out"}]'::jsonb, 'a', '''call off'' bir etkinliği iptal etmek anlamına gelir.', '[{"word": "call off", "example": "They called off the wedding.", "meaning": "iptal etmek"}]'::jsonb, 'medium', true, 'en', 'phrasal-verbs', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('64678bba-3a92-408c-a68b-299255ab2add', 'ielts', 'It took her a while to ------- the news of her promotion.', '[{"id": "a", "text": "take in"}, {"id": "b", "text": "take off"}, {"id": "c", "text": "take after"}, {"id": "d", "text": "take over"}]'::jsonb, 'a', '''take in'' bir bilgiyi zihinsel olarak anlamak/özümsemek anlamına gelir.', '[{"word": "take in", "example": "It''s a lot of information to take in at once.", "meaning": "anlamak, özümsemek"}]'::jsonb, 'hard', true, 'en', 'phrasal-verbs', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('123f3735-8e50-4d81-96b8-eecb0b5c3ad3', 'yds', 'Her decision to resign came as a complete ------- to everyone in the office.', '[{"id": "a", "text": "surprise"}, {"id": "b", "text": "surprising"}, {"id": "c", "text": "surprised"}, {"id": "d", "text": "surprisingly"}]'::jsonb, 'a', '''came as a'' ifadesinden sonra bir isim gelmesi gerekir; ''surprise'' burada isim olarak kullanılır.', '[{"word": "come as a surprise", "example": "His resignation came as a shock.", "meaning": "şaşırtıcı olmak"}]'::jsonb, 'medium', true, 'en', 'word-formation-collocations', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('3414aebe-d2b5-485c-9829-49550d53a96e', 'yokdil', 'The government has announced new measures to ------- unemployment.', '[{"id": "a", "text": "reduce"}, {"id": "b", "text": "reduction"}, {"id": "c", "text": "reducing"}, {"id": "d", "text": "reduced"}]'::jsonb, 'a', '''measures to + fiil'' kalıbında to-infinitive''in yalın fiil hali kullanılır.', '[{"word": "measures to do sth", "example": "They took measures to prevent fraud.", "meaning": "bir şeyi önlemek için tedbir almak"}]'::jsonb, 'medium', true, 'en', 'word-formation-collocations', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('375a4a79-aeb0-453f-b014-21b2c2e515c5', 'yds', '"I have finished my homework," she said. → She said ------- her homework.', '[{"id": "a", "text": "she had finished"}, {"id": "b", "text": "she has finished"}, {"id": "c", "text": "she finished"}, {"id": "d", "text": "she will finish"}]'::jsonb, 'a', 'Aktarılan cümlede present perfect, past perfect''e kayar.', '[{"word": "present perfect → past perfect", "example": "He said he had already eaten.", "meaning": "aktarımda zaman kayması"}]'::jsonb, 'medium', true, 'en', 'reported-speech-statements-questions', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('03b96257-5af8-486d-9f5e-74715d04a087', 'yokdil', '"Where do you live?" he asked me. → He asked me ------- .', '[{"id": "a", "text": "where I lived"}, {"id": "b", "text": "where did I live"}, {"id": "c", "text": "where do I live"}, {"id": "d", "text": "where I live"}]'::jsonb, 'a', 'Aktarılan soru cümlesinde normal cümle sırası (özne + fiil) kullanılır ve zaman bir adım geriye kayar.', '[{"word": "reported wh-questions", "example": "She asked me what I wanted.", "meaning": "aktarılan soru, düz cümle sırası"}]'::jsonb, 'medium', true, 'en', 'reported-speech-statements-questions', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('52c9cc12-deee-4c3e-8a24-f84e68a9bff5', 'yds', 'I ------- this film three times already, so I don''t want to watch it again.', '[{"id": "a", "text": "have seen"}, {"id": "b", "text": "saw"}, {"id": "c", "text": "see"}, {"id": "d", "text": "was seeing"}]'::jsonb, 'a', 'Şimdiki zamanla bağlantılı, ne zaman olduğu belirtilmeyen bir tekrar sayısı anlatıldığı için present perfect kullanılır.', '[{"word": "present perfect (deneyim)", "example": "I have visited Paris twice.", "meaning": "belirsiz zamanda yaşanmış deneyim"}]'::jsonb, 'easy', true, 'en', 'present-perfect-vs-past-simple', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('70034568-f64b-4960-b8a9-b92a7564f76d', 'yokdil', 'She ------- her degree in 2019 and started working right after.', '[{"id": "a", "text": "completed"}, {"id": "b", "text": "has completed"}, {"id": "c", "text": "completes"}, {"id": "d", "text": "has been completing"}]'::jsonb, 'a', 'Belirli bir geçmiş tarih (2019) verildiği için past simple kullanılır, present perfect değil.', '[{"word": "past simple + belirli tarih", "example": "He graduated in 2015.", "meaning": "belirtilen geçmiş zaman noktası"}]'::jsonb, 'easy', true, 'en', 'present-perfect-vs-past-simple', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('1b654d09-ca9b-4475-8857-33d566ea8b4c', 'yds', 'While I ------- dinner, the phone suddenly ------- .', '[{"id": "a", "text": "was cooking / rang"}, {"id": "b", "text": "cooked / was ringing"}, {"id": "c", "text": "was cooking / was ringing"}, {"id": "d", "text": "cooked / rang"}]'::jsonb, 'a', 'Devam eden bir eylem sırasında ani bir olay gerçekleştiği için devam eden eylem past continuous, ani olay past simple ile anlatılır.', '[{"word": "while + past continuous, past simple", "example": "While she was reading, the lights went out.", "meaning": "devam eden eylem + ani kesinti"}]'::jsonb, 'easy', true, 'en', 'past-simple-vs-continuous', 'system', 'approved');
INSERT INTO exam_questions (id, exam_type, question_text, options, correct_option, explanation, related_words, difficulty_level, is_active, learning_lang, topic_tag, source_type, status) VALUES ('4ddd3e9e-841b-4896-9ed2-99c9a74c40f0', 'yokdil', 'This time last year, I ------- abroad for my master''s degree.', '[{"id": "a", "text": "was studying"}, {"id": "b", "text": "studied"}, {"id": "c", "text": "have studied"}, {"id": "d", "text": "study"}]'::jsonb, 'a', 'Geçmişte belirli bir anda devam etmekte olan bir durum anlatıldığı için past continuous kullanılır.', '[{"word": "past continuous (belirli an)", "example": "At 8 pm yesterday, I was having dinner.", "meaning": "geçmişte belirli bir anda süren eylem"}]'::jsonb, 'medium', true, 'en', 'past-simple-vs-continuous', 'system', 'approved');
